### ISSUE TITLE
Need more flexibility in Connect screen contact handling

### ISSUE THREAD

**Issue by micahhainline** [carekit-apple/CareKit#100]
Currently the Connect screen has a very limited set of ways to connect with the contacts. Phone, Message, and Email options exists, but only one can be specified for each type, and the handling of them is fixed. There is no way, for example, to handle the phone connection using VoIP. Especially as CallKit is rolled out, there needs to be much more flexibility in how contacts are handled.
1. Expand OCKContact to allow for multiple phone numbers, email addresses, or message numbers
2. Allow for more flexibility in how the header labels are displayed
3. Allow for more flexibility in how the icons are displayed
4. Add a new common connect item type for video
5. Allow for URL-based handling of the contact item actions for common schemes
6. Allow for custom handling of contact item selection through the delegate

**Comment by tktsubota** [comment]
7. Allow for importing your existing contacts

**Comment by tktsubota** [comment]
<ol start="7">
  <li>Allow for importing your existing contacts</li>
</ol>

**Comment by micahhainline** [comment]
@tktsubota I don't disagree that better integration of the contacts already on the phone would be beneficial, but I'm not sure it belongs in this issue. There are existing mechanisms to read in the contacts and nothing stopping us from using them as a source for the OCKContacts. This issue is trying primarily to address the limitations of what is possible in the handling.

A utility function that converted from CNContact to OCKContact would be great though.

**Comment by umerkhan-apple** [comment]
Tracking this as an enhancement request to provide a utility function to convert CNContact to OCKContact. 

In terms of incorporating the contacts ui, I would recommend looking at the ContactsUI documentation:
https://developer.apple.com/reference/contactsui

If you choose to pursue that UI, then you can create a bar button item that will launch the contacts UI and from that you can receive the selected contact and use a utility function to convert it to a OCKContact.

**Comment by erik-apple** [comment]
I'm going to close this issue out now that CareKit 2.0 has been released.

CK2.0 has a contact type that can have multiple contact numbers, and we support using the iOS native contact view controllers in addition to the inline views that we provide. There are also many more customization hooks that you can use to perform non-standard control flows.

If you have any specific questions, feel free to re-open this issue or create a new more targeted one.
