### ISSUE TITLE
Scroll forward in Symptom Tracker

### ISSUE THREAD

**Issue by SNagra** [carekit-apple/CareKit#102]
I was wondering if there was a way to allow the user to scroll forward in time in the symptom tracker? I want to allow the user to go forward so that they can look ahead in case there is anything coming up on a future date, in case they need to prepare in some way.

**Comment by ninoguba** [comment]
You have to make the following modifications to OCKSymptomTrackerViewController.m :

Change line 201 to:

`_selectedDate = selectedDate;`

Change line 393 to:

`return controller;`

This will allow the view to scroll forward.
