### ISSUE TITLE
Revisit issue 74 Q1 - attach time to event in activity

### ISSUE THREAD

**Issue by JianWang2016** [carekit-apple/CareKit#111]
Revisit issue 74

I concur with @bishalg that your presentation at WWDC was excellent! Thanks so much for sharing with community CareKit.

I support to attach a time to the event in the activity schedule as petitioned in Q1. For intervention in the care card, time is absolutely necessary. If a scheduled event is not completed within a time window, it should be allowed to expire (optional of cause). Say if someone misses 8am medication, after 2 hours (the window to complete the event), he can simply wait until next scheduled event. The window of time can be adjusted according to the nature of the activity. For assessment, a window of time in addition to a specific time is also much needed.

Again, thanks for considering this proposal. I hope the closed issue is still monitored.

**Comment by tktsubota** [comment]
Link: #74

**Comment by srinathtm-apple** [comment]
Please checkout OCKSchedule in CareKit 2.0
