### ISSUE TITLE
OCKSymptomTrackerViewController layout issues in iOS 10

### ISSUE THREAD

**Issue by rickydamelio** [carekit-apple/CareKit#114]
It appears that there is a problem with the layout for scale format questions. This was working fine on iOS 9, but building for iOS 10/Xcode 8 produces the attached result.

I have also tried updating the CareKit source using the latest commit available (b0fc0f7adb135ec1150995304bc578c1f752df6d)

![simulator screen shot 19 sep 2016 9 07 44 am](https://cloud.githubusercontent.com/assets/5070045/18619804/e56295b4-7e48-11e6-97b4-fc78d6fc5b69.png)

**Comment by ninoguba** [comment]
Reported this issue on the ResearchKit project:

https://github.com/ResearchKit/ResearchKit/issues/824

**Comment by umerkhan-apple** [comment]
Fixed in the latest master 👍
