### ISSUE TITLE
multiple care plan using care kit

### ISSUE THREAD

**Issue by noureenwajeeh** [carekit-apple/CareKit#116]
I want to use carekit in one of the project. Is there any way that I can make multiple care cards using carekit. At the moment the carekit letting me make only one care card and i can add and delete activities on it . At the moment all the activities that I am adding are showing on the same care plan. I want to show different activities in different care plan. E.g. I may have two separate problems like back pain and smoking . And I want to design two care plans to track my progress on two separate things.

**Comment by tktsubota** [comment]
You could instantiate two care plan stores and pass them into two separate care cards.

**Comment by noureenwajeeh** [comment]
It doesn't make any difference if i use one careplan store or two instances. The underlaying database is same which is used to store the activities. It show me mix activities for both care plan. I am attaching code that i am using to create two careplans but its showing the mix activities on both care plans.
I have a careplan manager as ;
import Foundation
import CareKit

class CarePlanManager:NSObject
{
   //var sharedStore = CarePlanManager()
    
    let store : OCKCarePlanStore
    override init ()
    {
        // Determine the file URL for the store.
        let searchPaths = NSSearchPathForDirectoriesInDomains(.ApplicationSupportDirectory, .UserDomainMask, true)
        let applicationSupportPath = searchPaths[0]
        let persistenceDirectoryURL = NSURL(fileURLWithPath: applicationSupportPath)
        
        if !NSFileManager.defaultManager().fileExistsAtPath(persistenceDirectoryURL.absoluteString, isDirectory: nil) {
            try! NSFileManager.defaultManager().createDirectoryAtURL(persistenceDirectoryURL, withIntermediateDirectories: true, attributes: nil)
        }
        
        
        // Create the store.
        store = OCKCarePlanStore(persistenceDirectoryURL: persistenceDirectoryURL)
        
    }
}

and then a view controller with two buttons(careplan1 and careplan2) on it.
import UIKit
import CareKit
class ViewController: UIViewController {

   
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }
    
    @IBAction func careplan2Click(sender: AnyObject) {
 
        let startDate = NSDateComponents(year:2016 , month: 09 , day:14)
        let schedule = OCKCareSchedule.weeklyScheduleWithStartDate(startDate, occurrencesOnEachDay: [2,0,3,0,4,0,5])
        // create an intervention activity .
        let algaselActivity = OCKCarePlanActivity.interventionWithIdentifier("medication2", groupIdentifier: "painmedication", title: "Algasel", text: "200mg", tintColor: UIColor.blueColor(), instructions: "Take medication with food", imageURL: nil, schedule: schedule, userInfo: nil)
        
        let carePlanManager = CarePlanManager()
        carePlanManager.store.removeActivity(algaselActivity, completion:                                                       {success , error in
            print (error)})
//
    
        carePlanManager.store.addActivity(algaselActivity,completion:
                {success , error in
                    print (error)
            })
        
        let viewController = OCKCareCardViewController(carePlanStore: carePlanManager.store)
        self.navigationController?.pushViewController(viewController, animated: true)
    }
    
    @IBAction func careplan1Click(sender: AnyObject) {
        let startDate = NSDateComponents(year:2016 , month: 09 , day:14)
        let schedule = OCKCareSchedule.weeklyScheduleWithStartDate(startDate, occurrencesOnEachDay: [0,4,0,2,0,4,0])
        // create an intervention activity .
        let ibrufenActivity = OCKCarePlanActivity.interventionWithIdentifier("medication1", groupIdentifier: "painmedication", title: "Ibuprofen", text: "200mg", tintColor: UIColor.blueColor(), instructions: "Take medication with food", imageURL: nil, schedule: schedule, userInfo: nil)
        
        let carePlanManager = CarePlanManager()
        
        carePlanManager.store.removeActivity(ibrufenActivity, completion:                                                       {success , error in
            print (error)
        })

        carePlanManager.store.addActivity(ibrufenActivity,completion:
                                                      {success , error in
                                                        print (error)
        })
        
        let viewController = OCKCareCardViewController(carePlanStore: carePlanManager.store)
        self.navigationController?.pushViewController(viewController, animated: true)
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}

@tktsubota is that what you meant by two separate instances?

**Comment by tktsubota** [comment]
You can use two separate care plan stores:

```
let backPainStore = OCKCarePlanStore(persistenceDirectoryURL: backPainURL)
let backPainCareCard = OCKCareCardViewController(carePlanStore: backPainStore)

let smokingStore = OCKCarePlanStore(persistenceDirectoryURL: smokingURL)
let smokingCareCard = OCKCareCardViewController(carePlanStore: smokingStore)
```

**Comment by noureenwajeeh** [comment]
@tktsubota do you think that its a good approach. Suppose if i have an number of care plans , will i be creating the n number of stores?

**Comment by ninoguba** [comment]
@tktsubota is right. If your use case needs multiple separate care plans then you'll need to create multiple care plan stores.
