### ISSUE TITLE
Show activities with value on OCKCareCardViewController

### ISSUE THREAD

**Issue by noureenwajeeh** [carekit-apple/CareKit#119]
Hi All,
I am using carekit in one of my project. Attached is the screen shot from an existing application in which intervention and assessment activities shown on care card. While if i just follow the online examples, I can see the intervention activity on care card and assessment activities on symptoms tracker.
I wonder is there any way that i can achieve the same behaviour as attached i.e. click on the events circle for medication and take the input for blood pressure? I know i can use the delegate methods to take the blood pressure input, but the problem is to display on the care card with input because by default it just shows me the dot as it shows for medication activity. 
<img width="520" alt="screen shot 2016-09-27 at 14 32 11" src="https://cloud.githubusercontent.com/assets/13658716/18875705/c9b62d86-84be-11e6-93b2-26e9b6d002e9.png">
And also is this swipe left delete functionality a part of framework? I am using Cocoa pod 1.0.2 but i can't see any delegate method to get this stop activity functionality
![screen shot 2016-09-27 at 14 16 44](https://cloud.githubusercontent.com/assets/13658716/18875192/9942a564-84bc-11e6-9ed2-82f75a52ca0e.png)

Any suggestion would be highly appreciated.

**Comment by noureenwajeeh** [comment]
I found a way to implement the Delete option using swift. Just extend the OCKCareCardViewController in swift and implement the following,

func tableView(tableView: UITableView, editingStyleForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCellEditingStyle {
        return .Delete
    }
    
    func tableView(tableView: UITableView, canEditRowAtIndexPath indexPath: NSIndexPath) -> Bool
    {
        return true
    }
    
and the delete option will start appearing.
Similarly if I implement the cellforRowAtIndex method so I can have custom cells as well.

**Comment by umerkhan-apple** [comment]
You can create your own custom view controller that adopts a lot of the code from the Care Card View Controller. However, in your implementation of the table view delegate and data source, you can provide both the Care Card and Symptom Tracker Cells. 

Also when querying the care plan store, you can run 2 queries, for assessments and interventions each, and then consolidate the returned events.
