### ISSUE TITLE
CloudKit as cloud provider?

### ISSUE THREAD

**Issue by vinced45** [carekit-apple/CareKit#121]
Are there any reasons not to use CloudKit as a cloud provider? With iOS 10 you could share your private container with your physician and family.

**Comment by amelnychuck** [comment]
It would be great CloudKit could be used in the future, but currently CloudKit is not a HIPAA compliant cloud storage solution—I'd suggest looking into [AWS](https://aws.amazon.com/compliance/hipaa-compliance/) as a backend, or another provider depending on your specific needs.

The main evidence for this is found in the [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/), 5.1.3 item ii.

> Apps must not write false or inaccurate data into HealthKit or any other medical research or health management apps, and may not store personal health information in iCloud.

Hope this helps answer your question!
