### ISSUE TITLE
View Care Card event in the future

### ISSUE THREAD

**Issue by JianWang2016** [carekit-apple/CareKit#124]
Hi, the following paragraph is from the Care Card documentation, it doesn't support view or edit events in the future.  Even though it appears sensible not to allow editing a future event, it is reasonable to let users to see upcoming events and schedules. 
# 

Ideally, users should fill out the Care Card as they perform the events; however, they can also go back and edit previous days. Users can navigate to different days by tapping and swiping the hearts along the top of the screen. They cannot view or edit days in the future.

**Comment by ninoguba** [comment]
See my response to #102
