### ISSUE TITLE
How to handle non-scheduled medications?

### ISSUE THREAD

**Issue by dillan** [carekit-apple/CareKit#129]
The documentation states the following about `OCKCarePlanActivity`

> Intervention activities also require valid schedule, title, text, and detailedText parameters.

With the schedule required, I'm wondering how to best handle non-scheduled medications. For example, taking an insulin injection may only be needed if the person has tested their blood glucose and discovered it was too high.

**Comment by dillan** [comment]
Following up on this question with a feature suggestion. It would be helpful if user were able to be asked how much of a given medication they've taken. For example they may adjust the amount of insulin they are taking based on the results of a blood glucose test.

**Comment by pthealthtech** [comment]
This functionality is a priority for us as well.

**Comment by ninoguba** [comment]
Here's a suggestion for the first question:

In your Symptom Tracker, have a daily assessment activity to test their blood glucose.   Whenever the user completes this activity, check the result and if its too high, you then add an intervention activity for them to take their insulin.  For this new intervention activity you can set the schedule to appear for that day only or whatever is appropriate.

For the second question:

Similar to the first but instead of adding a new intervention activity, you'll need to "update" the dosage and occurrence when appropriate.

**Comment by umerkhan-apple** [comment]
Tracking this an enhancement request for being able to add activities that are not pre-determined or pre-scheduled.

**Comment by tktsubota** [comment]
Non-scheduled medications are now a feature as optional activities in CareKit 1.2.

**Comment by ninoguba** [comment]
Non-scheduled activities are more adhoc or as needed depending on some trigger or threshold.

The optional activity feature in CK 1.2 is a nice addition but still may not address the non-scheduled use cases.

**Comment by erik-apple** [comment]
We're going to go ahead and close this issue. CareKit 2.0 now provides a lot more options both in terms of scheduling and in terms of inserting non-scheduled content into the care contents view controller.

We recommend looking at the sample app provided as part of the repository. In the `CareViewController` file, you can see that the care contents are chosen by querying the store for tasks on a given date. To insert non-schedule content, you would simply perform your custom logic to determine if extra content should be shown or not, and if the check passes, you would create one more card view controller and append it to the content list.

There is even a simple example included in the code. The tip view is conditional, non-schedule content, that is shown only when the user has selected the current date.
https://github.com/carekit-apple/CareKit/blob/9787300cb65cb00322fdf5f4e939e52a3e6f2671/OCKSample/OCKSample/CareViewController.swift#L80-L87
