### ISSUE TITLE
Adding video to OCKCarePLanActivity

### ISSUE THREAD

**Issue by Dynami27** [carekit-apple/CareKit#131]
Any ideas how to add video to Carekit?  How would I display a video on the instructions portion of care card. There is an option to add a photo through imageURL using the OCKCarePlanActivity Class but not video. I also tried extending the OCKCarePlanActivity Class, but was not successful. Thank you!!

**Comment by ninoguba** [comment]
You can implement your own view controller that you present in this delegate method of the OCKCareCardViewController:

http://carekit.org/docs/Protocols/OCKCareCardViewControllerDelegate.html#//api/name/careCardViewController:didSelectRowWithInterventionActivity:

**Comment by Dynami27** [comment]
Where would I implement the video portion if I have video in main bundle. Sorry new iOS dev here. thanks!

**Comment by umerkhan-apple** [comment]
@Dynami27 You can present your own detail view controller for the activity in which you can use AVFoundation to play the video. When creating the activity, you can specify the videoURL in the userInfo dictionary for that activity.
