### ISSUE TITLE
Assessment from research kit does not update. 

### ISSUE THREAD

**Issue by Dynami27** [carekit-apple/CareKit#132]
Hello I am using an active task called short walk task from research kit into my carekit app. I am able to see and start the assessment from the symptomViewController, However, symptomViewController does not update and does not collect data from the assessment. Any ideas about how I can get the assessment to display and collect data provided by user? Thanks!

**Comment by ninoguba** [comment]
You need to implement the following method:

http://researchkit.org/docs/Protocols/ORKTaskViewControllerDelegate.html#//api/name/taskViewController:didFinishWithReason:error:

Check out how it is done on OCKSample.
