### ISSUE TITLE
Latest Release Not Available on CocoaPods

### ISSUE THREAD

**Issue by apbendi** [carekit-apple/CareKit#133]
Would be great to have the latest release available in the CocoaPods registry. Thanks!! :)

**Comment by UberJason** [comment]
+1. The latest release appears to be 1.1.1 (although I saw a blog post about 1.2 just yesterday), but the latest version in the Cocoapods master repo is 1.0.2. Can the repo owner do a quick `pod repo push` to get the latest into Cocoapods?

**Comment by tktsubota** [comment]
1.2 won't be out for a few weeks to iron out bugs and add any small little changes before it gets merged into *stable*. When it does, the CocoaPod release should be updated.

**Comment by UberJason** [comment]
Makes sense - how about 1.1.1? Would be great to get that in Cocoapods since it's been out for a while. :)

**Comment by UberJason** [comment]
@akshay-yadav-apple I saw the latest release of 1.2 today, but Cocoapods is still only installing 1.0.2. Any chance you can quickly do a `pod repo push` so 1.2 is available in Cocoapods for install? Thank you!

**Comment by akshay-yadav-apple** [comment]
Hey @UberJason, 
Thank you for updating. It is surprising why Cocoapods is still installing 1.0.2
I pushed the latest repo immediately after the release, and was able to install CK1.2 thru pod. I'll check again and see whats wrong. Meanwhile, please try again and let me know if the problem persists.

Thank you

**Comment by UberJason** [comment]
@akshay-yadav-apple My fault - I didn't do a `pod repo update` before trying to install CareKit 1.2. All is well now, thanks!

**Comment by akshay-yadav-apple** [comment]
@UberJason,
Awesome! Good to know.

@apbendi, @tktsubota, @UberJason, is it now Okay to close the issue?

**Comment by UberJason** [comment]
Okay by me, thank you!
