### ISSUE TITLE
QueryActivityEventsOperation seems out of date

### ISSUE THREAD

**Issue by BillNattaner** [carekit-apple/CareKit#134]
The Sample app includes the class QueryActivityEventsOperation in which the following comment occurs:

`// <rdar://problem/25528295> [CK] OCKCarePlanStore query methods crash if not called on the main thread`

I've asked on StackOverflow if this is still true, see: "[Can OCKCarePlanStore queries in Apple's CareKit be run off the main queue?](http://stackoverflow.com/questions/41431853/can-ockcareplanstore-queries-in-apples-carekit-be-run-off-the-main-queue/41436884)". The response was that the only method that has to be run on the main queue is "initWithPersistenceDirectoryURL:".  

The comment mentioned above has become misleading. It confused me, and it is starting to spread through the literature on CareKit (see this [tutorial](https://www.raywenderlich.com/136496/carekit-tutorial-for-ios-part-2)). Can the comment be replaced to indicate that the code presents a work-around for a problem that no longer exists?

**Comment by umerkhan-apple** [comment]
@BillNattaner I agree. We can either proceed with rephrasing the comment or refactoring the code. Let me know if you can create a PR with the changes.

**Comment by moppymopperson** [comment]
@umerkhan-apple I wondered about this too. I'll update the code in our app and submit the changes as a PR if there aren't any problems.
