### ISSUE TITLE
Documentation links and carekit.org don't work

### ISSUE THREAD

**Issue by alistra** [carekit-apple/CareKit#138]
https://www.apple.com/carekit/docs/docs/overview/overview.html

https://www.apple.com/carekit/docs/index.html

http://carekit.org/docs/

**Comment by umerkhan-apple** [comment]
carekit.org is back up and running! 👍

**Comment by alistra** [comment]
Nope. I still can't access it. It looks like it is location locked? I asked people at work and some see the page and some don't. Depending on the wireless carrier. I believe I can't see it on my polish ISP, but I can through a swiss vpn. There must be a CDN issue.

**Comment by tktsubota** [comment]
Still not working for me.

**Comment by umerkhan-apple** [comment]
Investigating the issue

**Comment by umerkhan-apple** [comment]
Updated and fixed! 👍

**Comment by alistra** [comment]
I confirm that the links in readme & carekit.org work for me.
