### ISSUE TITLE
Pull to refresh on assessments screen

### ISSUE THREAD

**Issue by majidsaleem105** [carekit-apple/CareKit#139]
I implemented pull to refresh feature on activities screen which works perfectly fine as expected. But when I implement same feature on assessments it doesn't work as expected. I wrote pull to refresh code in viewDidAppear function but It behaves like:

1. It doesn't apply on first visit. I have to take following 2 extra steps:
 a. I have to go into any activity's detail screen 
 b. then back to activity screen
 c. then go to assessments screen and pull to refresh appears this time.

2. It doesn't load new changes on assessments screen. I am calling an API to fetch new changes in pull refresh function, it fetches and updates CarePlanStoreManager store with new changes successfully but new changes do not appear on assessment screen.

**Comment by umerkhan-apple** [comment]
@majidsaleem105 Could you provide a link to your repo?
