### ISSUE TITLE
OCKDocument create PDF in iOS 10 generates replacing +/-infinity error

### ISSUE THREAD

**Issue by djknowles** [carekit-apple/CareKit#140]
When creating a PDF document  from an OCKDocument the console displays an error:

<Error>: replacing +/-infinity with -2147483648.

I believe this only occurs in iOS 10.

This appears to be relatively harmless (I have not seen any particular rendering issues on the generated PDF).

For the generation of my document this error appears 4 times (in two sets of two):

Jan 20 15:55:56  Diabetes[17260] <Error>: replacing +/-infinity with -2147483648.
Jan 20 15:55:56  Diabetes[17260] <Error>: replacing +/-infinity with 2147483647.
Jan 20 15:59:23  Diabetes[17260] <Error>: replacing +/-infinity with -2147483648.
Jan 20 15:59:23  Diabetes[17260] <Error>: replacing +/-infinity with 2147483647.

I have stepped through the code and the issue appears to occur in the file/function:

OCKHTMLPDFWriter.savePDF

The error occurs on the lines:

    for (NSInteger i = 0; i < pages; i++) {
        UIGraphicsBeginPDFPage();
        [renderer drawPageAtIndex:i inRect:renderer.printableRect];
    }

and happens when the UIGraphicsBeginPDFPage is invoked for the second time. From my reading of the documentation this implies that the error occurs when the function is ending the first page. On a multi-page document the error occurs on only the second iteration of the function.

I have created several different documents but the error occurs on them all.

**Comment by umerkhan-apple** [comment]
@djknowles Would you be able to provide a sample project with this issue isolated?

**Comment by djknowles** [comment]
The issue appears to have vanished in 10.3.

Generating a PDF from OCKDocument no longer generates the infinity message.

**Comment by djknowles** [comment]
The issue does occur in 10.2.1. Do you still wish me to create a project or close the issue?

**Comment by kelseydedoshka-apple** [comment]
@djknowles - closing as you mention this has been resolved.
