### ISSUE TITLE
CareKit-issue while updating Symptom tracker and viewing insights 

### ISSUE THREAD

**Issue by sgollahallichowda** [carekit-apple/CareKit#145]
Whenever user updated his CarePlanstore data and his activities it does not trigger the Delegate to inform insights , 

Any suggestion on this very much appreciated !

// The aggregate operation is dependent on the query operations.
		aggregateDataOperation.addDependency(meEventsOperation)
		aggregateDataOperation.addDependency(outdoorWalkEventsOperation)
		aggregateDataOperation.addDependency(moodEventsOperation)
		buildInsightsOperation.addDependency(aggregateDataOperation)
		
		// Add all the operations to the operation queue.
		updateOperationQueue.addOperations([
			meEventsOperation,
			outdoorWalkEventsOperation,
			moodEventsOperation,
			aggregateDataOperation,
			buildInsightsOperation
			], waitUntilFinished: false)

**Comment by ninoguba** [comment]
OCKSample is a good example showing how this works.   Look specifically at the CarePlanStoreManager.swift for its delegates.

**Comment by akshay-yadav-apple** [comment]
@sgollahallichowda 
Can you provide complete insights builder code, where you're creating the EventsOperations?

**Comment by umerkhan-apple** [comment]
@sgollahallichowda If you look at the Insights Builder inside the OCKSample app as @ninoguba  suggested, you should be able to find sample code that address your issue.
