### ISSUE TITLE
How to include image files in CareKit or ResearchKit

### ISSUE THREAD

**Issue by 84Park** [carekit-apple/CareKit#146]
I have found references to having the ability to add photo images, PDF, or other file types within CareKit/ResearchKit, but I have not been successful in finding any code examples. I wish to add photos, either from the camera or from the Camera Roll, into the app data store, and to be able to retrieve those images as part of the health record by date. Does that capability exist and if so, is example code available? Thanks in advance.

**Comment by ninoguba** [comment]
This should help:

https://developer.apple.com/library/content/samplecode/PhotoPicker/Introduction/Intro.html
