### ISSUE TITLE
Initializer for OCKCareSchedule(startDate: , endDate: , occurrences: , timeUnitsToSkip: ) creates corrupt data

### ISSUE THREAD

**Issue by moppymopperson** [carekit-apple/CareKit#147]
I spent awhile debugging and eventually pinned down that using this initializer for a schedule and then saving the activity to the store corrupts the store and requires resetting the simulator or emptying the store to get back to a working state.

I eventually found the other initializers that do work as expected, but it'd probably be worth marking this particular initializer private to prevent people from using it wrong like I did.

**Comment by umerkhan-apple** [comment]
Good catch! Our team will take a look at the issue.

**Comment by srinathtm-apple** [comment]
Closing this out as it's no longer applicable due to the CareKit 2.0 beta update.
