### ISSUE TITLE
Question about Symptom Tracking Occurence

### ISSUE THREAD

**Issue by Drelos** [carekit-apple/CareKit#148]
Hi all,

I am very new to CareKit. While searching it for a project that I have in mind I read in the documentation regarding the number of occurrences of a symptom tracked and how to do it. Is there a way to add a symptom tracking activity whenever a user asks for it. E.g. to track down whenever the user feels nausea repeatedly. This can happen many times a day this can happens not at all. I found in a book something about subclassung OCKCareShedule (but cannot be done in Swift). Can you please provide me with more information on whether this can be done. Thank you in advance.

**Comment by umerkhan-apple** [comment]
@Drelos You can definitely add new activities to the Care Plan as the user completes them. However, the symptom tracker and care card UI are used to track progress and completion, so it will not make sense to employ of those UI view controllers to display the data.

I would recommend creating a new custom view controller in which you can provide a `+` button. With that button, the user can add a care plan activity, and then you can query the care plan store to display the added events in your new custom view controller.

You shouldn't have to subclass the schedule object.

**Comment by Drelos** [comment]
@umerkhan-apple Great, I got the point. Thank you for the response.
