### ISSUE TITLE
No such module ResearchKit

### ISSUE THREAD

**Issue by ksoftllc** [carekit-apple/CareKit#15]
When I try to build the sample app, I get the error "no such module ResearchKit" in the HealthSampleBuilder.swift source file.

**Comment by YuanZhu-apple** [comment]
Did you use this command to clone?

```
git clone --recurse-submodules https://github.com/carekit-apple/carekit.git
```

**Comment by ksoftllc** [comment]
No, I simply downloaded the zip file. I have resolved the issue by downloading the ResearchKit as well and adding it to the workspace. It is now building.
