### ISSUE TITLE
Update ResearchKit dependency for Xcode 8.3

### ISSUE THREAD

**Issue by xmlmodeling** [carekit-apple/CareKit#156]
ResearchKit has been updated to fix compilation issues with Xcode 8.3.  Please update this dependency in CareKit.

**Comment by koralcem** [comment]
I see this issue is pretty old. As of this writing Xcode 9 is out, and I can build the OCKSample app with all of its dependencies (including ResearchKit and CareKit) without any issues.

@xmlmodeling Is this issue still applicable?

**Comment by akshay-yadav-apple** [comment]
Thanks @koralcem,
@xmlmodeling Closing the issue. Please feel free to reopen if the issue persists for you.
