### ISSUE TITLE
OCKSymptomTrackerViewController table cell dynamic height not working

### ISSUE THREAD

**Issue by vallamk** [carekit-apple/CareKit#157]
Hi,

I am working on a app that uses care kit. We are leveraging all the features of care kit which includes some activities and symptoms. The issue i am seeing is when we have long text that needs to be displayed as part of the textLabel in OCKSymptomTrackerViewController table view cell, it is showing eclipses. Cell hight is not growing with respect to the text length.

I went ahead and debugged through care kit code and found that everything has been implemented to support Self Sizing Cells in tableview but the textLabel that is used in OCKSymptomTrackerTableViewCell does not have proper properties. When i add _textLabel.numberOfLines = 0;
 _textLabel.lineBreakMode = NSLineBreakByWordWrapping;
these two lines of code in prepareView method of OCKSymptomTrackerTableViewCell, it is working as expected.

Is my understanding right, do we need to add this to careKit API ?

And also i want to customize the font size for this cell elements. Should i be doing that to careKit API or is there a way i could send the custom attributes?

Any help is greatly appreciated.

**Comment by ninoguba** [comment]
I did similar customizations and had done it by modifying the CareKit source directly.

**Comment by vallamk** [comment]
Thankyou Ninoguba for the response, i did modify CareKit source code and it is working great now. But going forward when i update new version of CareKit, i will have to go in and add these changes again, so i am wondering if it is good to add it to be part of the source by doing a pull request?
Any ideas?

**Comment by ninoguba** [comment]
Yes there is always that risk but as long as your changes doesnt have conflicts then it would be ok.  I think someone already added new delegate methods that let you customize the look of the CareCard and Symptom Tracker further.  Perhaps you can take a look how they implemented that and extend it to allow cell customizations the "ideal" way.

**Comment by akshay-yadav-apple** [comment]
@vallamk We have fixed this issue. Please confirm if it is okay to close the issue.

**Comment by akshay-yadav-apple** [comment]
@vallamk We have fixed this issue and are now closing it. Feel free to reopen if the fix does not work for your use case, or for any further discussion.
