### ISSUE TITLE
No Such Module ResearchKit

### ISSUE THREAD

**Issue by arishanapalli** [carekit-apple/CareKit#158]
Hi
Team,

I downloaded CareKit and try to run the sample application from the provided github, when running an sample application I got the error No Such Module ResearchKit.

Do I need to integrate ResearchKit framework into application.  Or the framework is missed from the sample project?

Your feedback is highly appreciated.

Please find the error Message image for understand more in detail.
Thank You.
<img width="1364" alt="errorimage" src="https://cloud.githubusercontent.com/assets/3903433/24947527/d41890f0-1f84-11e7-8ae1-105a24ba8ea0.png">

**Comment by tktsubota** [comment]
You have to go into Terminal and clone it from there to retrieve the submodules:

`git clone -b stable --recurse-submodules https://github.com/carekit-apple/carekit.git`

**Comment by arishanapalli** [comment]
Only OCKTest is able to run the application! OCKSample is giving error.

**Comment by koralcem** [comment]
@arishanapalli The sample application makes use of ResearchKit, hence it's hooked up as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) in the CareKit repo. As tktsubota mentions above, when you clone you also need to grab the submodules. The `--recurse-submodules` part of that command is important. Have tried running again after cloning with that command?

**Comment by srinathtm-apple** [comment]
Closing out issues that are no longer relevant due to the CareKit 2.0 beta update.
