### ISSUE TITLE
OCKCareCardViewController rendering errors with 7 events followed by 5

### ISSUE THREAD

**Issue by djknowles** [carekit-apple/CareKit#162]
If there are two activities where one generates 7 daily events and is directly followed by an activity containing 5 events the rendering of the event circles fails with the circles overlapping the table cell on the next line.
This occurs in iOS 10 and 9.

See attached image.
![screen shot 2017-05-23 at 4 21 22 pm](https://cloud.githubusercontent.com/assets/15701701/26338515/c18dc07a-3fd4-11e7-9fa5-06dc84926512.png)
![screen shot 2017-05-23 at 4 21 48 pm](https://cloud.githubusercontent.com/assets/15701701/26338516/c1d1dbf2-3fd4-11e7-8345-5fbf3285dfd2.png)

**Comment by rats083** [comment]
@djknowles  I have tried it from carekit sample and its working fine for me for any no of circle for iOS 9.3. Please use carekit sample for this and it should working fine.

![simulator screen shot may 29 2017 4 18 14 pm](https://cloud.githubusercontent.com/assets/6559961/26547613/79168274-448d-11e7-9571-4b15b8c4f2c9.png)
![simulator screen shot may 29 2017 4 38 29 pm](https://cloud.githubusercontent.com/assets/6559961/26547614/7919c6dc-448d-11e7-96a7-ad88e2576f18.png)

**Comment by djknowles** [comment]
Just downloaded the latest version of CareKit which appears different in the example applications. I am using the Pod version which is 1.0.2. Doing a diff between the two source trees indicates a number of differences.
It appears that the issue has been addressed in the latest version of the source however there has been no update to the pod files and hence the issue exists there.

**Comment by rats083** [comment]
okay. :)

**Comment by djknowles** [comment]
Fixed in version 1.2.0 of CareKit.
