### ISSUE TITLE
How to update OCKCarePlanStore store without interact on CardView. 

### ISSUE THREAD

**Issue by rats083** [carekit-apple/CareKit#163]
I added carekit into my application and added few activity on Card View and home view. I want to update data on carekit store and card screen when I change any data on my home view controller.

**Comment by ninoguba** [comment]
You can do that by creating an instance of the OCKCarePlanEventResult and attach it to a OCKCarePlanEvent on the OCKCarePlanStore.

http://carekit.org/docs/Classes/OCKCarePlanEventResult.html
