### ISSUE TITLE
OCKCarePlanStore - Bug in evaluation of adherence thresholds

### ISSUE THREAD

**Issue by mirlhaq** [carekit-apple/CareKit#167]
Fix for adherence thresholds - The value to evaluate the threshold should be "completed events"  divided by the "total amount of events".

`OCKCarePlanStore @ evaluateAdheranceThresholdForActivity:date:completion:`

**Comment by kelseydedoshka-apple** [comment]
@mirlhaq - thanks for pointing this out! Will close this out when we get your PR merged it.

**Comment by mirlhaq** [comment]
@kelseydedoshka-apple you are very welcome! :)

**Comment by teldridge11** [comment]
@kelseydedoshka-apple Looks like this issue can be closed - PR was merged

**Comment by kelseydedoshka-apple** [comment]
@teldridge11 - great, closing out.
