### ISSUE TITLE
OCKCareContentsViewController uses groupIdentifier to determine tableView sections - unclear documentation

### ISSUE THREAD

**Issue by UberJason** [carekit-apple/CareKit#170]
I noticed that `OCKCareContentsViewController` is using the `groupIdentifier` of `OCKCarePlanActivity` to determine visual groupings of different activities in the Care Contents view (tableView sections). However, the documentation for `groupIdentifier` implies that its purpose is more for internal organization and querying purposes:

> Group identifier string. You can use the identifier to group similar activities. You can use this identifier as a key to retrieve multiple activity instances from the store.

And indeed, `OCKCarePlanStore` has a method `activitiesWithGroupIdentifier:completion:`.

Furthermore, if an activity is `optional`, then its `groupIdentifier` is ignored for visual organization, and it is instead placed in the "Optional" tableView section. So the usage of `groupIdentifier` in determining visual groupings is somewhat inconsistent.

I think there would be value in having a different property on `OCKCarePlanActivity` for visual groupings of activities in the Care Contents view that doesn't clash with `groupIdentifier`. For example, I could imagine wanting to group activities by the provider who assigned them using `groupIdentifier`, while still visually separating the activities in the Care Contents view by, for example, their activity types (e.g. Physical Exercises vs. Medications).

**Comment by ninoguba** [comment]
+1

**Comment by ninoguba** [comment]
Are the section labels "Optional" and "Read-Only" fixed?  Would it be valuable as well to be able to define a custom text for them too?

**Comment by UberJason** [comment]
There appear to already be properties on `OCKCareContentsViewController` to set custom titles for the Optional and Read-Only sections:

````/**
 The section header title for all the Optional activities. Default is `Optional` if nil.
 */
@property (nonatomic, nullable) NSString *optionalSectionHeader;

/**
 The section header title for all the ReadOnly activities. Default is `Read Only` if nil.
 */
@property (nonatomic, nullable) NSString *readOnlySectionHeader;
````

**Comment by kelseydedoshka-apple** [comment]
@ninoguba - as @UberJason has mentioned, there are properties on the OCKCareContentsViewController to set custom titles for those section headers. 

@UberJason - thanks for brining this point up, as it was something we had a lot of discussion around on our side as well, so we really value input on this from the community! For the reasons you mentioned above implementing a secondary visualIdentifier field could be an interesting addition however we used the groupIdentifier field as we think it is intuitive for activities that are in the same group to display together. Your point with the optional values is absolutely valid and we will update the documentation on this. The reason we still use the groupIdentifier field in this case is in the mentioned documentation in the case you want to group it with other activities for querying purposes. I think it would be great to continue the discussion on this!

**Comment by UberJason** [comment]
@kelseydedoshka-apple Thanks for the reply! I understand the reasoning a little better now.

Although I do understand that it may be a common case to visually group activities that are also grouped in the data layer, I would push back a little bit about this being an "intuitive" approach. As a developer, the `groupIdentifier` field was entirely intuitive to me as a querying mechanism and method of organizing activities in the _data_ layer, but it was not intuitive that it would end up being a section and display title in the UI. I actually initially chose a groupIdentifier that was in camelCase (something like "exerciseActivities") and had to change it once I saw the UI. 

In general, I don't love the idea that a single property would be used for both underlying data organization AND appearance in the presentation layer. It's less flexible and more tightly couples data and visual organization. That tying together should be more explicit. It doesn't have to be implemented the way I did it. I could imagine a solution where `groupIdentifier` is used for visual groupings if `visualGroupIdentifier` is nil, or a flag like `usesGroupIdentifierForVisualGroupings` to make the coupling of data and visual organization explicit.

I'm a big fan of CareKit and hope your team is still opening to reconsidering this approach. I'd also love to hear if anyone else out there has a perspective on this - perhaps @ninoguba?

**Comment by ninoguba** [comment]
I agree with most points @UberJason already mentioned, specifically the separation of the use of groupIdentifier to group the activities in the care plan while having another property that allows flexibility in presenting activities on the Care Contents view.

Also since the section header for the Optional and Read-Only activities can be custom-set, to me it makes it more consistent that the other activities can also be grouped by custom section headers that is not necessarily grouped the same way in the underlying care plan store.

**Comment by kelseydedoshka-apple** [comment]
@UberJason and @ninoguba - I definitely agree with wanting to keep the consistency of being able to set all of the section headers for the grouped activities, and I really appreciate all of the feedback around this! I am also interested in opening the discussion up to then the relationship between the groupIdentifier property and the proposed visualIdentifier property. Some of the reasoning behind the initial solution came because we are looking to only allow activities to be grouped if they are of the same type to keep UI consistency and clarity. Dropping the functionality of the groupIdentifier to only be used for querying purposes could be done and the visualIdentifier could be the sole property for grouping the activities in the UI, however I have some concern about these two grouping properties to become a little confusing. Thoughts on this?

**Comment by UberJason** [comment]
@kelseydedoshka-apple I appreciate your concerns about the two properties being a little confusing. I think that while the terms "groupIdentifier" and "visualGroupIdentifier" may be a little confusing (and we can rename visualGroupIdentifier/visualIdentifier to something more self-explanatory), the actual concepts are not confusing - one of them is for back-end data management, while one is about UI organization. 

So I think that well-worded documentation would go a long way to explaining the difference:
* Explicitly explain the difference in the code defining the groupIdentifier and visualGroupIdentifier properties.
* Explain with a paragraph or so and show code examples in the [carekit.org docs](http://carekit.org/docs/docs/AccessingCarePlanData/AccessingCarePlanData.html) (which don't appear to have been updated for 1.2 yet, but I assume that'll happen in due time).
* Have a couple of good examples in the sample project, which is already excellent and has so far been my go-to for understanding how the various components of CareKit work!

I also appreciate how your team wants to only allow activities to be grouped if they are of the same type - my thought on this would be that as an open-source project, the framework should only "strongly encourage" this kind of behavior, but not necessarily "strictly require" / "only allow". Carefully worded documentation, analogous to other Apple documentation, would help accomplish this goal. (For example: [HKHealthStore](https://developer.apple.com/documentation/healthkit/hkhealthstore) says, _"Like many classes in HealthKit, the HKHealthStore class should not be subclassed."_) There could also be a boolean flag `usesGroupIdentifierForVisualGroupings` that defaults to `true` to get this encouraged behavior by default, while still allowing that behavior to be overridden if necessary.

**Comment by kelseydedoshka-apple** [comment]
@UberJason - I absolutely agree with your points above. I think the confusion around the identifiers comes with the naming, and determining the proper property names as well as clear documentation  to ensure these changes are well understood.

I agree with your open source comment as well and that is how we generally operate. Any strict guidelines we set in place from our side are just guidelines and we do encourage developers to make changes to modules to fit their desired use case if necessary. I think they key here is really going to be in the property naming/design as you mentioned with potentially a boolean flag as well as clear documentation. 

Documentation will be available shortly for the 1.2 release - stay tuned for that!

**Comment by UberJason** [comment]
@kelseydedoshka-apple Sounds great, looking forward to seeing that 1.2 documentation (and hopefully a Podspec bump for 1.2!). 

I don't know what the process is at Apple for deciding on changes like these with community input, but I hope your team will consider adding this visualGroupIdentifier or some other solution similar to it!

**Comment by kelseydedoshka-apple** [comment]
@UberJason - Podspec bump on it's way as well!

In terms of process we always consider the community discussions when making changes moving forward and we are also happy to look and accept and PRs that look good. If you happen to do some work on the changes discussed here please feel free to submit a PR and we can look into accepting it!

**Comment by UberJason** [comment]
@kelseydedoshka-apple Got it - so it sounds like one concrete path forward would be for me to update my PR #171 to try to incorporate some of these discussed changes? That PR got no direct response, all the conversation has been in this issue thread. But I'm happy to take another stab at it.

**Comment by kelseydedoshka-apple** [comment]
@UberJason - my oversight for not connecting this issue to the PR. Let me take a look at it and maybe you could tackle some of the changes we have discussed here.

**Comment by UberJason** [comment]
@kelseydedoshka-apple Awesome, thank you!

**Comment by erik-apple** [comment]
Closing this out now that CareKit 2.0 has been released.
Developers now have the freedom to layout the care content in any order or they please, so this should no longer be an issue.
