### ISSUE TITLE
[Carthage] Skipped building CareKit due to the error: Dependency "CareKit" has no shared framework schemes

### ISSUE THREAD

**Issue by MacroYau** [carekit-apple/CareKit#172]
It's exciting to learn the new CareKit features in the WWDC talks. Thanks for the team's and every contributor's effort!

However, I encountered the captioned issue when I was trying to integrate the new version into my project. I attempted to pull the latest `master` branch commit via Carthage with the Cartfile line ```github "carekit-apple/CareKit" "master"``` as usual. Any idea to fix this?

**Comment by Pariecemckinney-apple** [comment]
Hello @MacroYau, 

Thank you for pointing out this issue. Have you found a solution for the bug yet? In the meantime we will also investigate the problem.

**Comment by MacroYau** [comment]
@Pariecemckinney-apple Not yet. I will try again in the next few days.

**Comment by MacroYau** [comment]
@Pariecemckinney-apple I found that the bug is caused by [CareKit.xcodeproj/xcshareddata/xcschemes/CareKit.xcscheme](https://github.com/carekit-apple/CareKit/blob/stable/CareKit.xcodeproj/xcshareddata/xcschemes/CareKit.xcscheme), which was present in the stable build, [went missing](https://stackoverflow.com/questions/35054788/carthage-no-shared-framework-schemes-for-ios-platform-for-my-own-framework) in the latest commit.

**Comment by trpmap93** [comment]
@MacroYau  Not a solution to the Carthage issue (as I also experienced the main problem you described)  but using the terminal to clone the git repository works as advertised.  I think its probably best now to start weaning away from Carthage (although I love it) and Cocoa Pods as the Swift Package Manager is becoming more mature.  This looks to be the direction things are going.

**Comment by UberJason** [comment]
@trpmap93 I think that until SPM supports iOS, we can't wean away from Carthage or CocoaPods. I don't think there's been any news on that front yet, has there? So it may still be a while.

**Comment by trpmap93** [comment]
@UberJason You are correct, there has been no official news on that front that I know of, but I am just trying to read the tea leaves.  I have noticed a trend lately with dependencies in that I have been having issues like this more frequently.  I have never had to clone the git repository from terminal until the last couple of months after failing with both Carthage and Cocoapods.  I hate it though because I really love Carthage.

**Comment by MacroYau** [comment]
@trpmap93 I've just tried to clone `master` to a local repo and point the Carthage entry to it. It works for now, thanks!

**Comment by nikwest** [comment]
haven't tried it yet myself, but if you use fastlane there is a plugin which recreates schemes:

recreate_schemes(project: "./path/to/CareKit.xcodeproj")

https://docs.fastlane.tools/actions/#building

**Comment by srinathtm-apple** [comment]
Closing out this issue, we now support SPM...
