### ISSUE TITLE
CareKit Bridge Documentation

### ISSUE THREAD

**Issue by SNagra** [carekit-apple/CareKit#173]
Is there any documentation around how to incorporate CareKit bridge in an existing project to a custom cloud backend? The WWDC session only talked about Medable and did not link to any resources that describe how to build a custom solution.

**Comment by evliu** [comment]
I looked through the source code and it looks like all it is is a delegate function on the carePlanStore that gets called with the same delegate functions as the normal delegate, but there isn't any actual API. At this point, you still need to transform the data yourself, and there's no actual API. I tried looking at CloudMine's SDK for cloud but it doesn't look like they use the `cloudBridgeDelegate`, but rather, just wrap the existing carePlanStore to capture the changes to activities and list.

**Comment by malhal** [comment]
Very weird WWDC talk on this. It would appear that Medable's SDK with the sync feature isn't available yet. If you look closely at 19:33 in the [video](https://developer.apple.com/videos/play/wwdc2017/239/) you can see bridge folders that currently aren't on [Medable's github ](https://github.com/Medable/iOS-SDK).

I would imagine how it works is they listen to the cloudBridgeDelegate methods and then append to an event log adding a timestamp that is persisted to file, so they are cached in case the app quits. And then they would upload the events to the server, probably a few seconds after they are created, or the next time the device gains a network connection, and after launch. Upon receiving data on the server they send the push notifications to other devices and then those download the changes and update the care store. 

Quite a simple sync solution with a few cons. While offline all the data being created is duplicated between the care store and the event log, but once the log is uploaded it would be deleted. While offline if the same activity is updated multiple times, then its possible there are redundant log entries, but a more complex implementation could remove these before the upload takes place so only the latest change is sent.

**Comment by timrsmith** [comment]
Hi, I just wanted to chime in from Medable. Our CloudBridge SDK, which you saw pieces of in the WWDC session, is currently in private beta with a number of our early Synapse customers and will be publicly available very soon.

@malhal you're right that the cloudBridgeDelegate method is what notifies Medable's CloudBridge (MDCKCloudBridge) of local CarePlanStore changes. MDCKCloudBridge takes care of the sync from there. The sync also takes care of a lot behind-the-scenes to ensure consistency and coherence across disparate CarePlanStores. The scenario you outline with duplicate activities is a good example. CK doesn't strictly enforce activity uniqueness within the scope of a CPS, but the CloudBridge does without requiring any changes to how object properties are currently being used within an app.

There are also a number of helper methods to support common use cases, such as creating patients, inviting patients to participate (or care givers, care team members, etc), user registration and authorization, sending secure messages, and more.

It's great to see the discussions happening around the new capabilities in CK1.2. If you are developing or have an existing CareKit app and would like to leverage CloudBridge, you can request access [here](https://www.medable.com/products/synapse). We'd love to chat about what you're working on, discuss the solution in greater detail, and get your feedback!

**Comment by evliu** [comment]
Does anyone know if an actual API will exist? Otherwise, I feel like it's unnecessary for the new `cloudBridgeDelegate` to exist if I could just use the normal delegate to do the same thing. I would expect an API to standardize the json-encoded data and have that passed to the delegate. It's fine either way, was just confused on how it's an API.

**Comment by kelseydedoshka-apple** [comment]
@SNagra - thank you for bringing this up. Documentation regarding the bridge will be available soon!

@evliu - You absolutely could use the existing delegate methods to accomplish this, however the idea was to separate out the cloudBridgeDelegate and isolate the functionality just pertaining to the data syncing so that we can continue to expand and grow this functionality without starting to clog up the existing delegate methods. You are correct at the moment in that the delegate methods we have added aren't really an API, but as Tim mentioned above the API solutions at the moment come from the implementations developed by Medable and CloudMine. Building your own would involve transforming and handling the data yourself. As there are many solutions already out there the goal is to leave it as open and as modular from the get go and we hope to grow this as we have discussions like this surrounding the topic!

**Comment by akac** [comment]
Our interest is in building a solution in our own private AWS cloud. We are looking forward to any documentation you have soon. I've built powerful high end sync systems, both custom and to public APIs for 2 decades but I'm always interested in seeing what makes that job easier.

**Comment by scdi** [comment]
@kelseydedoshka-apple - Could we now have access to the documentation regarding the bridge? SO we have to use the companies that Apple sponsored, only if we want to use the bridge? Are there any tutorials? Is there an equivalent solution that one could use?

**Comment by kelseydedoshka-apple** [comment]
@scdi - you certainly don't have to use the companies we recommend. Medable and CloudMine are great solutions for developers who don't want to build out their own custom solutions. Documentation on how to use either of those solutions are on their respective websites.

You certainly can build out your own custom solution, it will just require significantly more work. You can look at the **cloudBridgeDelegate** for documentation and delegate functions you can tie into to create your own solution. This delegate fires callbacks on events in the care plan store. You will be required to handle all of the data and syncing accordingly once this happens however. Medable and CloudMine handle all of these callbacks and syncing already if you don't want to have to do that on your own.

**Comment by scdi** [comment]
I am embarrassed to say this but I can't find any documentation on Medable about the cloudBridgeDelegate. The only information I see on the Apple Developer website is not to use the cloudBridgeDelegate is the following (http://carekit.org/docs/docs/Overview/Overview.html):
"Connecting App Data with the Bridge API
CareKit provides the bridge API to enable data sharing between a CareKit app’s device storage and backend cloud storage solutions. The bridge API is an abstract cloud API that conforms to the Care Plan Store schema and enables data syncing without requiring additional configuration.

You can use CareKit’s bridge API to create your own hooks to HIPAA-compliant backend storage. The API provides delegate functions that enable cloud bridges to work seamlessly with the CareKit framework. These delegate functions provide the data synching mechanism by triggering for every type of state change in the database.

The bridge API is supported by third-party cloud storage providers, who provide CareKit-compatible solutions. You may be able to find a cloud solution without creating your own."

If you have vetted any information that would seem helpful would mind sending a link
Thank you so much

**Comment by kelseydedoshka-apple** [comment]
@timrsmith - would you mind helping out on this one?

**Comment by timrsmith** [comment]
Thanks @kelseydedoshka-apple! @scdi we do make the sdk, object model, and documentation available as a part of our Synapse product offering. You can request information on that here: https://www.medable.com/products/synapse

**Comment by scdi** [comment]
HI Tim:

I made the request a week ago and got this response:

"*Hi Jude*


Thank you for your reaching out to Medable
<http://www2.medable.com/e/228462/2017-12-09/vhpy/46713776>.  Our products
enable innovators to transform human health through applications and new
data possibilities.

Synapse <http://www2.medable.com/e/228462/products-synapse-/g9ss/46713776>
enables
healthcare providers to easily configure and launch CareKit
<http://www2.medable.com/e/228462/2017-12-09/vhq1/46713776> apps to track
health in real-time. With Synapse, providers can prescribe a treatment plan
to a patient through an app, track and monitor patient treatment
activities, and communicate securely with a patient and the broader care
team.

We are excited to learn more about your disease management application
needs.

Thanks,
Tim Smith"

**Comment by timrsmith** [comment]
@scdi thanks for letting me know. I'll make sure someone reaches back out. Apologies for the delay!

**Comment by scdi** [comment]
Not at all. Any help is welcome

**Comment by scdi** [comment]
I am sorry to start the new year with a negative feel, but to this day I
have not heard back from Medable. If anyone has the documentation could
they send it to me.

**Comment by kelseydedoshka-apple** [comment]
@damianesteban - apologies for the confusion here. In terms of documentation we have left it up to the individual API developers (like Medable and CloudMine) to provide the documentation as it is specific to each respective API.

**Comment by danielmoro** [comment]
This is disappointing, I was expecting a documentation how to BUILD a bridge to custom server with provided client API, not how to USE someone else's cloud solution. I already have a server in a cloud, what I need is explanation how to connect to CareKit...

**Comment by kelseydedoshka-apple** [comment]
@danielmoro - how you connect and handle the CareKit data is entirely up to you. The bridge provides delegate methods when the Care Plan Store changes, how you handle those delegate callbacks and data syncing depends on how you want the data formatted and handle syncing. Apologies for your disappointment, but happy to answer any questions your have on the delegate directly.

**Comment by scdi** [comment]
I agree this is disappointing. Companies were invited to work with Apple to leverage the Bridge. The knowledge or experience gained is passed on a service for a fee.
Is there anyway, since this technology is meant to be open source, for the average developer to benefit from documentation or code samples derived from that work that Apple invested in the companies that met with them?
All we are asking for is help to leverage the bridge. Please get us across.

**Comment by srinathtm-apple** [comment]
Closing this issue as it is no longer relevant due to CareKit 2.0 beta update...
