### ISSUE TITLE
Error compiling CKPrototyper.xcodeproj - TabBarViewController.swift:87:60: Result values in '? :' expression have mismatching types '_' and 'OCKPatient'

### ISSUE THREAD

**Issue by morrismarkw** [carekit-apple/CareKit#174]
The WWDC17 presentation included a demo of the new CareKit prototyping tool ... with the promise that this is a tool for non technical people. 

Well, I gave it a try and got a Swift compiler error. I guess this non technical person needs some technical help! And I thought I would start a thread just in case others like me are experiencing this issue. I'm sure there is a simple fix. 

/CareKit-master/CareKitPrototypingTool/OCKPrototyper/CareKitPatient/TabBarViewController.swift:87:60: Result values in '? :' expression have mismatching types '_' and 'OCKPatient'

**Comment by srinathtm-apple** [comment]
Hey @morrismarkw - thank you so much for bringing this up! So this issue has been fixed in Xcode 8.2 and above. Can you please check which version of Xcode you are currently using ? You can update the Xcode app to the latest version from the Mac app store.

**Comment by morrismarkw** [comment]
Thanks, that worked!
