### ISSUE TITLE
Support for generic OCKInsightItems in OCKInsightsViewController

### ISSUE THREAD

**Issue by UberJason** [carekit-apple/CareKit#181]
Currently the [internal implementation](https://github.com/carekit-apple/CareKit/blob/e9347ecba9635c7889fcdf37ca64afd629960322/CareKit/Insights/OCKInsightsViewController.m#L325-L356) of `OCKInsightsViewController` expects its insight items to be either an `OCKChart`, an `OCKMessageItem`, or an `OCKRingItem`. However, the fact that `OCKInsightItem` itself is a generic insight class intended to be subclassed suggests that there should be the capability to create other custom insight items, and they should be displayable in `OCKInsightsViewController`. 

One fairly simple solution could be to have a generic `OCKInsightsGenericTableViewCell` that simply expects some sort of `insightView` - similar to the way `OCKInsightsChartTableViewCell` simply expects a `chartView()` implementation.

**Comment by kelseydedoshka-apple** [comment]
@UberJason - this is a great suggestion, I think it would be good to get some additional feedback from others on this as well! The suggested implementation would definitely help modularize the insights view for customized content. Let's keep this discussion open as we both look into working through this implementation.

**Comment by ninoguba** [comment]
I think Insight items for the following types of content will be a good addition to the framework:

- Image (OCKImageItem)
- Video (OCKVideoItem)
- Table (OCKTableItem)
- Link (OCKLinkItem) - which loads up a URL on Safari
- Action (OCKActionItem) - which will contain a call-to-action text and button that triggers a custom function/action when tapped

**Comment by erik-apple** [comment]
CareKit 2.0 now makes adding content much easier. The 2019 WWDC session includes a walkthrough of the new APIs and demonstrates how to add arbitrary content into care contents page.

https://developer.apple.com/videos/play/wwdc2019/217/
