### ISSUE TITLE
headerTitle not working on CK 1.2

### ISSUE THREAD

**Issue by ninoguba** [carekit-apple/CareKit#182]
The headerTitle property added to the Care Card and Symptom Tracker views on PR #141  doesnt work anymore in the latest version of CareKit (1.2)

**Comment by kelseydedoshka-apple** [comment]
@ninoguba - thanks for pointing this out. Just to clarify - is this no longer working for the existing Care Card and Symptom Tracker views, or this is feature not accessible via the new Care Contents view?

**Comment by ninoguba** [comment]
@kelseydedoshka-apple not working for the existing Care Card and Symptom Tracker views.

**Comment by kelseydedoshka-apple** [comment]
@ninoguba - thanks for the additional clarification here. Stay tuned for updates on this.
@akshay-yadav-apple , @Pariecemckinney-apple - please take a look at this.

**Comment by ninoguba** [comment]
Submitted PR #189 to resolve this.

**Comment by Pariecemckinney-apple** [comment]
@ninoguba The PR was merged. Thank you for the contribution.
