### ISSUE TITLE
Activities are now always grouped and sorted alphabetically

### ISSUE THREAD

**Issue by ninoguba** [carekit-apple/CareKit#183]
I appreciate that on the latest version of CareKit, activities now appear grouped and sorted alphabetically on the Care Card, Symptom Tracker, and the new Care Contents views as this may satisfy most use cases and requests from the community.

However I wish it was implemented in such a way that we can also configure the activities to appear ungrouped and sorted by the order they got added on the Care Plan, just like the way it was before.

In one of the apps I'm working on for example, all assessment activities belong to a specific groupIdentifier "Symptoms" and now appear on the Symptom Tracker showing a group section header title that offer no aesthetic value (there will always only be one group).  I will now need to hide it. More importantly I need to order all my assessment activities a certain way and the default alphabetical sorting breaks it. 

Some might argue I can just set their groupIdentifier to nil but I can't as I purposely use the groupIdentifier for querying the store data for the Insights.

**Comment by UberJason** [comment]
+1. I also think this is a good example for why the groupIdentifier should be separated into two properties, one for visual groupings and one for data store querying, as per my issue #170.

**Comment by ninoguba** [comment]
Created PR #188 for flexibility and backward compatibility.

**Comment by akshay-yadav-apple** [comment]
Thanks @ninoguba and @UberJason for pointing out this issue, and for submitting the PR #188. We will quickly review the PR and get back on this issue soon.

Thanks again!

**Comment by ninoguba** [comment]
PR merged so I'm closing this now.
