### ISSUE TITLE
Question: We can now swipe forward to future dates on the Care/Symptom views. Is this intentional?

### ISSUE THREAD

**Issue by ninoguba** [carekit-apple/CareKit#185]
Is this intentional for CareKit 1.2?

**Comment by akshay-yadav-apple** [comment]
Hey @ninoguba,
Thanks for pointing out this issue, it is not intentional.

**Comment by UberJason** [comment]
I feel like this may actually be a useful feature, though. For example, previewing your upcoming medication/assessment schedule (especially if your care plan is going to change soon, e.g. a provider has prescribed a new medication and ended an old one). Is there a reason to disallow it?

**Comment by akshay-yadav-apple** [comment]
@UberJason,
I agree it would be a good feature to allow viewing the upcoming activities, as long as the user is not allowed to complete any future activity (only view).

**Comment by ninoguba** [comment]
@akshay-yadav-apple so can we expect to have this date checking logic implemented within the framework or is this something you want app developers using CK to implement ourselves in our apps?

**Comment by ninoguba** [comment]
@akshay-yadav-apple submitted PR #199 to fix this unintentional change in CK 1.2.

**Comment by Pariecemckinney-apple** [comment]
@UberJason - We completely agree that this would be a very useful feature for many reasons. However, being that this was a unintentional change, we will accept this merge request and begin discussion on supporting the viewing of future dates. Thanks again for the great input and thank you @ninoguba for the issue and PR .

Closing now
