### ISSUE TITLE
Bug: App crashing when there are no events on the selected date and you tap Today button

### ISSUE THREAD

**Issue by ninoguba** [carekit-apple/CareKit#186]
This bug is evident in the Care Card, Symptom Tracker and Care Contents views.   When the selected date doesnt have any events and when the user taps on the Today button, the app crashes with the following error in the console:

> *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:]: section (0) beyond bounds (0).'

Tested this with OCKSample app and then scrolled the week page controller to the last week of 2015 to get no events on the table view.  You can also just add nothing or remove all activities on the Care Plan Store so you wont have to scroll back a lot.

**Comment by ninoguba** [comment]
Solved it.  Will submit a PR...

**Comment by Pariecemckinney-apple** [comment]
@ninoguba, Thank you for submitting a PR for this issue.

**Comment by Pariecemckinney-apple** [comment]
@ninoguba The PR has been merged. Thank you for the contribution. Closing the issue.
