### ISSUE TITLE
Missing () following default

### ISSUE THREAD

**Issue by moppymopperson** [carekit-apple/CareKit#190]
The sample app does not currently build in XCode 8 or 9 beta.

In 8 it does not build because of line 136 in the watch app's InterfaceController.swift file.
`tableView.insertRows(at: IndexSet.init(integersIn: Range(NSMakeRange(rowIndex, activityEventRows)) ?? 0..<0) , withRowType: "EventRow")`. This compiles fine under XCode 9 beta, so I believe it is related to a Swift 3/4 difference.

In 9 it does not build because of the lines  50 and 207 in the WatchConnectivityManager. Both use `WCSession.default` but should be `WCSession.default()`.

**Comment by Pariecemckinney-apple** [comment]
@moppymopperson, Thanks for the PR and pointing out the issue with line 136 in the interfaceController.swift file. For now, please use the following solution for Xcode 8.3.

`tableView.insertRows(at: IndexSet.init(integersIn:NSMakeRange(rowIndex, activityEventRows).toRange() ?? 0..<0) , withRowType: "EventRow")`
