### ISSUE TITLE
Android Port?

### ISSUE THREAD

**Issue by damianesteban** [carekit-apple/CareKit#195]
Hello folks. My team is planning on integrating CareKit into our iOS application in the coming months, and I was curious if anyone has discussed the potential of an Android version.

Thanks!

**Comment by matteocrippa** [comment]
@damianesteban I think there is no official support, but there are a couple of similar projects one is ResearchStack, but it is not affiliate with this at all and more similar to ResearchKit

**Comment by damianesteban** [comment]
Ok. Thank your for the information.
