### ISSUE TITLE
Bar charts only display up to 2 variables

### ISSUE THREAD

**Issue by scdi** [carekit-apple/CareKit#196]
It seems that when one attempts to display more than 2 bar chart series in insights only the percents values show and not the graphic charts themselves.

**Comment by smravca-apple** [comment]
Thanks for calling this out @scdi 
@akshay-yadav-apple and @Pariecemckinney-apple could you take a look at this one?

**Comment by Pariecemckinney-apple** [comment]
Hello @scdi, 

I haven't been able to reproduce the bug on my end. Would you mind sending a snapshot or some of the code you wrote? Any extra information would help. Also, what version of CK are you using?

**Comment by scdi** [comment]
Hi:

I attached three pictures. Two pictures to show visible chart for two
variables, and including the code generating the chart. The third picture
is the one where the chart is no longer visible once I attempt to show 3
variable. Percentages are displayed but the bars are not.

jude

**Comment by scdi** [comment]
I forgot to mention I m using CareKit version 1.2

**Comment by Pariecemckinney-apple** [comment]
@scdi - I'm not seeing any images on our end. Are you sure they were sent?

**Comment by ninoguba** [comment]
@Pariecemckinney-apple I have hit the same issue with the bar chart when it has more than 2 series.

This is the chart working as expected with 2 series:
<img width="452" alt="screen shot 2017-08-23 at 2 44 07 pm" src="https://user-images.githubusercontent.com/4361804/29640032-d18fc51a-8811-11e7-8231-5d71d959d055.png">

This is the chart not working with 3 series:
<img width="454" alt="screen shot 2017-08-23 at 2 44 49 pm" src="https://user-images.githubusercontent.com/4361804/29640054-e88409b6-8811-11e7-93ba-77b45d8100aa.png">

The code to generate the chart is pretty standard and can be reproduced from the OCKSample just by adding one more series.

Please note there is also a layout issue/bug for the first title in the legend collection.  However many in the legend collection, the first title always gets cut off with ... even if its a short title.

**Comment by ninoguba** [comment]
Definitely a layout constraint issue.  Here's the output in the console:

```
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600000495590 UIView:0x7fc65eff62b0.height == 12   (active)>",
    "<NSLayoutConstraint:0x6000004956d0 V:|-(0)-[UIView:0x7fc65eff62b0]   (active, names: '|':OCKChartBarView:0x7fc65eff60e0 )>",
    "<NSLayoutConstraint:0x600000495720 V:[UIView:0x7fc65eff62b0]-(0)-|   (active, names: '|':OCKChartBarView:0x7fc65eff60e0 )>",
    "<NSLayoutConstraint:0x600000495a40 UIView:0x7fc65eff68b0.height == 12   (active)>",
    "<NSLayoutConstraint:0x600000495b80 V:|-(0)-[UIView:0x7fc65eff68b0]   (active, names: '|':OCKChartBarView:0x7fc65eff66e0 )>",
    "<NSLayoutConstraint:0x600000495bd0 V:[UIView:0x7fc65eff68b0]-(0)-|   (active, names: '|':OCKChartBarView:0x7fc65eff66e0 )>",
    "<NSLayoutConstraint:0x600000495810 V:|-(0)-[OCKChartBarView:0x7fc65eff60e0]   (active, names: '|':UIView:0x7fc65eff5f40 )>",
    "<NSLayoutConstraint:0x600000495cc0 V:[OCKChartBarView:0x7fc65eff60e0]-(4)-[OCKChartBarView:0x7fc65eff66e0]   (active)>",
    "<NSLayoutConstraint:0x600000495d60 V:[OCKChartBarView:0x7fc65eff66e0]-(0)-|   (active, names: '|':UIView:0x7fc65eff5f40 )>",
    "<NSLayoutConstraint:0x600000495270 OCKGroupedBarChartBarGroupView:0x7fc65eff5690.height >= UIView:0x7fc65eff5f40.height   (active)>",
    "<NSLayoutConstraint:0x600000494c80 V:|-(2)-[OCKGroupedBarChartBarGroupView:0x7fc65eff3120]   (active, names: '|':UIView:0x7fc65ef8eaa0 )>",
    "<NSLayoutConstraint:0x600000495f40 V:[OCKGroupedBarChartBarGroupView:0x7fc65eff3120]-(16)-[OCKGroupedBarChartBarGroupView:0x7fc65eff5690]   (active)>",
    "<NSLayoutConstraint:0x600000495f90 OCKGroupedBarChartBarGroupView:0x7fc65eff5690.height == OCKGroupedBarChartBarGroupView:0x7fc65eff3120.height   (active)>",
    "<NSLayoutConstraint:0x6000004972a0 V:[OCKGroupedBarChartBarGroupView:0x7fc65eff5690]-(16)-[OCKGroupedBarChartBarGroupView:0x7fc65eff6ce0]   (active)>",
    "<NSLayoutConstraint:0x6000004972f0 OCKGroupedBarChartBarGroupView:0x7fc65eff6ce0.height == OCKGroupedBarChartBarGroupView:0x7fc65eff5690.height   (active)>",
    "<NSLayoutConstraint:0x600000498600 V:[OCKGroupedBarChartBarGroupView:0x7fc65eff6ce0]-(16)-[OCKGroupedBarChartBarGroupView:0x7fc65eff8330]   (active)>",
    "<NSLayoutConstraint:0x600000498650 OCKGroupedBarChartBarGroupView:0x7fc65eff8330.height == OCKGroupedBarChartBarGroupView:0x7fc65eff6ce0.height   (active)>",
    "<NSLayoutConstraint:0x600000499960 V:[OCKGroupedBarChartBarGroupView:0x7fc65eff8330]-(16)-[OCKGroupedBarChartBarGroupView:0x7fc65eff9af0]   (active)>",
    "<NSLayoutConstraint:0x6000004999b0 OCKGroupedBarChartBarGroupView:0x7fc65eff9af0.height == OCKGroupedBarChartBarGroupView:0x7fc65eff8330.height   (active)>",
    "<NSLayoutConstraint:0x60000049acc0 V:[OCKGroupedBarChartBarGroupView:0x7fc65eff9af0]-(16)-[OCKGroupedBarChartBarGroupView:0x7fc65effb140]   (active)>",
    "<NSLayoutConstraint:0x60000049ad10 OCKGroupedBarChartBarGroupView:0x7fc65effb140.height == OCKGroupedBarChartBarGroupView:0x7fc65eff9af0.height   (active)>",
    "<NSLayoutConstraint:0x60000049c020 V:[OCKGroupedBarChartBarGroupView:0x7fc65effb140]-(16)-[OCKGroupedBarChartBarGroupView:0x7fc661400890]   (active)>",
    "<NSLayoutConstraint:0x60000049c070 OCKGroupedBarChartBarGroupView:0x7fc661400890.height == OCKGroupedBarChartBarGroupView:0x7fc65effb140.height   (active)>",
    "<NSLayoutConstraint:0x60000049d380 V:[OCKGroupedBarChartBarGroupView:0x7fc661400890]-(16)-[OCKGroupedBarChartBarGroupView:0x7fc661402130]   (active)>",
    "<NSLayoutConstraint:0x60000049d3d0 OCKGroupedBarChartBarGroupView:0x7fc661402130.height == OCKGroupedBarChartBarGroupView:0x7fc661400890.height   (active)>",
    "<NSLayoutConstraint:0x60000049d4c0 OCKGroupedBarChartBarGroupView:0x7fc661402130.bottom == UIView:0x7fc65ef8eaa0.bottom   (active)>",
    "<NSLayoutConstraint:0x600000493970 V:|-(0)-[UIView:0x7fc65ef8eaa0]   (active, names: '|':OCKGroupedBarChartView:0x7fc65ef98030 )>",
    "<NSLayoutConstraint:0x6000004939c0 V:[UIView:0x7fc65ef8eaa0]-(24)-[OCKChartLegendView:0x7fc65eff0c50'\Ufffc\Ufffc']   (active)>",
    "<NSLayoutConstraint:0x600000493a10 V:[OCKChartLegendView:0x7fc65eff0c50'\Ufffc\Ufffc']-(0)-|   (active, names: '|':OCKGroupedBarChartView:0x7fc65ef98030 )>",
    "<NSLayoutConstraint:0x60800029d290 V:|-(15)-[OCKLabel:0x7fc65ef9b030'Meals/Snacks/Fluids Count']   (active, names: '|':OCKInsightsChartTableViewCell:0x7fc660020200'ChartCell' )>",
    "<NSLayoutConstraint:0x60800029e3c0 V:[OCKLabel:0x7fc65ef9b030'Meals/Snacks/Fluids Count']-(0)-[OCKLabel:0x7fc65ef8efc0]   (active)>",
    "<NSLayoutConstraint:0x60800029da60 V:[OCKLabel:0x7fc65ef8efc0]-(10)-[OCKGroupedBarChartView:0x7fc65ef98030]   (active)>",
    "<NSLayoutConstraint:0x60800029da10 OCKGroupedBarChartView:0x7fc65ef98030.bottom == OCKInsightsChartTableViewCell:0x7fc660020200'ChartCell'.bottom - 15   (active)>",
    "<NSLayoutConstraint:0x6000002999b0 'UIView-Encapsulated-Layout-Height' OCKInsightsChartTableViewCell:0x7fc660020200'ChartCell'.height == 326.667   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000495a40 UIView:0x7fc65eff68b0.height == 12   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

**Comment by ninoguba** [comment]
I found the issue is caused by the number of subviews in the _barBox view higher than the subviews in the _labelBox in OCKGroupedBarChartBarGroupView.  My interim hack solution is to simply add an empty label subview to the _labelBox to match my number of bar series. Not pretty in code but works for now.

**Comment by scdi** [comment]
Thank you so much for sharing. I was starting to think that I was doing
something wrong.

**Comment by Pariecemckinney-apple** [comment]
@ninoguba Thank you for posting the images and also providing a quick fix. Are you using version 1.2?
We will continue investigating the issue, but from a quick test on my end I am still not seeing any issues. The picture below shows me adding "moodEvents" to the backPain insight in the sample App. 

<img width="408" alt="screen shot 2017-08-28 at 11 07 40 am" src="https://user-images.githubusercontent.com/29615893/29787070-5d486188-8be2-11e7-9427-d11d5a01fc8d.png">

**Comment by ninoguba** [comment]
@Pariecemckinney-apple I'm pretty certain I'm using CK 1.2 but let me double check this with OCKSample again and see if I missed anything.

**Comment by scdi** [comment]
Thank you for looking into this. I noticed that with an app completely done in objective C, the problem did not show.
One question: What version of CareKit and ResearchKit are you using?

**Comment by Pariecemckinney-apple** [comment]
@scdi I am pulling directly from our current stable branch (1.2).

**Comment by scdi** [comment]
Are you using Xcode 9?

**Comment by Pariecemckinney-apple** [comment]
@scdi I ran it on both

**Comment by scdi** [comment]
Thank you so much. I am baffled.


On Thu, Aug 31, 2017 at 12:00 PM, Pariece McKinney <notifications@github.com

**Comment by ninoguba** [comment]
@Pariecemckinney-apple I ran OCKSample and it does show no issues with 3 bar series.  Let me then look at my embedded CK framework and make sure I'm on the very latest master.

**Comment by scdi** [comment]
Are the charts produced by ResearchKit or CareKit?

**Comment by ninoguba** [comment]
CareKit

**Comment by scdi** [comment]
I think that we can close this one. Although I have not tested CareKit
stable, I am guessing that the problem is because I have been using the
Master branch.

jude

**Comment by Pariecemckinney-apple** [comment]
@scdi Sounds good. Please feel free to reopen at any point if you want the conversation to continue. Thanks again for opening the issue.

**Comment by SNagra** [comment]
Was there a definitive solution to this problem? I am able to get three bar graphs together within the Sample app, but if I use the exact same CareKit framework within my app, I run into the original issue, which is the bar graphs disappear when going including more than 2 bars.

Tried the latest builds of builds of CareKit both on Master and Stable branches. I'm at my wits end trying to figure out the issue.

**Comment by scdi** [comment]
I asked to close it since I realized that I was using only using the Master branch versions. I never tested the stable branch until yesterday. The graph worked when I did.

jude
 



Jude Jonassaint, RN
jude@sicklesoft.com

Inclusion begins with a core belief that everyone deserves DIGNITY & RESPECT. 
This email may contain confidential information of the sending organization. Any unauthorized or improper disclosure, copying, distribution, or use of the contents of this email and attached document(s) is prohibited. The information contained in this email and attached document(s) is intended only for the personal and confidential use of the recipient(s) named above. If you have received this communication in error, please notify the sender immediately by email and delete the original email and attached document(s).
