### ISSUE TITLE
In the documentation, Care Card should also reflect mod and display of intervention activities and results

### ISSUE THREAD

**Issue by ninoguba** [carekit-apple/CareKit#200]
In Figure 1 in the updated documentation, the Care Card is illustrated to only display intervention activities from the Care Plan Store, which is not accurate.  It should be similar to the Symptom Tracker where in activities and results can be modified and displayed.

<img width="631" alt="maincarekitmodules" src="https://user-images.githubusercontent.com/4361804/28393649-d6e5934a-6c9c-11e7-8a62-869176e6bb41.png">

**Comment by Pariecemckinney-apple** [comment]
@ninoguba, Thank you for pointing this out. We will begin investigating the issue.
