### ISSUE TITLE
CareKit website is often down - Documentation

### ISSUE THREAD

**Issue by akac** [carekit-apple/CareKit#205]
I often hit the CK website for documentation but half the time I get this.
<img width="509" alt="screen shot 2017-07-27 at 11 41 14 am" src="https://user-images.githubusercontent.com/364743/28684130-83af867a-72c0-11e7-9614-2a8960915705.png">

PING carekit.org (23.235.47.133): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2

I don't have any other network issues, nor do I have any problems accessing any other Apple website. I can also access ResearchKit often.

**Comment by Pariecemckinney-apple** [comment]
@akac - Thank you for opening this issue. How long ago did you start noticing this problem? Also, how often?

**Comment by akac** [comment]
I noticed about a week or two ago, but I’ve only been really working hard on CareKit related stuff a month ago. It happens every other day and when it does it usually fixes itself later in the day. 

So I had my friend try to access it at the same time I couldn’t and he was able to. He was in Chicago, and I’m in Denver. Again, though I tried it on TMobile LTE and Comcast. Other sites (such as ResearchKit) worked fine.

Also I am using iOS 11 on my phone and Safari Tech Preview on my MacBook Pro. Not sure if that has anything to do with it.

**Comment by MacroYau** [comment]
Same happens to me right now in Hong Kong. The CK website is down, but the RK one works.

**Comment by Pariecemckinney-apple** [comment]
@akac & - We really appreciate you pointing this issue out. We will begin investigating immediately. @MacroYau - Thank you for your input also.

**Comment by addisonwebb** [comment]
This is still a constant issue. Can we reopen this to get this resolved?
