### ISSUE TITLE
OCKCareCardViewController: It is possible to complete future events

### ISSUE THREAD

**Issue by djknowles** [carekit-apple/CareKit#206]
**How to reproduce:**

- Create an activity.
- View the activity in the OCKCareCardViewController.
- Select a future day in the top of the screen day list.
- Complete the event by clicking on the circle.

**Issue:**

The UI now allows the completion of future events.

Previously it was not possible to visit a future day by clicking on the top day list. Thus it was not possible to complete the events.

I am not sure if this is deliberate but this is confusing to use and would lead to erroneous completion of events.

**Comment by ninoguba** [comment]
This is a duplicate of issue #185 which is now fixed by PR #199.

**Comment by djknowles** [comment]
Closing this issue.
