### ISSUE TITLE
More OCKCarePlanEventResult than events for the day

### ISSUE THREAD

**Issue by akac** [carekit-apple/CareKit#207]
In some cases, a user may need to do an assessment that's based on other events. So in some days they may have 1-2 assessments for a specific activity, and some days they may have 5 or 6 - and its not premeditated. 

What is the best way to create new events for a specific activity for that day only?

**Comment by Pariecemckinney-apple** [comment]
@akac - Would you mind giving a simple example? I believe that would help me understand exactly what you mean.

**Comment by akac** [comment]
To be clear - I've already modified CareKit pretty heavily - so the issue for me is somewhat moot, but I'm sure others may have a need for it as well.

So in our case, we need to do assessments whenever in the morning and evening - and after certain events. So at a minimum there are 2 assessments we have to do daily for a period of time. But a few times a week, there might be 3, 4, or 5 assessments after specific activities occur. A contrived example:

We might want to assess something after they ate. They might eat once in a day, twice, or three times. It depends on the day. I can't make this an optional activity because at least 2 times are non-optional. 

That's not our exact use-case, but its a good analogy.

**Comment by srinathtm-apple** [comment]
Closing this out as it's no longer applicable due to the CareKit 2.0 release.
