### ISSUE TITLE
OCKPatient and OCKCarePlanStore both reference each other through read only property

### ISSUE THREAD

**Issue by nikwest** [carekit-apple/CareKit#208]
I am wondering how the API of OCKPatient and OCKCarePlanStore is intended to be used. Both require each other in their respective init method and both only have public read only properties of each other.

The only (IMHO pretty non-swifty and non-elegant) way is to sub class e.g. care plan store. Then use either nil for patient or another init method. In this init method of the subclass create the patient using the not completely initialised store object. Finally call the super init of the store with the newly created patient. This will also create a circular reference between both objects. 

Maybe at least the public API should mark on of the properties as 'weak' to reflect this potential issue.

**Comment by Pariecemckinney-apple** [comment]
@nikwest - Thank you for pointing this out. You are correct in that the current structure doesn't seem to make much sense. We will begin investigating this today.

**Comment by srinathtm-apple** [comment]
Closing this out as it's no longer applicable due to the CareKit 2.0 release.
