### ISSUE TITLE
Activities need to be disabled instead of removed.

### ISSUE THREAD

**Issue by akac** [carekit-apple/CareKit#209]
For health regulations, we need to be able to always store/save the original recovery plan no matter the changes, as well as the event results. As such if an activity changes, you're essentially disabling the old activity and then adding a replacement one. 

However CareKit doesn't support that - you can't even change the schedule properly because the schedule is day-based, not time based. So if a doctor makes 3 changes in a day, you can't simply set the end date of an activity to stop today (think a doctor gave a patient a specific activity today, the user performed a task, put in a result - the doctor saw that and goes, hm, no I need to change something on that same day). Plus changing the schedule changes the activity which may break data collection requirements.

The answer is pretty simple - you add an "enabled" property to an Activity which is obviously on by default. Then add a method to deactivate an activity. 

I actually have already done this in my fork of CareKit and that is working great. I originally went the schedule route and in the real world saw the issues with that, so decided to go ahead and change the model to support "enabled:bool".

**Comment by ninoguba** [comment]
@akac can you contribute this to the framework or at least share this part of your fork publicly?

**Comment by akac** [comment]
I certainly can - I only didn't because I frankly wasn't sure if the *way* I did it was appropriate for public usage. But I can do it.

**Comment by riverbaymark** [comment]
@akac this is and excellent recommendation!  As a clinician I can attest to both points you brought up:
 1. Everything once documented needs to remain documented and easily retrievable.
 2. Making changes to a regimen happens much more frequently than everything going as planned. 

Thanks for sharing this.

Mark

**Comment by scdi** [comment]
@akac How did you solve this? Do you mind sharing? I currently have to use an additional core data schema.

**Comment by kelseydedoshka-apple** [comment]
@akac - this is a great suggestion and something we have been considering on our side as well! I love that others in the community are having similar thoughts. Would love to see how you accomplished this.

**Comment by srinathtm-apple** [comment]
Let's continue to track this issue via #71 , there seems to be significant overlap in the feature set..
