### ISSUE TITLE
CareKit - better modularized

### ISSUE THREAD

**Issue by akac** [carekit-apple/CareKit#210]
I love CareKit - but one of my biggest issues is that its too opaque. I needed to change a few things in the care, insight, and connect controllers and subclassing in these cases essentially having to rewrite most of the code…and expose classes such as table cells in the project to public. 

In the end, I've rewritten all of the controllers in CareKit myself in my own project (in Swift), and I use the CareKit data model, and quite a lot of the views. To do that, obviously I had to turn most of the CareKit views and so on to a public part of the framework. 

Again, I've already done this in my fork of CareKit - so I'm okay - but I figure others may want to customize things a bit more than what CareKit offers and I think the ability to do so natively without having to deal with all the objective-C framework fun would be beneficial. Maybe for CareKit 2.0 :)

**Comment by kelseydedoshka-apple** [comment]
@akac - thanks for bringing this up and some great points here. As you touched upon, a lot of the CareKit modules are very specific and built for the view's desired functionality so I can see where you might be running into some issues with customizations.

As a framework we love to see people take our base modules and change them to fit their specific needs, and to your point I think it would be great to start talking about how to make some of these items more modular to reduce work when customizing.

If you don't mind sharing I would be interested to know what kind of adjustments you find yourself making that you think could be integrated better into the framework models.

**Comment by srinathtm-apple** [comment]
Hey @akac - please checkout CareKit 2.0 :D
