### ISSUE TITLE
Inbox not showing up in Connect View

### ISSUE THREAD

**Issue by riverbaymark** [carekit-apple/CareKit#212]
The documentation is sparse in this area but any insight would be appreciated.  Trying to implement some code with the OCKConnectVIewController but the Inbox does not display in my view.   Also the stubbed out delegate and datasource examples leave out coding examples that would be extremely beneficial.  

Thanks!

**Comment by riverbaymark** [comment]
Hi @Pariecemckinney-apple,

Thanks so much for your help!  I've implemented the OCKConnectViewControllerDataSource methods but its still not showing up unfortunately.  I'm going to run the sample app and compare my current code vs the sample code today.

Thanks again!

Mark

**Comment by Pariecemckinney-apple** [comment]
@riverbaymark Just wanted to check in to see if a solution was found?

**Comment by riverbaymark** [comment]
@Pariecemckinney-apple Thanks for reaching back out and sorry wasn't back in touch.  I have been totally rewriting my code based more on your sample and it works perfectly now.  Very impressed with your new sample app!  Beautifully written.  

Kinda off topic but if you guys have any examples of utilizing multiple stores associated with multiple patients that would be greatly appreciated!

Thanks!

Mark

**Comment by Pariecemckinney-apple** [comment]
@riverbaymark No problem! What would be the use case for multiple stores if you don't mind me asking?

**Comment by riverbaymark** [comment]
@Pariecemckinney-apple I envision at least two scenarios.  One would be for a family.  Imagine "Sue" has 2 children and an elderly mother.  Sue is the only one with a device but would like to use an application powered by Carekit to keep track their asthma (which they all have).   The other scenario is in a practice setting.  I am in the process of creating a check-in / history entry app for my practice.  Since not all of my patients have an iOS device, I would let them use one of several iPads we have to enter their data, gain insights, share info via connect ,etc (kiosk mode and other patients data of course being secure and unviewable).  I am basing my assumptions there is a relationship of 1 store per patient.  

Thanks!

Mark

**Comment by Pariecemckinney-apple** [comment]
@riverbaymark Makes total sense. We don't have any built out examples but this would be possible if you utilized the "persistantDirectoryURL"  parameter when creating/initializing a OCKCarePlanStore. You would have to develop a way of uniquely generating a directory url for each patient you create. This means you would have to keep track/save the records of the directory urls and the patients that belong to them locally. 

Hope this helps and please let me know if you have any other questions or concerns!

**Comment by riverbaymark** [comment]
Thanks @Pariecemckinney-apple!

**Comment by Pariecemckinney-apple** [comment]
No problem! Closing. Please feel free to re-open anytime if you wish to continue the conversation.
