### ISSUE TITLE
Demo App crashed 

### ISSUE THREAD

**Issue by smkdoss73** [carekit-apple/CareKit#213]
OCKTest Demo app crashed, 

Steps:

1. click symptom Tracker
2. click Track Health Data

<img width="1440" alt="screen shot 2017-08-24 at 5 34 43 pm" src="https://user-images.githubusercontent.com/7939817/29665686-de5a643a-88f2-11e7-8f17-321f019a0cab.png">

**Comment by Pariecemckinney-apple** [comment]
@smkdoss73 Thank you for pointing out this issue. We will begin the process to get this fixed.

**Comment by Pariecemckinney-apple** [comment]
@smkdoss73 This bug will handled on our end. Thank you for posting this issue. Closing
