### ISSUE TITLE
Sample app has missing watch icons

### ISSUE THREAD

**Issue by gc435** [carekit-apple/CareKit#216]
The included sample app in CareKit 1.2 gets rejected when uploaded to iTunes Connect.  The error is:

> Missing Icons - No icons found for watch application 'OCKSample.app/Watch/OCKSampleWatch.app'. Make sure that its Info.plist file includes entries for CFBundleIconFiles.

I see that the watch `AppIcon` is in the iOS code's `Assets.xcassets`.  I haven't done Watch development yet.  If I put an `AppIcon` in `OCKSampleWatch/Images.xcassets`, it doesn't get recognized.  I have to call it `WatchAppIcon` or something else and then make the appropriate change in _App Icons Source_ for the Watch target.

What's the best way to solve this?

**Comment by kelseydedoshka-apple** [comment]
@gc435 - in general our sample apps shouldn't be uploaded to iTunes Connect. Are the missing watch icons something blocking you in development of your own app or just relative to the CareKit sample app?

**Comment by srinathtm-apple** [comment]
Closing out issues that are no longer relevant due to the CareKit 2.0 beta update.
