### ISSUE TITLE
Keep task showing up daily until completed?

### ISSUE THREAD

**Issue by SNagra** [carekit-apple/CareKit#217]
Hi,

Is it possible to have a task continue to show up in the Care Plan over a certain amount of days until it has been completed once, and then once completed, it will no longer show up on subsequent days?

Thanks

**Comment by ninoguba** [comment]
Yes.  As soon as they complete the activity. call setEndDate for that activity.

http://carekit.org/docs/Classes/OCKCarePlanStore.html#//api/name/setEndDate:forActivity:completion:

**Comment by kelseydedoshka-apple** [comment]
@ninoguba - thanks for the suggestion. @SNagra - did this help solve your issue?

**Comment by SNagra** [comment]
@kelseydedoshka-apple Yes this did! Thanks @ninoguba
