### ISSUE TITLE
The event "optional" property should not override the event groupIdentifier

### ISSUE THREAD

**Issue by boozi2** [carekit-apple/CareKit#220]
An optional event should also be allowed grouping if a groupIdentifier is defined

**Comment by riverbaymark** [comment]
I totally agree.  Several medications such as albuterol, migraine meds, etc. are used on a prn (or as needed) basis.  Other items such a a peak flow meter reading or pulse oximetry are also not necessarily performed on a scheduled basis.  Being able to group these would be very helpful.

**Comment by ninoguba** [comment]
Adding properties like groupOptionals and groupReadOnlys would address your requirement.   If these are TRUE (default) then optional and readonly activities will be grouped on their own as is now.   If these are FALSE then the activities will be grouped according to their groupIdentifier.

**Comment by kelseydedoshka-apple** [comment]
@boozi2, @ninoguba , @riverbaymark - all great suggestions and something we have considered on our side as well. One of the reasons we separated this out was to give users a clear indication that the activities were optional by providing the "Optional" section header. If these items were grouped together with other non-optional items there is no clear indication which activities are optional vs not. Would love to hear some suggestions you all might have on how to indicate optionality if grouped together.

**Comment by ninoguba** [comment]
@kelseydedoshka-apple you could use something like the edge indicators (previously available in early CK) to show activities that are optional.  You could also add a label after or below the activity's title and text to show a customizable "optional" text.  Another suggestion would be to italicize the activity's title to denote optionality.

**Comment by kelseydedoshka-apple** [comment]
@ninoguba - great suggestions! Overall I think these enhancements to Optional activities are a great suggestion, will consider moving forward!

**Comment by srinathtm-apple** [comment]
Closing this issue as we now support this workflow in CareKit 2.0
