### ISSUE TITLE
Pulldown refresh for Read-Only Activities

### ISSUE THREAD

**Issue by majidsaleem105** [carekit-apple/CareKit#222]
I implemented OCKCareContentsViewController and displayed Intervention, Optional and ReadOnly activities. I'm facing an issue that ReadOnly activities do not update with pull-down refresh. 

Here is a brief description:
1st Case: Changes in Intervention + ReadOnly
All activities gets reloaded with pull-down refresh if there is any changes in Intervention and ReadOnly activities.

2nd Case: Changes in Optional + ReadOnly
Same results. Everything works fine.

3rd Case: Changes in ReadOnly
View doesn't reload with new ReadOnly activities if there are changes in ReadOnly activities.

**Comment by akshay-yadav-apple** [comment]
Hey @majidsaleem105,
Thank you so much for bringing this to our attention. We will look into this so we can resolve this issue.

**Comment by akshay-yadav-apple** [comment]
Hey @majidsaleem105,
The _shouldEnablePullToRefreshInCareContentsViewController_ and _didActivatePullToRefreshControl_ delegate methods only initialize and start the refreshControl on the UI. The issue that you are facing depends on your implementation of _didActivatePullToRefreshControl_ method. Could you please verify the implementation again, and respond with how you are fetching the updates?

**Comment by majidsaleem105** [comment]
Hey @akshay-yadav-apple,
I've implemented both delegate methods that you mentioned in your reply. Initialization of UI wasn't my actual issue. 

PullDownRefresh is working perfectly fine when I made changes in Intervention and Assessments and new changes appear on my view card. But it doesn't load any new change if there are changes just in ReadOnly exercises.

Here is a brief description of my problem:
1st Case: Changes in Intervention + ReadOnly
All activities gets reloaded with pull-down refresh if there is any changes in Intervention and ReadOnly activities.

2nd Case: Changes in Optional + ReadOnly
Same results. Everything works fine.

3rd Case: Changes in ReadOnly
View doesn't reload with new ReadOnly activities if there are changes in ReadOnly activities.

How I implemented?
I implemented it with two ways:

1st Way:
1. I created a function to call an API to fetch new changes from server.
2. Implemented pullDownRefresh feature and called it in ViewDidLoad/ViewDidAppear.

2nd Way:
1. I implemented didActivatePullToRefreshControl delegate function as you suggested.
2. Called API to fetch new changes from server.

Results are same for both implementations. New changes do not appear on cardView if there are only changes in ReadOnly section.

**Comment by pthealthtech** [comment]
Hi @akshay-yadav-apple,

Is there any update on this task?

**Comment by akshay-yadav-apple** [comment]
Hey @pthealthtech,
I understand the desired functionality on this issue. The delegate methods mentioned above are only for refreshControl on UI. The code for fetching the updates in carePlan store are not part of these delegate methods.

**Comment by pthealthtech** [comment]
Hi @akshay-yadav-apple,

Can you please expand on your last comment? This an issue because our clinicians are ordering read-only activities and they are not appearing on the patient's care  card, even after a pull-down refresh. So they are both sitting there not understanding why it's not there so it gets ordered again.

**Comment by pthealthtech** [comment]
@akshay-yadav-apple, is there anything that can be done on this task? Our clinicians are really struggling with the fact that unless they order their read-only tasks with an activity, they aren't coming over to the patient's phone.

**Comment by dukemike** [comment]
@akshay-yadav-apple, I believe adding this to the `RootViewController` extension for the `OCKCareContentsViewControllerDelegate` replicates the problem.

`ActivityType.caffeine` doesn't disappear until switching to another day while `.weight` is removed immediately.

```
    func shouldEnablePullToRefresh(in viewController: OCKCareContentsViewController) -> Bool {
        return true
    }

    func careContentsViewController(_ viewController: OCKCareContentsViewController, didActivatePullTo refreshControl: UIRefreshControl) {
        storeManager.store.activity(forIdentifier: ActivityType.caffeine.rawValue) { (success, activity, error) in
            if success {
                if let activity = activity {
                    let calendar = NSCalendar(calendarIdentifier: NSCalendar.Identifier.gregorian)!
                    let yesterday = calendar.components([.day, .month, .year], from: calendar.date(byAdding: .day, value: -1, to: Date(), options: NSCalendar.Options(rawValue: 0))!)
                    self.storeManager.store.setEndDate(yesterday, for: activity, completion: { (success, activity, error) in
                        if let error = error {
                            print("failed to update activity: \(error.localizedDescription)")
                        } else {
                            print("ended activity")
                        }
                    })
                }
            }
            DispatchQueue.main.async(execute: {() -> Void in
                refreshControl.endRefreshing()
            })
        }
    }
```

**Comment by akshay-yadav-apple** [comment]
Hey @dukemike,
Fix for handling changes in activity list is merged into master. Please pull latest master and check if it resolves the issue.

**Comment by akshay-yadav-apple** [comment]
Hey @pthealthtech,
The latest fix calls carePlanStoreActivityListDidChange for changes in OCKCarePlanActivityTypeReadOnly also.  However, how the changes in activities reflect in the app, still depends on your implementation inside didActivatePullToRefreshControl delegate method. Please let us know if the fix resolves the issue for your use case.

**Comment by dukemike** [comment]
@akshay-yadav-apple Thanks for the fix. It worked for me.

**Comment by pthealthtech** [comment]
@akshay-yadav-apple Thank you for the fix, it soled our issue as well.
