### ISSUE TITLE
Access controls on messages

### ISSUE THREAD

**Issue by riverbaymark** [carekit-apple/CareKit#224]
Allowing message conversations between patients and healthcare providers / offices brings forth some definite challenges such as:

1.  Who can initiate contact (provider / office or patient).
2.  Although the vast majority of patients would never "abuse" such a system, there are some who would see it as a 24/7 open access line which opens up major liability for a practice.
3.  With medical messaging there needs to be a way messages are divided by topic (e.g. the same patient might have a message to please refill my blood pressure medication one day and the next week need to ask about a sore throat).  There also needs to be a way these topics are "closed" by the provider office or patient once the topic has come to resolution.  
4.  Consideration of a "messaging center".  Currently most offices whether small or large have someone who takes the message and possibly relays it to a nurse or the provider.  In messages I could see this as basically a group message that goes to the message person, nurse, and provider.

Any thoughts or suggestions from there community?

I have included some of my thoughts below from a previous post but felt it was pertinent to include them here:

There are concierge medicine practices and other practices that offer enhanced services that promote direct access to a provider, so some type of access control would be a great idea. In this scenario it is likely a patient could initiate a conversation but the provider should have the ability to "close" it.
The ability for a provider to initiate a conversation with a patient and then "close" it is also an excellent idea.
Traditionally offices have a "phone nurse" or "message center" where everything is routed through. Questions are then brought to the provider and an answer is relayed back to the patient. I could almost envision this as a "group message" where a message stays open until it is answered by an appropriate party with multiple persons (nurses, providers, etc.) being able to view it.
The hard thing is with a continuous message stream, if a patient has multiple interactions, then being able to go back and see specific items is hard over time. There almost needs to be a way to have the message interaction but it be categorized by person (primary) and by issue (secondary). One great analogy I can think of is this very format we are discussing things in right now. In GitHub there are issues a person brings up, someone can answer the issue at hand, and then it can be closed but looked back on historically if need be (as often is the case). In the GitHub example though it is kinda the reverse in that issue is primary and the person asking the question is secondary.

**Comment by ninoguba** [comment]
Requirements and controls for secure messaging between patients and providers can vary greatly across organizations.  I believe there are companies that already provide messaging solutions for healthcare-related use cases.  I would defer to their expertise on this matter.

On the CK front however, the framework already provides the basic UI and delegate methods for allowing messaging in your app but will still need integration with messaging backend solutions and further customizations to fit anyone's particular requirements.

**Comment by riverbaymark** [comment]
At HIMSS last year, there were probably hundreds of messaging solutions but they almost all suffered from the same fatal flaws.  The first is as a provider it is not feasible to have multiple communication applications that you have to check frequently.  The second is messaging in a clinical setting requires the ability to group and filter as mentioned above.  I have not seen any solutions that do this or do it well and actually have the ability to integrate with an EHR.  

On a tangent, as I have talked with several providers about their desire for communications, they almost all prefer some type of graphical interface that shows overall how a patient is doing in certain areas (think asthma symptom scores, blood pressure, etc).  Kinda a green, yellow, red zone graph that they can easily gauge.  

My hope is that Apple is large and influential enough to help bring some order to the wild, wild, west of healthcare communication applications.  It greatly needs more uniformity in this regard.  An issue with several messenger providers is they think they know what providers would like, instead of actually seeing how their systems work in a true clinical setting.  This is evidenced by the number of complaints that are discussed daily with colleagues about these services.  The thing I have enjoyed seeing with ResearchKit and CareKit is that suggestions from practicing clinicians are usually incorporated into APIs.

**Comment by kelseydedoshka-apple** [comment]
@riverbaymark - appreciate your thoughts and feedback here, thanks for sharing! Would love to keep this conversation open for others to share their thoughts here as well.

**Comment by riverbaymark** [comment]
@ninoguba @kelseydedoshka-apple Hi guys sorry if my last post sounded aggressive its just a boiling over frustration with how broken our healthcare communication is.  Going through the breast cancer battle with my wife over the last year (she's doing great now :) and doesn't mind me sharing her experience) and trying to communicate with various institutions across the US has been an even more eye opening experience.  If I hadn't been a provider and used my resources to help securely send documents and converse, its scary to think of how much more a horrible experience it would have been.  Again hats off to you guys and the Awesome work Apple is doing in making this stuff easier!

**Comment by srinathtm-apple** [comment]
Closing out this issue as it is no longer relevant due to CareKit 2.0 beta update..
