### ISSUE TITLE
CareKit - Update activity status from start to end date in iOS

### ISSUE THREAD

**Issue by jasminpsa** [carekit-apple/CareKit#227]
There is problem with update OCKCarePlanEvent status as completed in OCKCarePlanStore from it's start to end date of an activity(OCKCarePlanActivity)

Visit [here](https://stackoverflow.com/questions/47881351/carekit-update-activity-status-from-start-to-end-date-in-ios) for more information.

**Comment by jasminpethani** [comment]
@akshay-yadav-apple 

Any update on this issue ?

**Comment by jasminpsa** [comment]
Yes @akshay-yadav-apple any update on this issue ?

**Comment by akshay-yadav-apple** [comment]
Hey @jasminpsa,
I am trying to understand the issue, and a little more explanation of the problem will be extremely helpful to clearly understand the issue. 
Does the JSON show events for a particular intervention for each day from Nov 19 to Nov 25, and there are 7 events for each day except Nov 24 which has only 3 events for the same intervention?
Please let me know if that is correct.
Also, please provide any more details of the problem if possible.

**Comment by jasminpsa** [comment]
Hi @akshay-yadav-apple 
Yes, JSON shows events for a particular intervention with there status (1 is completed and 0 is not completed). 

> Problem is i can update event status for one week only (not more than that)  
> No such method i found which can help me to update event status from activity's start to end of date. 

```
"occurrence": {
      "Sun, 19 Nov 2017" : [0,0,0,0,1,0,0],
      "Mon, 20 Nov 2017" : [0,1,0,1,1,0,0],
      "Tue, 21 Nov 2017" : [0,1,0,0,0,0,1],
      "Wed, 22 Nov 2017" : [0,0,0,0,0,0,0],
      "Thu, 23 Nov 2017" : [0,1,0,0,0,0,0],
       "Fri, 24 Nov 2017" : [0,0,0],
      "Sat, 25 Nov 2017" : [0,0,0,0,1,0,0]
    }
```
Here in example you can see only seven days data is appear but if you enter more than 7 days of occurrences are not allowed on `OCKCareSchedule`  objects that's why it rise an error at
` NSParameterAssert(occurrencesFromSundayToSaturday.count == 7);`

**What i have tried?(steps)**
- Replacing existing intervention activity in OCKCarePlanStore with our custom activity with occurrences calculated from above JSON
-  _enumerateEvents_ from it's start to end date will provide events which has scheduled events in store before otherwise nil
- updating status of event which matching with date mention(e.g.  "Sun, 19 Nov 2017") and status == 1  and update the status in store.

After this I have tried many other ways  to update the event status but couldn't find way to solution. In short  _OCKCarePlanStore_ should have method for updating events status from it's start to end date of intervention activity.

**Comment by jasminpsa** [comment]
Hi @akshay-yadav-apple  

Did you find any update on this ? 
You can ask here if you need yet more explanation

**Comment by akshay-yadav-apple** [comment]
Hey @jasminpsa!
The explanation definitely helped understand the issue better. The assertion mentioned above is checked during initialization of a schedule object. AFA I understand you want to update events of an already created intervention activity. Using the _updateEvent_ method in CarePlanStore is how you can update the events programatically. Is that what you are trying in the step 3 above.

**Comment by jasminpsa** [comment]
Hi @akshay-yadav-apple 
Yes I am trying to update event in care plan in step 3 above.
But i want to update scheduled activity to update that status from it's start of activity to it's end date.

**Comment by akshay-yadav-apple** [comment]
@jasminpsa,
With the currently available API, were you able to iterate thru startDate till endDate from the json, and call updateEvent for each date? Did that resolve the issue for your use case?

**Comment by jasminpsa** [comment]
@akshay-yadav-apple 
No I am not able to resolve the issue with my use case.

**ISSUE:** As mentioned above i can only update event for only 7 days not more than that.
We can't schedule event for an activity for more than 7 days (method should be without time bound i mean weekly, monthly ...etc)  

Also tried with scheduling daily activity for it's start to end date of activity but at a time only one schedule object can be assign for activity due to restriction of single object of `OCKCareSchedule` in `OCKCarePlanActivity`
```
+ (instancetype)dailyScheduleWithStartDate:(NSDateComponents *)startDate
                         occurrencesPerDay:(NSUInteger)occurrencesPerDay;
```
There should be some method which can help to update event status from event's start to end date.

If you have solution or method in existing api which can help in this issue it will be better.

**Comment by ninoguba** [comment]
@jasminpsa an activity with no end date is supported in CareKit. All you need to do is initialize your OCKCarePlanActivity with an OCKCareSchedule that has a nulled end date.

Updating the event's state is also straightforward using OCKCarePlanStore's updateEvent API.  You will need a collection of events and call updateEvent on each of them iteratively.

You have several options to get a collection of events.  I'm not 100% sure though if you can get events for future dates. Will have to test.  Obviously you can only call updateEvent on existing events. The API documentation says:  "Update the state of an event after the user has responded to it."

Hope this helps.

**Comment by ninoguba** [comment]
I did a quick simple test by modifying the Insights of OCKSample and found that you can query events for future dates and they will be returned and thus you can call updateEvent on them to change the status.

OCKSample's Insights use the enumerateEvents API and is passed a start and end date.  I simply modified the call so the end date will be a future date so now I have a collection of events.  Then somewhere in the Insight Builder class, I added the following snippet:

```
        events.forEach { (event) in
            CarePlanStoreManager.sharedCarePlanStoreManager.store.update(event, with: nil, state: OCKCarePlanEventState.completed, completion: { (success, updatedEvent, error) in
                if (!success) {
                    print(error?.localizedDescription)
                }
            })
        }
```

I confirmed I was able to update the state for events with future dates.  

So definitely this would work in your use case whether your activity's end date is set or not and whether your events are in the past, present, and future.

**Comment by jasminpsa** [comment]
@ninoguba 
I have tried updating event for particular activity your way but getting error:

`*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 1 beyond bounds [0 .. 0]'`

**What i have tried ?**
As shown below i have tried by changing start Date and endDate for outdoorWalk activity 
 ```
let startDate = DateComponents(year: 2017, month: 12, day: 24)
  let endDate =  DateComponents(year: 2017, month: 12, day: 31)
  let outdoorWalkEventsOperation = QueryActivityEventsOperation(store: carePlanStore,
                                                                      activityIdentifier: ActivityType.outdoorWalk.rawValue,
                                                                      startDate: startDate,
                                                                      endDate: endDate)
```

In the completion Block of `buildInsightsOperation.completionBlock` 

```
buildInsightsOperation.outdoorWalkEvents?.allEvents.forEach({ (event) in
                        self.carePlanStore.update(event, with: nil , state: .completed, completion: { (isSuccess, updatedEvent, error) in
                            if !isSuccess {
                                debugPrint("Error: not udpateding care plan event")
                            }
                        })
                    })
```


Can you provide the thing you have tried ?  So, i can play with dates and see the changes  with JSON i have already mention above .

**Comment by ninoguba** [comment]
Look at the OCKSample closely.  Here's how the activities' schedules are initialized:

`let schedule = OCKCareSchedule.weeklySchedule(withStartDate: startDate as DateComponents, occurrencesOnEachDay: [1, 1, 1, 1, 1, 1, 1])`

This API makes the endDate not defined making the activities open ended.  In your app, if the activities are already added in the care plan store, then you'll need to call setEndDate() to modify it's schedule.

http://carekit.org/docs/Classes/OCKCarePlanStore.html#//api/name/setEndDate:forActivity:completion:

Now for my simple test, I simply changed the queryDateRange in the InsightsBuilder to start on the start of the previous week and end on the end of the following week. (Note the default ends it at the current date). So now this provides me a collection of events for my activities spanning the calculated date range.

Then to test the eventUpdate API, I added  the following function:

```
    /**
     For a given array of `OCKCarePlanEvent`s, mark them as completed.
     */
    fileprivate func updateEvents() {
        // Make sure there are events to parse.
        guard let events = medicationEvents else { return }

        // Set start date to the start of the previous week
        let calendar = Calendar.current
        var components = DateComponents()
        components.day = -7
        let startDate = calendar.date(byAdding: components as DateComponents, to: Date())!

        /*
         Loop through 14 days beginning on the start date, ending on the end of the following week
         */
        for offset in 0..<14 {
            // Determine the day to components.
            components.day = offset
            let dayDate = calendar.date(byAdding: components as DateComponents, to: startDate)!
            let dayComponents = calendar.dateComponents([.year, .month, .day, .era], from: dayDate)
            
            // Update the events for the corresponding day.
            let eventsForDay = events[dayComponents]
            eventsForDay.forEach { (event) in
                CarePlanStoreManager.sharedCarePlanStoreManager.store.update(event, with: nil, state: OCKCarePlanEventState.completed, completion: { (success, updatedEvent, error) in
                    if (!success) {
                        print(error?.localizedDescription)
                    }
                })
            }
        }
    }
```

And call this function within the main() func of BuildInsightsOperation.

**Comment by erik-apple** [comment]
I'm going to close this due to inactivity and the release of CareKit 2.0.
Feel free to re-open this issue or create a new one if the same problem persists in CK 2.0.

I think you'll find that scheduling has become much more flexible in the most recent version.
