### ISSUE TITLE
CareKitTests - testThresholds is failing

### ISSUE THREAD

**Issue by UberJason** [carekit-apple/CareKit#228]
The testThresholds test in CareKitTests is failing on line 935 with `((cdThreshold) == nil) failed`. Here's a quick screenshot:

<img width="1278" alt="screen shot 2017-12-23 at 5 37 58 pm" src="https://user-images.githubusercontent.com/5779307/34323096-1d68cefe-e808-11e7-856d-07078db94169.png">

I believe there is an error in the actual assertion on line 935, and CareKit itself is fine. The schedule for this activity is a "twice every other day" schedule (`occurrencesPerDay = 2`, `daysToSkip = 1`), and most of the other assertions in this test are asserting the threshold is correct on `startDate` and nil on `startDate` + 1 day. On line 935, the test is asserting the threshold is nil on `startDate`. The PR for this fix is #229.

**Comment by kelseydedoshka-apple** [comment]
@UberJason - thanks for catching this, and the fix as well.

**Comment by kelseydedoshka-apple** [comment]
@UberJason - merged the PR, closing this out!
