### ISSUE TITLE
Localize OCKCarePlanActivity title.

### ISSUE THREAD

**Issue by ZaidSA** [carekit-apple/CareKit#235]
I am trying to localize the title of `OCKCarePlanActivity` and `groupIdentifier` as well.
But at initialisation it stores the title in Care plan store, so I am unable to localize the title.
It there any method provided to achieve this?

**Comment by akshay-yadav-apple** [comment]
Hey @ZaidSA,
Are you initializing the OCKCarePlanActivity and then changing the system language, or are you initializing the OCKCarePlanActivity with a localized string?

**Comment by ZaidSA** [comment]
@akshay-yadav-apple,
Yes, Initializing the OCKCarePlanActivity and then changing the system language.

**Comment by akshay-yadav-apple** [comment]
Hey @ZaidSA , so according to current implementation, the localized string is saved in CarePlanStore. So if you launch your app when the system is set to language A and then switch to language B, you won't see any difference. However, if you switch the language B and then launch the app for the very first time, the localized string will show up as expected. Let me know if that made sense.

**Comment by ZaidSA** [comment]
thanks @akshay-yadav-apple, so you mean once we have set string on language A on first launch, we can't update string to language B in future, is that correct?
If yes, then any possibilities of dynamic languages in current code or in future planning?

**Comment by srinathtm-apple** [comment]
Closing this out as it's no longer applicable due to the CareKit 2.0 release.
