### ISSUE TITLE
Accessibility issue with OCKCareCardViewController

### ISSUE THREAD

**Issue by vallamk** [carekit-apple/CareKit#237]
Hi,

I am trying to test my app developed on Care Kit and Research Kit api to be ADA compliant.

My app is crashing when i am trying to load OCKCareCardViewController. View loads fine but crashes right after with the below stack trace.

I am using CareKit 1.2 version.

Stack Trace :

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString appendString:]: nil argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105b0f12b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001051a3f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000105b84245 +[NSException raise:format:] + 197
	3   CoreFoundation                      0x0000000105b4d464 mutateError + 196
	4   CareKit                             0x000000010466ff4c _OCKAccessibilityStringForVariablesWithVariadics + 188
	5   CareKit                             0x0000000104670278 _OCKAccessibilityStringForVariables + 376
	6   CareKit                             0x0000000104641f3d -[OCKHeaderView accessibilityLabel] + 109
	7   UIAccessibility                     0x00000001265ec80c -[NSObject(AXPrivCategory) _accessibilityPotentiallyAttributedValueForNonAttributedSelector:attributedSelector:] + 244
	8   UIAccessibility                     0x00000001265ec968 -[NSObject(AXPrivCategory) _accessibilityAXAttributedLabel] + 41
	9   UIKit                               0x00000001263dcf25 -[UINavigationBarAccessibility_UIViewAccessibilityAdditions _accessibilityAXAttributedLabel] + 650
	10  UIAccessibility                     0x00000001265f096c -[NSObject(AXPrivCategory) accessibilityAttributeValue:] + 2374
	11  UIAccessibility                     0x00000001265cd7c0 _copyMultipleAttributeValuesCallback + 363
	12  AXRuntime                           0x0000000122da7ff6 ___AXXMIGCopyMultipleAttributeValues_block_invoke + 65
	13  AXRuntime                           0x0000000122da7b9f _handleNonMainThreadCallback + 55
	14  AXRuntime                           0x0000000122da7e76 _AXXMIGCopyMultipleAttributeValues + 291
	15  AXRuntime                           0x0000000122da2747 _XCopyMultipleAttributeValues + 454
	16  AXRuntime                           0x0000000122db4f24 mshMIGPerform + 247
	17  CoreFoundation                      0x0000000105a9e7d9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	18  CoreFoundation                      0x0000000105a9e741 __CFRunLoopDoSource1 + 465
	19  CoreFoundation                      0x0000000105a96524 __CFRunLoopRun + 2596
	20  CoreFoundation                      0x0000000105a95889 CFRunLoopRunSpecific + 409
	21  GraphicsServices                    0x000000010e9059c6 GSEventRunModal + 62
	22  UIKit                               0x0000000106dcf5d6 UIApplicationMain + 159
	23  Bees Knees                          0x00000001040c1557 main + 55
	24  libdyld.dylib                       0x000000010bb8cd81 start + 1
	25  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any help is greatly appreciated.

Thankyou,
Kranthi.

**Comment by akshay-yadav-apple** [comment]
Hey @vallamk,
Thanks for bringing this to our attention. We have fixed this issue in the master branch. Please let us know if you still have this issue.

**Comment by vallamk** [comment]
Hi,

Thank you for fixing the issue. I got the master branch code and it is working as expected.
Thank you once again for quick fix.

I am seeing one more issue with Accessibility on OCKCareCardViewController. Voice over is not detecting the arrow mark on Intervention activity to let users know that they can tap on it to get the details of the activity. 
Do you expect this to be created as a separate issue?
If you can help me with this issue too that will be great.

Thank you,
Kranthi.

**Comment by lukeredpath** [comment]
I was also running into this issue - slightly different symptom but same cause. In my case I'm trying to write some UI automation tests of a screen that uses the care contents view controller and when I tried to put the app's debugDescription it crashed due to the nil accessibility label on the ring view. Glad to see this is fixed.

**Comment by srinathtm-apple** [comment]
Closing this out as it's no longer applicable due to the CareKit 2.0 release.
