### ISSUE TITLE
Parallel tasks rather than serial

### ISSUE THREAD

**Issue by pthealthtech** [carekit-apple/CareKit#238]
We have patients that need to work on one task, minimize it (paused but still active) open another task, work on it, pause it, resume task #1.

Does anyone know if patients can have multiple activities/tasks open at the same time?

**Comment by akshay-yadav-apple** [comment]
Hey @pthealthtech 
Are you referring to ORKTask from ResearchKit? If that is correct, are you trying to maintain state of a task? ResearchKit does not allow having more than one active task open at a time, however ResearchKit supports coming back to a task on the step where you left at. Is that what you are trying to achieve. Can you give an example of the ask?

**Comment by pthealthtech** [comment]
Sometimes they have to be performing an exercise activity and in the middle of it, do either a different exercise activity or take a measurement, then come back and do more of the first activity. They may swap back and forth several times between tasks. We can handle this by having multiple instances of the same order but that gets messy for the patient.

**Comment by srinathtm-apple** [comment]
Closing out this issue as it is no longer relevant due to CareKit 2.0 beta release..
