### ISSUE TITLE
watchOS sample app threading issues

### ISSUE THREAD

**Issue by micpringle** [carekit-apple/CareKit#240]
I noticed when running the watchOS sample app that the following message is printed several times to the debug window...

```
2018-02-20 11:30:08.084466+0000 OCKSampleWatch Extension[7181:609594] [default] -
[WKInterfaceController setTitle:]:330: -[WKInterfaceController setTitle:]: called from 
queue other than main. This is not supported and may fail in the future.
```

Setting a symbolic breakpoint for `[WKInterfaceController setTitle:]` reveals that `setTitle` is called twice from a background thread...

1. From `session(_:, activationDidCompleteWith:, error:)` via the call to `loadData()`
2. From `session(_:, didReceiveMessageData:)`, in the `allData` case, via the call to `updateTitleLabel(withCompletionPercentage:)`

Shouldn't these calls be dispatched to the main thread?

**Comment by srinathtm-apple** [comment]
Closing out this issue as it is no longer relevant due to CareKit 2.0 beta release..
