### ISSUE TITLE
Voice over is not reading OCKCareCardViewController OCKCareCardTableViewCell button

### ISSUE THREAD

**Issue by vallamk** [carekit-apple/CareKit#241]
Hi,

I am working on testing voice over on my app that is built with CareKit Api. 
I am seeing an issue with CareCard view where voice over is not letting user know that they can tap on arrow button to get the details of the activities.
I debugged the code little bit and found that,
In OCKCareCardTableViewCell, accessibilityElements function does not have any accessibility information for arrow button. 
I added  [self.axChildren  addObject:_button]; before [self.axChildren addObjectsFromArray:_frequencyButtons]; in accessibilityElements function to test if that is the problem and it turned out to be it.
Now voice over is able to get to the arrow button and reading out that it is a button. 
But i would like to add accessibility label to the button to mention to users that they can double tap on it to get details. I am not sure where i can add it.

Can any one please help me with this.

Thank you,
Kranthi.

**Comment by srinathtm-apple** [comment]
Closing this out as it's no longer applicable due to the CareKit 2.0 beta update.
