### ISSUE TITLE
Patient App [Care Contents] Past days in current week appear as completed and past days before enrollment look the same as future days

### ISSUE THREAD

**Issue by NirajMedable** [carekit-apple/CareKit#246]
### Issue 1
Past days in current week show as completed when no care card exists for those days.   The example in the image is that Thursday is the first day of care.   I think its doing this because the days before have no card so therefore they are 100% complete.  But its inconsistent with what Issue 2 below shows.  

![issue__1](https://user-images.githubusercontent.com/16706952/37221552-aa2a9c40-2387-11e8-959b-d71fd5caa2e1.jpg)

### Issue 2 
Past days before the current week show as blank.  Like future days should show.  

![issue__2](https://user-images.githubusercontent.com/16706952/37221631-e125b356-2387-11e8-9cd6-e166e6e85fba.png)

Is this a bug or expected behavior just to depict to users that where they are at in the current week when they enroll?

**Comment by akshay-yadav-apple** [comment]
Hey @NirajMedable,
Thanks for reaching out with this issue. This is an unexpected behavior. Past weeks before the week with the start date should also show completed rings. Since I am unable to recreate this issue, can we look at the schedule objects for your activities and I'll try to mimic the apps behavior on my end.

**Comment by NirajMedable** [comment]
@akshay-yadav-apple talking to the customer we are building for, they actually prefer the days not to be starred in previous weeks cause to patients it indicates they completed activities on the screen when none were present.  The feedback I received was that even on the current week, where there are no activities, its best to have blank with the start date of the care card to be indicated in a better way.   Just some thoughts.   If there is a way to control the state of these rings, can you point me to that solution in the docs please?  Thanks!

**Comment by akshay-yadav-apple** [comment]
@NirajMedable 
This sounds like a good idea. Currently the API does not provide any way to not show the completed ring if there are no activities for a day. If this is acting as a blocker for any project, the attached diff shows the changes needed as a temporary fix in care contents, however a more concrete fix will be something like having a property that developers can set to choose completed ring/or not. This does sounds like something we would want to include in CareKit, but unfortunately its not in our immediate scope. Please feel free to submit a PR if you ever get to implement this for any of your project. It will definitely be a wonderful addition to the framework.

[diff.patch.zip](https://github.com/carekit-apple/CareKit/files/1812553/diff.patch.zip)

**Comment by NirajMedable** [comment]
@akshay-yadav-apple Thanks so much, I'll pass to my team!  Can you share what's in your immediate timeline for the next version of Carekit or when that next release is planned?  It would be helpful for my own product planning purposes.   Thanks!

**Comment by ninoguba** [comment]
#259

**Comment by erik-apple** [comment]
CareKit 2.0 addresses this request by means of a new OCKAdherenceAggregator enum. It comes with several options out of the box, and you can also pass it a closure to define your own custom adherence computation rules. The completion rings also have more states that you can use to differentiate between days on which there was nothing to do and days on which the user didn't complete their tasks.
