### ISSUE TITLE
Confused about how assessment activities are presented and updated

### ISSUE THREAD

**Issue by lukeredpath** [carekit-apple/CareKit#248]
As per the title, I'm a bit confused about how a user is supposed to record new results for an assessment activity.

For example, if I have an activity to record blood pressure with a schedule of twice a day and the user already gave me their initial reading as part of some onboarding/setup process, I update the first event of the day with the result and this is displayed on both the care contents and symptom tracker view controllers.

From here, what is supposed to trigger the capture of the result for the second event of the day?

The blood pressure row in both of the above controllers is associated with the already completed event (and it displays the result). Tapping on the controller in the care contents view triggers the delegate callback `careContentsViewController(_:, didSelectRowWithAssessmentEvent:)` but the event passed to this callback is already completed.

Tapping on the row in the symptoms tracker does nothing - it doesn't highlight and no delegate callback is received.

I'm also confused as to why these rows do not display any circles as it does for intervention activities.

The documentation, which seems to be out of date, refers to a protocol `OCKEvaluationTableViewDelegate` which doesn't exist. It suggests implementing the protocol method to launch some custom scene for performing the assessment and capturing the results. I assume this is now `OCKSymptomsTrackerViewControllerDelegate` but as per above, this is never called because the row presented on the symptoms tracker is associated with the already completed event.

What should I be doing here?

**Comment by Pariecemckinney-apple** [comment]
Hello @lukeredpath, 

Thank you for pointing out that our documentation refers to the wrong delegate. We will investigate the issue and get it fixed as soon as possible. In regards to your other issue, is there a reason that you chose to use CareContents and SymptomTracker view controllers in tandem? This is something that we don't recommend as CareContents is meant to include all of the functionality of a SymptomTrackerViewController. This might help me get a better understanding of the overall goal. Looking forward to your response.

**Comment by lukeredpath** [comment]
@Pariecemckinney-apple thanks for your reply.

Just to be clear, I'm not trying to use both CareContents and SymptomTracker, sorry for the confusion. I was trying both out to see if I could better understand how it handled assessment events but I actually only want to use the CareContents screen.

The issue I'm having is I don't understand why assessment events aren't presented in the same way as intervention events (e.g. with round empty circles indication it awaits completion) or why it only seems to support one event per day for assessment events (you can create an assessment activity with a frequency of multiple times per day but there's no obvious support for this in the UI).

For now I've worked around it by creating two separate assessment activities - one for blood pressure reading in the morning and one for in the evening.

**Comment by tmbiOS** [comment]
@lukeredpath!
Hi!
Did you found the idea how to solve your problem?

**Comment by lukeredpath** [comment]
@tmbiOS creating separate assessment activities for morning/evening worked in my case.
