### ISSUE TITLE
Glyph image not seen for custom implementation

### ISSUE THREAD

**Issue by mukulm24** [carekit-apple/CareKit#253]
I have added OCKRingView in another view. I have set isCareCard true. 

I cannot see the glyph image, only the circular progress is seen.

**Comment by akshay-yadav-apple** [comment]
Hey @mukulm24,
Are you trying to add OCKRingView in CareContentsViewController or are you trying to use it in a custom View Controller in your app. Ideally it should work. Can you please provide some code snippets for more clarity.

**Comment by mukulm24** [comment]
I'm updating the CareContentsViewController to show a glyph of the current activity progress. 
So I'm adding the glyph to CareCardAdditionalInfoTableViewCell. Following is the code to add the glyph.

```
- (void)prepareView {
    if (!_completionStatusView) {
        _completionStatusView = [[OCKRingView alloc] initWithFrame:CGRectMake(0, 0, RingViewSize, RingViewSize)
                                          useSmallRing:NO];
        [self addSubview:_completionStatusView];
    }
    
    if (!_titleLabel) {
        _titleLabel = [OCKLabel new];
        _titleLabel.numberOfLines = 4;
        _titleLabel.textStyle = UIFontTextStyleHeadline;
        [self addSubview:_titleLabel];

    }
    
    [self setUpConstraints];
}
```

**Comment by srinathtm-apple** [comment]
Closing this out as it's no longer applicable due to the CareKit 2.0 beta update.
