### ISSUE TITLE
OCKSymptomTrackerTableViewCell title and text labels have ambiguous layout

### ISSUE THREAD

**Issue by king7532** [carekit-apple/CareKit#256]
See this screen shot from the OCKSample app in the Xcode UI debugger:
<img width="1718" alt="screenshot" src="https://user-images.githubusercontent.com/11179766/38558469-3fc8a844-3c9e-11e8-8e00-b389f118115f.png">

This can cause the either the title or text label's heigh to collapse:
<img width="527" alt="screen shot 2018-04-10 at 9 07 06 am" src="https://user-images.githubusercontent.com/11179766/38558578-93016dac-3c9e-11e8-8d31-51d033d9c78d.png">

**Comment by king7532** [comment]
What do you think about using a `UIStackView` to encapsulate the 4 `OCKLabel`s? I would be happy to submit a pull request.

**Comment by srinathtm-apple** [comment]
@king7532 - this should no longer be an issue in the latest CareKit 2.0 beta..
