### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [carekit-apple/CareKit#257]
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by akshay-yadav-apple** [comment]
Hey @jbeguna04,
Sorry for the delay in responding. 
We appreciate and welcome all the PRs we get for CareKit and ResearchKit, and merge them after careful review process. please feel free to propose the new logo design in form of a PR.

**Comment by jbeguna04** [comment]
Greetings @akshay-yadav-apple, I would like to ask more information about the project so that I can have more idea about the logo/icon output. Thanks in advance
