### ISSUE TITLE
Unable to properly subclass OCKChart

### ISSUE THREAD

**Issue by moppymopperson** [carekit-apple/CareKit#258]
I've created a minimum reproducible example of this bug on [this branch](https://github.com/moppymopperson/CareKit/tree/chart-bug).

It seems that there is something wrong with the `OCKChart` class that prevents it from working properly when subclassed in Swift, but I haven't been able to pin down what it is yet.

Code compiles correctly, but when it comes time to display the subclass of `OCKChart` as an `OCKInsightItem` in an insights view controller, some really outlandish behavior occurs -- all of the properties of the class are deinitialized. 

- Optional values that were previously set all become nil. 
- Non optional values, including Swift `let` constants, shows as `<uninitialized>` in the debugger
- Types that have a default value in Objective-C are reset to that value (e.g. ints all become 0)
- Types that don't have a default value and are not optional cause a bad access exception and crash the app

The example I've provided sets the background color to green, but if you place breakpoint at line 29 and enter `po self.color` you'll see that the color has been reset to nil. 

I am guessing that this bug does not affect Objective-C apps, but I have not confirmed that.

<img width="1129" alt="debugger" src="https://user-images.githubusercontent.com/22581112/42279579-2b220a2e-7fd9-11e8-85d5-152b4a1b9b5a.png">

**Comment by dukemike** [comment]
@moppymopperson I think your problem may be tied to not having implemented `copy:withZone`. For example,

```swift
    override func copy(with zone: NSZone? = nil) -> Any {
        let chart: CustomChartInsight = super.copy(with: zone) as! CustomChartInsight
        chart.color = self.color
        chart.width = self.width
        chart.height = self.height
        return chart
    }
```

In your `chartView` you may need to also set the constraints, but YMMV. For example,

```swift
chart.translatesAutoresizingMaskIntoConstraints = false
chart.heightAnchor.constraint(equalToConstant: self.height).isActive = true
```

**Comment by moppymopperson** [comment]
@dukemike That seems to be the issue, thanks! I didn't realize that the object was getting copied!
