### ISSUE TITLE
Pull Request Proposal: Days without data shown as 100% complete

### ISSUE THREAD

**Issue by moppymopperson** [carekit-apple/CareKit#259]
When there is no data available for a day it is shown as 100% complete. I never thought this was a big deal as it's at most only visible for the first week, but we've gotten a lot of feedback from different users and stakeholders that they want it to show 0% when no data is available.

Currently I've responded to this by using a fork of CareKit in which I've hardcoded it to use 0% when no data is available. Upstream is hardcoded to use 100%.

I'm proposing adding a boolean variable to the `OCKWeekViewController` that lets users choose the behavior they want, with the default option being the same as it is now to preserve compatibility. The new variable would have to be exposed through a property on `OCKCareContentsViewController` and the older `OCKCareCardViewController` since the week view controller is not a public member of either.

I'm happy to put these changes together and submit a PR, but I'd like to know if there is interest before I put in the time.

**Comment by ninoguba** [comment]
This is definitely useful.  We too modify the CK code to set this to 0 as well when there are no activities for that particular day.  Look forward to your PR.

**Comment by erik-apple** [comment]
CareKit 2.0 addresses this request by means of a new `OCKAdherenceAggregator` enum. It comes with several options out of the box, and you can also pass it a closure to define your own custom adherence computation rules.
