### ISSUE TITLE
GitHub project improvements

### ISSUE THREAD

**Issue by bgannin** [carekit-apple/CareKit#260]
A maintainer could do the following for CareKit:

- "topics" which are project related keywords (healthcare, health, ios, framework, carekit, patient, objective-c, swift)
- disable projects since it is a currently unused section
- choose the appropriate license type (BSD variant I believe) to provide filtering/clarity

For reference, Swift's GH project disabled these features already and has a visible license type. They haven't added any topics yet though 🔖

Matches ResearchKit issue #1195.

**Comment by erik-apple** [comment]
Thanks for the suggestions!
We have added topics, began using projects, and Github recognizes our license file now.
