### ISSUE TITLE
OCKBarChart does not render correctly with more than 6 days

### ISSUE THREAD

**Issue by boscoybarra** [carekit-apple/CareKit#266]
With more than 6 days of information OCKBarChart does not render correctly the bar chart, information is superimposed. Data loads incorrectly like the images attached. The issue occurs both in HTML and PDF formats.

In my opinion, it needs padding between bars, dates, and labels when loading more than 6 days because information superimposes on top of each other. The more days the worst. Please find the results attached as images.

The way to reproduce this is to complete Assessments or CarePlan data and see how the chart superimpose information when you add bar information with more than 6 days. You will have to change the date on your device and time travel to the future while completing assessments or activities day by day until you reach more than 6 days. I'm using an iPhone 5SE with iOS 11.4.1.

Thank you

![data superimpose with ockbarchart](https://user-images.githubusercontent.com/2598374/50695119-0e915b00-103c-11e9-9bbf-382274494aa5.png)

![other example](https://user-images.githubusercontent.com/2598374/50695633-8318c980-103d-11e9-8f23-b9fcb916bfa9.png)

**Comment by erik-apple** [comment]
We're going to close this issue now that CareKit 2.0 has been released. We are no longer providing bug fixes for version 1.2.

**Comment by boscoybarra** [comment]
> We're going to close this issue now that CareKit 2.0 has been released. We are no longer providing bug fixes for version 1.2.

@erik-apple , thank you. Is this issue fixed on CareKit 2.0 ? Thank you!

**Comment by erik-apple** [comment]
Yep, the new bar charts support much denser data.
You should still be careful not to overwhelm your users with data though!

![Bar Chart Test](https://user-images.githubusercontent.com/51723116/72189763-94b05200-33b2-11ea-8e52-a11e0f0dc0c4.png)

**Comment by fedetop01** [comment]
Hi @erik-apple, I'm using the latest version of carekit, and I was trying to achieve the same thing you did here, displaying chart over an entire month. However, I'm struggling to accomplish the retrieve the data for an entire month, whereas the monthly view of the graph I did it extending the class that before displayed only the weekly chart. Could you help me understand how you set up such a monthly view, and especially how you retrieved the data?

**Comment by gavirawson-apple** [comment]
@fedetop01 Check out the conversation [here](https://github.com/carekit-apple/CareKit/issues/685), there are some helpful tips for setting up a monthly calendar.
