### ISSUE TITLE
OCKCareCardViewController does not display multiple activities with the same name

### ISSUE THREAD

**Issue by djknowles** [carekit-apple/CareKit#268]
If two OCKCarePlanActivity objects contain different identifiers but the same title only the last created activity is displayed on the OCKCareCardViewController list view. It is however counted when showing the summary care overview percent complete.

To reproduce this issue add two OCKCarePlanActivity objects with different identifiers but with the same name.
Display the OCKCareCardViewController.
Only the last activity is displayed.

**Comment by srinathtm-apple** [comment]
@djknowles - this should no longer be an issue in latest CareKit 2.0 beta
