### ISSUE TITLE
OCKCareCardViewController details for an activity does not display long title/description properly

### ISSUE THREAD

**Issue by djknowles** [carekit-apple/CareKit#269]
When the user is on the OCKCareCardViewController they can click on the > to show the detailed information for an activity. This screen displays the activity title, description and instructions.

The activity detail screen does not scroll the header part of the activity. For this reason if the title and description are long enough the information runs off the end of the screen. As this part of the screen does not scroll the user is unable to see all the information and the instructions field is completely missing.

**Comment by erik-apple** [comment]
I'm going to close this out. CareKit 2.0 has been released and is the officially supported version now. We're happy to help answer questions about previous versions when we can, but we're no longer administering bug fixes to previous versions.
