### ISSUE TITLE
Proposal: Swift Package Manager Support

### ISSUE THREAD

**Issue by amelnychuck** [carekit-apple/CareKit#271]
With Apple's integration of Swift Package Manager as a first party dependency manager in Xcode, as well as the removal of the Cocoapods `CareKit.podspec` file within the project (and an overall shift away from Carthage/Cocoapods as the preferred dependency management tools on iOS to first party offerings,) adding support for Swift Package manager is a high priority feature to increase adoption of the framework among projects with an iOS 13 deployment target written in Swift.

It makes sense to create separate package definitions (Package.swift files) for `CareKitStore` and `CareKitUI` to allow for the independent importing of each framework into a project, as emphasized in this years WWDC talk.

In addition, the README.md documentation should be updated to reflect Swift Package Manager as the preferred method of importing each package, with short instructions on importing the framework using Xcode 11's built in `Add Package Dependency...` feature. The existing import instructions should remain in the readme as an alternative to using Swift Package Manager, however a note should be included that Swift Package Manager is the preferred method of including the project as a dependency, in line with modern development best practices.

Would love to know your thoughts on the above, and I'm happy to help in contributing this change back into the community time allowing. 👍 Fantastic work on the 2.0 beta and I can't wait to start using it in my future projects.

**Comment by srinathtm-apple** [comment]
@amelnychuck - totally agree, we were planning on getting this in before pushing to stable in September. However, if you do find the time to get this configured, please let us know by commenting on this thread and we will hold off from our side and wait for your PR to kick in :D 

And please feel free to provide further feedback as to start looking into CareKit 2.0

**Comment by king7532** [comment]
@amelnychuck I was thinking exactly the same thing yesterday. Thank you very much for writing it up so nicely! 👏

@srinathtm-apple may I suggest creating a new branch, something like `IntegrateSwiftPackageManager` where we can contribute our pull requests to get advice and feedback? I'll admit, this will be the first time I'm creating a Swift Package, as opposed to consuming them. Thank you for CareKite 2.0!

**Comment by srinathtm-apple** [comment]
@king7532 - Absolutely, I have created a new branch called integrateSPM, feel free to submit your PRs to that branch!

**Comment by erik-apple** [comment]
I believe one of the hurdles that we'll need to overcome is that SPM doesn't currently support bundling of resources. There are a number of assets that need to be included in CareKitUI (images) and CareKitStore (the core data schema) that can't currently be packaged with SPM.

This limitation is acknowledged at 29:52 in the WWDC session [Creating Swift Packages](https://developer.apple.com/videos/play/wwdc2019/410/). There is an open proposal and ongoing discussion about this on the Swift forums as well, which can be found here --> [SPM Static Dependencies Proposal](https://forums.swift.org/t/spm-static-dependencies/10152)

**Comment by erik-apple** [comment]
Good news:
We're working a way to make this happen, and we've got a proposal in place.

The gist of the proposed solution is to replace all resource files in CareKit with alternatives that can be created entirely in code. The blocking assets right now are the image assets used by CareKitUI and the database schema used by CareKitStore. 

We intend to remove the assets by replacing them with the new SF Symbols announced at WWDC
https://developer.apple.com/videos/play/wwdc2019/206/

Similarly, we will replace the managed object model created from CareKitStore's schema file with one explicitly specified in code.

**Support for SPM will be added in 3 incremental phases.**
1. Replace CareKitUI assets with SF Symbols
2. Replace CareKitStore schema with a programmatic managed object model
3. Creating the SPM Package.swift file and migrating the dependencies of the example projects

The new CareKit SPM package will include 3 products that will be linked as static libraries: CareKitUI, CareKitStore, and CareKit. The sample and catalog app will not be available through SPM - they will still require you to clone the repo.

Finally, I want to note that this will be a *temporary* solution until SPM gains support for resource files. Once resources can be included, the CareKitStore schema file will likely be returned to its present form.

**Comment by erik-apple** [comment]
Support for SPM has landed on master!
The integration with the Xcode 11 beta works very nicely, and we hope this will make adopting CareKit just that much easier.
