### ISSUE TITLE
CareKitStore security

### ISSUE THREAD

**Issue by raheelsayeed** [carekit-apple/CareKit#275]
The 2.0 version looks great. Wondering if there are extra security features added (passcode protections)? Sometimes we need to protect stored patient data, and limit access to other device users.

**Comment by erik-apple** [comment]
We're glad to hear that you're interested in trying out CareKit 2.0!

We do not presently provide any utilities for passcode protection as part of the CareKit framework, as we feel it is more of a generic app level feature than a CareKit framework feature.

That said, we are interested in learning more about your use case and how CareKit could support it. Would you be able to share any details about what you're building?

**Supplementary info on CareKit security:**
If you use the `OCKStore` that we provide, the data will be fully encrypted on disk anytime that the device is locked. Similarly, the store's data will be automatically excluded from iCloud backup. The code that enables these security measures can be found here.

https://github.com/carekit-apple/CareKit/blob/a82e11bcd369d3408c3cdc37d68a0aadd28a3ba6/CareKitStore/CareKitStore/CoreData/OCKStore.swift#L103-L117

**Comment by chrisnowak** [comment]
ResearchKit offers some standard passcode entry stuff:
http://researchkit.org/docs/docs/Passcode/Passcode.html
