### ISSUE TITLE
Why is the sample app building with 70 errors?? 

### ISSUE THREAD

**Issue by izloop** [carekit-apple/CareKit#276]
I have installed the files as directed however, I am running into a ludicrous amount of errors - any help on reducing these and getting the app running so that I can start building with CareKit? 

Best,

<img width="1440" alt="Screen Shot 2019-06-18 at 6 49 33 PM" src="https://user-images.githubusercontent.com/38543275/59703654-a48bfd00-91fa-11e9-9114-31b3e974e5cf.png">

**Comment by erik-apple** [comment]
Based on the warnings I see there, it seems like you may not be using Xcode 11. Are you on the latest beta?

**Comment by izloop** [comment]
Thanks, I have updated Xcode, however, I still have 4 issues! :S 


<img width="529" alt="Screen Shot 2019-06-18 at 8 03 48 PM" src="https://user-images.githubusercontent.com/38543275/59708059-4d8b2580-9204-11e9-8d36-47604f4bcf51.png">

**Comment by king7532** [comment]
@izloop Try to clean the build folder, on the menu bar `Product -> Clean Build Folder`. Then try to build and go again.

**Comment by izloop** [comment]
@king7532 - Thanks, it worked well!

**Comment by erik-apple** [comment]
@king7532 Thanks for jumping in!

@izloop The issue you encountered is a known bug in the Xcode 11 beta -- it is not related to CareKit. If you ever get build errors regarding UITableViewDiffableDataSource, just clean and build again. It should be fixed in a future release.
