### ISSUE TITLE
Replace CareKitUI image assets with SF Symbols

### ISSUE THREAD

**Issue by erik-apple** [carekit-apple/CareKit#280]
This issue is part of a larger proposal to add support for Swift Package Manager (#271).

Presently all the images used in CareKitUI are stored as binary images in the frameworks assets folder. SPM does not yet support resource files, so all CareKitUI resources will be replaced with suitably equivalent SF Symbols.

**Comment by Inukinator** [comment]
Hey Erik, I just learned about CareKit and seems like a cool project!
Is there anything I can help with or does the "Merge" mean this has already been done? I haven't worked much in other Open Source projects, but would love to begin, and help where I can!

// B

**Comment by erik-apple** [comment]
@BastianInuk We're glad to hear that you're interested in CareKit and would like to contribute! 
This issue is being closed because it's just been completed through PR #283.

A great place to start contributing would be by helping us dream up and implement a new way to display charts (#285) and contacts (#286). You can get started just by commenting on those issues with some ideas. 

If you're ever looking for something you can chip in on, looking in our proposals project is a great place to start.
https://github.com/carekit-apple/CareKit/projects/2

You can check to see if there are any open proposals for you to work on, or you can create your own proposal and then shepherd it through the adoption process.
