### ISSUE TITLE
Custom aggregator for daily adherence target values

### ISSUE THREAD

**Issue by pgallastegui** [carekit-apple/CareKit#287]
For the daily adherence driven by the schedule of an OCKTask, at the moment it seems it only considers the count of targetValues passed in the OCKScheduleElement constructor. Is there a way (or are there plans for a way) to make that respond to a custom aggregator?

The application would be that, just as you can use a custom aggregator for the charts (in the case of having to meet a specific amount specified in the logs, like 50oz of water) this aggregator would help determine if you've met a specific sum of values in OCKOutcomes.

**Comment by erik-apple** [comment]
We agree that this is something we should support soon.

Are you looking at using this feature to change how the completion rings are filled, or are you using `fetchAdherence` in another context altogether?

Have you looked at the `fetchInsights` method? It only acts on one task at a time, but if used in a dispatch group, I believe it could do what you want.

**Comment by pgallastegui** [comment]
The main objective was to change how the completion rings are filled. For the purpose of one of the Tasks in our app, it doesn't matter how many times you do something, it matters what the sum of all the values logged is (in this case, how much milk has been drank).

For this, we would also need the capability of specifying the value and units of the Outcome logged (which is addressed in issue #288).

**Comment by erik-apple** [comment]
There is a change in the pipeline to utilize `OCKEventAggregator` in more places, and one of those will likely be in `fetchAdherence`.

That will get you half way to where you want to be, but we'll also need to expose a way for you to change how the values in the completion rings are computed. I think this is something that will come up in a lot of use cases, so I'd be interested in hearing how you would like to have that exposed to you.

For example, we could setup a datasource and you could set yourself to that, or we could provide a method on `OCKDailyPageViewController` that you can override to implement custom logic. I'm sure there are other possibilities too. Any preferences on that front?

**Comment by pgallastegui** [comment]
I think a datasource would work well. Would that replace the schedule-driven adherence or work in tandem with it?

**Comment by erik-apple** [comment]
This is all very much exploratory, but I think a good approach would be for the existing behavior to be the default, but to allow for customization by setting yourself as the data source. By setting yourself as the datasource, you would effectively be opting out of the default schedule-driven adherence.

**Comment by pgallastegui** [comment]
Sounds excellent. Thank you!

**Comment by erik-apple** [comment]
@pgallastegui We've just merged a PR that gives you the ability to do specify a custom aggregator. We ended up going with a model where you pass a custom aggregator into the view controller.

When you instantiate an `OCKDailyPageViewController`, you can now pass a second, optional, aggregator parameter. 

https://github.com/carekit-apple/CareKit/blob/ad27028f332cf3fdfa26823fd3d5df14262e758f/CareKit/CareKit/Lists/Controller/OCKDailyPageViewController.swift#L101

The aggregator itself now has a `custom` case in which you can provide a closure that operates on an array of events and returns an adherence value. 

https://github.com/carekit-apple/CareKit/blob/ad27028f332cf3fdfa26823fd3d5df14262e758f/CareKitStore/CareKitStore/OCKAdherenceAggregator.swift#L33-L43

These two changes should make it possible to accomplish your goal!
