### ISSUE TITLE
Custom log view

### ISSUE THREAD

**Issue by pgallastegui** [carekit-apple/CareKit#288]
It would be great to have a chance to provide a custom view/view controller to handle the input of data for a specific log (units, value, notes, kind) without having to create the entire stack of classes related to this purpose. For example, to be able to create a complex view that replaces the single log button to enter more complex data:

<img width="396" alt="59870470-3f9be880-935b-11e9-9836-427765b0a854" src="https://user-images.githubusercontent.com/6440438/60131715-a2c4bb00-975f-11e9-8dd7-0a7a9a27625d.png">

We created that demo by using a datasource protocol in a Synchronized Task View Controller that took a custom view. The datasource would then be used to pass an array of OCKOutcomes to be stored. CareKit would then take care of all the rest: updating the logs list, any charts, and the daily adherence progress based on the values passed.

**Comment by gavirawson-apple** [comment]
That is a great idea! This will allow for some great customizability, so we have decided to start working on an implementation. Stay tuned for a related PR!

**Comment by pgallastegui** [comment]
Excellent! We have a rough implementation of this idea (used when taking that screenshot) in the repo for the PR #274 

Thank you!

**Comment by gavirawson-apple** [comment]
@pgallastegui Check out my comment on the PR you submitted. We have implemented this functionality in the latest updates!
