### ISSUE TITLE
V2 Adherence and Local Notifications

### ISSUE THREAD

**Issue by jwaddilove** [carekit-apple/CareKit#292]
I would like to enhance my V2 app to use the local notification system. Initially I want to use a badge on the app icon to show the number of doses (tasks) that remain for today. Optionally I would like to be able to fire a local notification as a Banner to alert the user that it is time to peform a task.

Are there any obvious hooks in the V2 code to help build such functionality? I'm wondering if I should be adopting Swift Combine framework for this sort of design.

Thank you for any advice

**Comment by gavirawson-apple** [comment]
These sound like great features to have handy! There are many routes to implement these features, and combine is certainly one of them.

While we don't provide public hooks into our combine implementation, you can make use of some of our internal hooks on your personal fork. Check out:
[https://github.com/carekit-apple/CareKit/blob/master/CareKit/CareKit/Synchronized%20View%20Controllers/Synchronization/OCKSynchronizedStoreManager%2BPublishers.swift](url)

This file contains a bunch of publishers that will allow you to listen for changes to data in the database. In your case, you can listen for changes to specific tasks and events. Here is some sample code to get you started, given you have a reference to a `storeManager` object:

```swift
let subscription = storeManager.publisher(forEvent: event, categories: [.add, .update, .delete]).sink { [weak self] newValue in
    // This block will be called any time the event is added, updated, or deleted from the database.
    // This is a good place to register notifications that are reliant on this event. 
}
```

**Comment by erik-apple** [comment]
It depends a lot on your project requirements, but another viable place to perform this work might be in the AppDelegate. Going through the app delegate wouldn't be as close to real time as Gavi's suggestion, but it comes with the bonus of only touching already public methods.

Each time your app enters the foreground or goes into the background, you could grab a reference to your store and use `store.fetchTasks` and `store.fetchInsights` in combination to determine how many events occur today, and how many are done already. You can set the badge based on those values.

Similarly, you could use these opportunities to reschedule local notifications. Depending on your needs, you might also consider setting up regular background sessions in which you could query the store to schedule notifications for the upcoming day/week/month

**Comment by erik-apple** [comment]
I'm going to go ahead and close this due to inactivity. If you still have questions, feel free to reopen this issue and restart the conversation!
