### ISSUE TITLE
Obtaining events by group identifier 

### ISSUE THREAD

**Issue by desmondbaldwin** [carekit-apple/CareKit#293]
Will Carekit2 give us the ability to easily obtain all the events for activities having the same group identifier?

**Comment by gavirawson-apple** [comment]
This is a great feature to have, and is definitely on our to-do list. We also plan on providing functionality for limiting and ordering the results returned by a query. 

We will update this issue with a PR when it is ready!

**Comment by gavirawson-apple** [comment]
We have just submitted a PR that opens up the ability to query events for an activity with a specific group identifier. Here is some sample code that will help get you started:

```swift
// Create the task query
let taskQuery = OCKTaskQuery(for: Date())
taskQuery.groupIdentifiers = ["task-identifier"]

// Query for all tasks with the specified group identifier
storeManager.store.fetchTasks(nil, query: taskQuery, queue: .main, completion: { result in
    switch result {
    case .failure: break
    case .success(let tasks):

        // Fetch events for each of the tasks
        let eventQuery = OCKEventQuery(for: Date())
        for task in tasks {
            storeManager.store.fetchEvents(taskIdentifier: task.identifier, query: eventQuery, queue: .main, completion: { result in
                switch result {
                case .failure: break
                case .success(let events):
                    // handle events here
                    break
                }
            }
        }
    }
}
```

We have also added the ability to sort and limit results returned by a query. For more details see:
 https://github.com/carekit-apple/CareKit/blob/master/CareKitStore/CareKitStore/Structs/OCKTaskQuery.swift.

Hopefully that solves your issue!
