### ISSUE TITLE
No valid SSL cert on carekit.org

### ISSUE THREAD

**Issue by heptal** [carekit-apple/CareKit#297]
![8A2C92F7-63A6-408F-A6F3-7481F569A07C](https://user-images.githubusercontent.com/1241082/60685195-59fbb900-9e67-11e9-89f7-88b92066e992.png)
![F952F72B-005E-4045-8744-5590DBE78935](https://user-images.githubusercontent.com/1241082/60685196-59fbb900-9e67-11e9-83d6-d71463e81d7d.png)

**Comment by erik-apple** [comment]
Thanks for the heads up. We'll look into the issue!

**Comment by erik-apple** [comment]
The previous carekit.org site now redirects to Apple's new researchandcare.org website, which has a valid SSL certificate.
