### ISSUE TITLE
stable branch is missing some crucial fixes

### ISSUE THREAD

**Issue by gubikmic** [carekit-apple/CareKit#304]
Hi, I just started looking into CareKit and ResearchKit and it's pretty awesome what they offer out of the box! 🙏🏻

I think the stable branch should point to 20bd47bda72155ffd45ada291edc668682a17652 though, i.e. the latest commit before 2.0 starts.

Otherwise a simple app using the `OCKCareCardViewController` like below crashes.

```
import UIKit
import CareKit

class ViewController: UINavigationController {
    lazy var carePlanStore: OCKCarePlanStore = {
        let fileManager = FileManager.default
        let urls = fileManager.urls(for: .documentDirectory, in: .userDomainMask)
        let url = urls[0].appendingPathComponent("carePlanStore")
        
        if !fileManager.fileExists(atPath: url.path) {
            try! fileManager.createDirectory(at: url, withIntermediateDirectories: true, attributes: nil)
        }
        
        return OCKCarePlanStore(persistenceDirectoryURL: url)
    }()
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let careCard = OCKCareCardViewController(carePlanStore: carePlanStore)
        careCard.title = "Care"
        pushViewController(careCard, animated: true)
    }
}
```

**Comment by erik-apple** [comment]
Thanks for raising this issue. 

We've created a new tagged release, version 1.2.2 that includes all changes between 1.2.1 and 2.0-beta.

**Comment by urbanintell** [comment]
Does OCKCareCardViewController still exist or has it been replaced by OCKDailyPageViewController?

**Comment by erik-apple** [comment]
You are correct, it has been replaced by in CareKit 2.0 by `OCKDailyPageViewController` and `OCKDailyTasksPageViewController`.
