### ISSUE TITLE
CareKit V2 OCKCartesianChartViewController and a custom eventAggregator

### ISSUE THREAD

**Issue by olger** [carekit-apple/CareKit#309]
Hello CareKit team, 

I a building a simple Care App for people to see how they are doing with their chronic illness.

I've taken the V2 WWDC 2019 video and material in the tickets over here to build integration between CareKit and ResearchKit and that seems to work fine. 

Now every day there is a question (score 1 to 10) how the patient feels about the day. This Score is stored as a an Outcome with Outcome value connected to the task. 

With that information I'd like to create a OCKCartesianChartViewController that shows the given values in a scatter plot 
`let insightsCard = OCKCartesianChartViewController(
                            storeManager: self.storeManager,
                            dataSeriesConfigurations: [dayScoreDataSeries],
                            date: date,
                            plotType: .scatter)`

Now in order to do so, It seems that I need a custom aggregator in the dataseries configuration:
`let dayScoreDataSeries = OCKCartesianChartViewController<OCKStore>.DataSeriesConfiguration(
                            taskIdentifier: "dayscore",
                            legendTitle: "Day Score",
                            gradientStartColor: #colorLiteral(red: 0.7372466922, green: 0.7372466922, blue: 0.7372466922, alpha: 1),
                            gradientEndColor: #colorLiteral(red: 0.7372466922, green: 0.7372466922, blue: 0.7372466922, alpha: 1),
                            markerSize: 10,
                            eventAggregator: OCKEventAggregator<OCKStore.Event>.custom({ events in Double(12.0) })
                            )`

The eventAggregator closure is not called it seems, any advice where to look to see how this is called from the framework ?

Kind regards, 

Olger

**Comment by olger** [comment]
It needs something like this:

`diff --git a/CareKit/CareKit/Synchronized View Controllers/Chart/OCKCartesianChartViewController.swift b/CareKit/CareKit/Synchronized View Controllers/Chart/OCKCartesianChartViewController.swift
index 524ba8c..8f90dc2 100644
--- a/CareKit/CareKit/Synchronized View Controllers/Chart/OCKCartesianChartViewController.swift
+++ b/CareKit/CareKit/Synchronized View Controllers/Chart/OCKCartesianChartViewController.swift
@@ -171,10 +171,11 @@ open class OCKCartesianChartViewController<Store: OCKStoreProtocol>: UIViewContr
         var allDataSeries = [OCKDataSeries]()
         var errors = [Error]()
         let group = DispatchGroup()
-        let insightsQuery = OCKInsightQuery<Store.Event>(from: eventQuery)
         for config in dataSeriesConfigurations {
             group.enter()
-            storeManager.store.fetchInsights(forTask: config.taskIdentifier, query: insightsQuery) { result in
+            var aggregatedQuery = OCKInsightQuery<Store.Event>(from: eventQuery)
+            aggregatedQuery.aggregator = config.aggregator
+            storeManager.store.fetchInsights(forTask: config.taskIdentifier, query: aggregatedQuery) { result in
                 switch result {
                 case .failure(let error): errors.append(error)
                 case .success(let values):`


I've tested with this change and see the scale changing but it is not drawing any dots (or a bar if you change the config), so it is not completely fixed with the above change.

**Comment by gavirawson-apple** [comment]
Thanks for spotting this issue Olger! We're currently working on pushing new features and bug fixes very soon, and will include this patch. 

We're glad you've been able to achieve your custom use case with the framework.Keep us updated on your progress and always let us know if you spot any more issues or areas in which the framework can improve!

**Comment by olger** [comment]
Thanks @gavirawson-apple for your support, looking forward to the changes
