### ISSUE TITLE
Locale / Region bug with V2

### ISSUE THREAD

**Issue by olger** [carekit-apple/CareKit#310]
Hi CareKit team, 

I have an issue that my dailyPage view and the OCKCartesianChartViewController are not in sync with regards to the selected dates. 
I found https://github.com/carekit-apple/CareKit/issues/277mentioning changing the region and when I change the region to US, all data is presented as expected. (my region is set the The Netherlands)

The screen below shows the screen with the The Netherlands  region:
![Simulator Screen Shot - iPhone Xʀ - 2019-09-03 at 08 41 30](https://user-images.githubusercontent.com/734430/64149941-7f854e80-ce27-11e9-9d56-ae38499ca3e6.png)

The screen below shows te screen with the United States region:
![Simulator Screen Shot - iPhone Xʀ - 2019-09-03 at 08 47 16](https://user-images.githubusercontent.com/734430/64150018-9f1c7700-ce27-11e9-9773-ff2eeb27f568.png)

**Comment by erik-apple** [comment]
Thanks for reporting this! We were able to reproduce it on our end, and will begin working on a fix.

**Comment by olger** [comment]
Thanks @erik-apple for the support !

**Comment by erik-apple** [comment]
This bug is fixed now! We'll be submitting and merging the PR in the near future. Sit tight!

**Comment by erik-apple** [comment]
A fix for this bug has just been merged as part of #313. 
Please let us know if you find any other bugs or usability concerns!
