### ISSUE TITLE
Non US Locales does not work in Sample app

### ISSUE THREAD

**Issue by advatar** [carekit-apple/CareKit#312]
If you run the sample app and click on f.i Nausea log the correct day is not being updated. It is easy to replicate.

1. Make a fresh clone
2. In the Settings in simulator set Locale to f.i Sweden.
3. Launch Sample and test
4. Change back to US

Has this been noticed before? Any patch or workaround?

**Comment by erik-apple** [comment]
Thanks for notifying us!

Yes, this is a known bug and has already been fixed.
https://github.com/carekit-apple/CareKit/issues/310

We will be pushing the fix shortly!

**Comment by erik-apple** [comment]
This has bug has been fixed by #313.
