### ISSUE TITLE
CareKit fails EXC_BAD_ACCESS on iOS 13.2

### ISSUE THREAD

**Issue by jwaddilove** [carekit-apple/CareKit#318]
Hi, I'm still working away at my CareKit app. Having upgraded to the newest beta of iOS 13.2 my app, and the OCKSample, both fail in `OCKDailyPageViewController`, the failing method is 

`init(storeManager: OCKSynchronizedStoreManager<Store>, adherenceAggregator: OCKAdherenceAggregator<Store.Event> = .countOutcomes)` 

line:
`self.calendarWeekPageViewController = .init(storeManager: storeManager, aggregator: adherenceAggregator)` 

It's being invoked from the AppDelegate set up.

Any suggestions? is the current version of CareKit comparable with the 13.2Beta.

As always, thank you for your help... Jonathan

**Comment by erik-apple** [comment]
Thanks for filing a bug! We were able to reproduce this in the Sample app and just pushed a fix for it.

Can you confirm that the fix worked for you?
If it does, you can just close out this issue.

If it does not, please tell us how you set up your project (Swift Package Manager or embedded frameworks).

**Comment by jwaddilove** [comment]
Hmm, downloaded V2 zip to desktop and then tried to build & run on iPhone 11Pro running 13.2.

Can't get the OCKSample to compile (probably my mistake), see attached

I see that you switched to use a non-SPM version of the frameworks, does that mean I shouldn't use the SPM version in my own code.

As always, many thanks Jonathan


[Build OCKSample_2019-10-07T19-19-50.txt](https://github.com/carekit-apple/CareKit/files/3698887/Build.OCKSample_2019-10-07T19-19-50.txt)

**Comment by jwaddilove** [comment]
OK, Have successfully run the OCKSample using the embedded CareKit frameworks.

I'm closing this but would like to understand if/when I can use SPM versions of CareKit

Many thanks   Jonathan
