### ISSUE TITLE
Crush in OCKCareCardWeekView

### ISSUE THREAD

**Issue by Koshub** [carekit-apple/CareKit#32]
Values array provided for `setValues` with items count more than 7 will crush app by accessing index out of bounds of `_heartButtons`. See [here](https://github.com/carekit-apple/CareKit/blob/master/CareKit/CareCard/OCKCareCardWeekView.m#L168)

**Comment by umerkhan-apple** [comment]
@Koshub `OCKCareCardWeekView` is a project level file. It is not meant to be used directly. `OCKCareCardViewController` will always provide an array of 7 items for `setValues` in `OCKCareCardWeekView`. Is there a scenario where this is not the case?

**Comment by Koshub** [comment]
@umerkhan-apple Well, no. I just report about the probably possible issue. Sorry if it is called like really possible bug. You are right - the selected level of parameters checking is not at that place. But I think it should be escaped there. Thank you for response.

**Comment by umerkhan-apple** [comment]
@Koshub Sounds good. Let's do an assertion check to make sure there are exactly 7 values provided. Would you like to do the PR?

**Comment by Koshub** [comment]
@umerkhan-apple Assertion check - will be enough I think. Sorry, currently don't have time for PR.
