### ISSUE TITLE
Question: how to clear all database?

### ISSUE THREAD

**Issue by tmbiOS** [carekit-apple/CareKit#327]
Hello! How to clear the database? (delete all entities).

**Comment by gavirawson-apple** [comment]
One way to delete the entire store is to delete and re-install your app. Another route you can consider is to use the in-memory option when creating your store for the first time:

```swift
let store = OCKStore(name: "My-Store", type: .inMemory)
```

An in-memory store will live as long as the app is alive in memory, which is often useful for the development process.

**Comment by gavirawson-apple** [comment]
Closing out this issue, but feel free to open it back up if you have additional questions!
