### ISSUE TITLE
Contact "monogram" described as optional but nonoptional in initializer

### ISSUE THREAD

**Issue by p2** [carekit-apple/CareKit#33]
Sorry to be nitpicking, this is a minor point. The description of `monogram` for an `OCKContact` says:

> If a monogram is not provided, the image will be used for the contact

I think the opposite is happening: if there is no image, the monogram will be used. Hence it always has to be provided as a fallback.

**Comment by matteocrippa** [comment]
@p2 monogram is going to be refactored, you can see something in PR

**Comment by p2** [comment]
Will be resolved with #21
