### ISSUE TITLE
OCKSchedule for common use cases

### ISSUE THREAD

**Issue by hnunes46** [carekit-apple/CareKit#335]
Hello everyone, do you think if is useful to extend de OCKSchedule with a simple method to create schedule for common use cases.

For example:
 - On wake up
 - Breakfast
 - Lunch
 - Dinner 
 - Before sleep

Without the need of creating manually that common use cases.

`let breakfastSchedule = OCKSchedule.dailyAtTime(hour: 8, minutes: 0, start: Date(), end: nil, text: "Breakfast")`

Example of the common method:

`let breakfastSchedule = OCKSchedule.dailyAtTime(.breakfast, start: Date(), end: nil)`

Tell me if it is useful

Cheers everyone

**Comment by erik-apple** [comment]
We considered doing this while we were developing the scheduling API. At one point we had bunch of convenience methods, including...

```swift

// Breakfast, lunch, and dinner, every day
let meals = OCKSchedule.mealTimes(start: Date(), end: nil)

// Morning every day
let morning = OCKSchedule.mornings(start: Date(), end: nil)

// Precisely at noon
let noon = OCKScheduleElement.dailyAtTime(.noon, start: Date(), end: nil)
```

Eventually we decided not to include these are part of the API for two key reasons:

**1. It seems difficult to establish agreement on time windows**

For events like "breakfast". Is it 6AM to 9AM? Is it 8AM - 11AM? Different people probably want it to mean different things, and it may even vary by on region or culture.

**2. It is easy enough for developers to add these methods themselves**

Each app will probably have its own unique use cases, and it only takes a few lines of code create these extensions. 

All that to say, we agree that these additions would be very useful, and we encourage you to add them in the context of your app! We don't have any plans to add new helpers into the framework itself.

You can add as many of these helpers as you want by extending `OCKSchedule` with static functions.

```swift
extension OCKSchedule {

    static func breakfast(start: Date, end: Date? = nil) -> OCKSchedule {
        return OCKSchedule.dailyAtTime(hour: 6, minutes: 0, start: start, end: end, duration: .hours(4))
    }
}
```
