### ISSUE TITLE
Integrating with ResearchKit

### ISSUE THREAD

**Issue by scdi** [carekit-apple/CareKit#339]
Great Work giving an example on how to integrate CareKit to implement a ResearchKit survey task. That is incredibly helpful.  Thank you so much. 

Issues: 
The "mark completed" does not seem to persist. So if one closes the app and reopens it, it looks like the survey needs to be done (again). 

The header view did not update with the data from the survey. I think that was the intent with the synchronized example. The header view remained blank. That could be from changes on my part. 

Still: The README content provided is great. Thank you so much.

**Comment by erik-apple** [comment]
Thanks for opening an issue!

I just tried to reproduce your problem using the code recently added to the README, but everything worked as expected. I was able to replicate.

If you can share your project with us, or better yet, create a new minimal project in which this bug manifests, we can help you further.

Regarding the persistence problem, you might want to check what type of store you're using. It sounds like  you may have your store set to `.inMemory` instead of `.onDisk`.

I'm not sure about the header synchronization part. If you can provide some more detail or code we can look at, we might be able to help more.

```swift
/// Initialize a new store by specifying its name and store type. Store's with conflicting names and types must not be created.
///
/// - Parameters:
///   - name: A unique name for the store. It will be used for the filename if stored on disk.
///   - type: The type of store to be used.
public init(name: String, type: OCKCoreDataStoreType = .onDisk)

/// An enumerator specifying the type of stores that may be chosen.
public enum OCKCoreDataStoreType {

    /// An in memory store runs in RAM. It is very fast, but cannot support large datasets and is not persisted between app launches.
    /// Its primary use case is for testing.
    case inMemory

    /// A store that persists data to disk. This option should be in almost all cases.
    case onDisk
}
```

**Comment by scdi** [comment]
Thank you so much. Here is the code added to the OCKSample app

Codes for SurveyViewController.swift and SurveyViewSynchronizer.swift are added as provided.

In SceneDelegate -->
class SceneDelegate: UIResponder, UIWindowSceneDelegate 
    var window: UIWindow?

    // Manages synchronization of a CoreData store
    lazy var manager: OCKSynchronizedStoreManager = {
        let store = OCKStore(name:  "SampleAppStore", type: .onDisk)
       store.populateSampleData()
        let manager = OCKSynchronizedStoreManager(wrapping: store)
        return manager
    }()
....
in CareViewController.swift -->
let surveyCard = SurveyViewController(
                    viewSynchronizer: SurveyViewSynchronizer(),
                    taskID: "survey",
                    eventQuery: OCKEventQuery(for: Date()),
                    storeManager: self.storeManager)

                listViewController.appendViewController(surveyCard, animated: true)

![Screen Shot 2019-12-20 at 3 26 07 AM](https://user-images.githubusercontent.com/13545391/71241075-b26d2880-22d8-11ea-87d1-2b0af795225a.png)
![Screen Shot 2019-12-20 at 3 25 38 AM](https://user-images.githubusercontent.com/13545391/71241076-b26d2880-22d8-11ea-92f4-05775f2a82ea.png)

Thank you.

**Comment by scdi** [comment]
I forgot to mention that the first screenshot is taken after rebooting the app. "Completed" statement seen on the second screenshot is not persisted. And the text in the header remains as "Rate your pain ..."

**Comment by erik-apple** [comment]
I may have figured this out! Is it possible that you've forgotten to add a survey task into your store?

```swift
func populateSampleData() {
    // ...
    let survey = OCKTask(id: "survey", title: "Survey!", carePlanID: nil, schedule: schedule)
    addTasks([nausea, doxylamine, kegels, survey], callbackQueue: .main, completion: nil)
    // ...
}
```

When you do this, make sure you also delete the app and reinstall it, otherwise the call to `addTasks` could fail because the nausea, doxylamine, and kegels tasks already exist in the store.

**Comment by scdi** [comment]
Thank you so much. I will give that a try.

**Comment by scdi** [comment]
Oh yes. You were right. That solved the problem.

**Comment by erik-apple** [comment]
Great! Glad we got it sorted out!

**Comment by danielet** [comment]
Hello,

I recently followed the issue and I tried the same thing adding to OCKSample the example presented in the README for adding a ResearchKit survey.

However, I got this error when I hit the button Start Survey:
`unrecognized selector sent to instance`

My guess is that I am doing something wrong in the subclass part, and those are my steps:

- created a new swift file where I copied and past the class from the README
`class SurveyViewController: OCKInstructionsTaskViewController, ORKTaskViewControllerDelegate {`
- in AppDelegate add 
```
lazy var synchronizedStoreManager: OCKSynchronizedStoreManager = {
        let store = OCKStore(name: "testStore")  
        store.populateSampleData()
        let manager = OCKSynchronizedStoreManager(wrapping: store)
        return manager
    }()
```
- in CareViewController added
```
let surveyCard = SurveyViewController(
                    viewSynchronizer: SurveyViewSynchronizer(),
                    taskID: "survey",
                    eventQuery: OCKEventQuery(for: Date()),
                    storeManager: self.storeManager)
                    listViewController.appendViewController(surveyCard, animated: false)
```

- and finally in func populateSampleData added
```
let testSurvey = OCKTask(id: "survey",
                                 title: "Take Survey",
                                 carePlanID: nil,
                                 schedule: schedule)
tasks.append(testSurvey)
```

**Comment by cbaker6** [comment]
Hey @danielet! Inside of your TaskViewController, lets say you subclassed, `OCKInstructionsTaskViewController' you need to override the following method:

``` 
override func taskView(_ taskView: UIView & OCKTaskDisplayable, didCompleteEvent isComplete: Bool, at indexPath: IndexPath, sender: Any?) {
     
        // 2a. If the task was marked incomplete, fall back on the super class's default behavior or deleting the outcome.
        if !isComplete {
            super.taskView(taskView, didCompleteEvent: isComplete, at: indexPath, sender: sender)
            return
        }
```

Then in the same method you can do something like:

```
// Show an `ORKTaskViewController` for the assessment's task.
        let taskViewController = ORKTaskViewController(task: selectedAssessment.researchKitTask(), taskRun: nil)
        taskViewController.discardable = true
        taskViewController.delegate = self
        taskViewController.modalPresentationStyle = .fullScreen
        
        let titleLabel = UILabel()
        titleLabel.adjustsFontSizeToFitWidth = true
        titleLabel.font = UIFont(name: "Avenir", size: 18)
        titleLabel.textColor = .black
        titleLabel.text = "Survey Title"
        taskViewController.navigationItem.titleView = titleLabel
        
        present(taskViewController, animated: true, completion: nil)
```

Make sure you become a delegate of your RKTask view:

``` 
extension SurveyInstructionsViewController: ORKTaskViewControllerDelegate{
    
    func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?) {
        
        defer {
            taskViewController.dismiss(animated: true, completion: nil)
        }
               
        // Make sure the reason the task controller finished is that it was completed.
        guard reason == .completed else {

            return
            
        }
```

Hit me up, we should catch up!
