### ISSUE TITLE
Assigning 0 contacts to connect view controller forces its view to load

### ISSUE THREAD

**Issue by p2** [carekit-apple/CareKit#34]
Another nitpick: Assinging a zero-length array to the contacts view controller's `contacts` property calls the `prepareHeaderView` method, which will call `[self.view addSubview:]`, forcing the view to load. An `isViewLoaded` call would be great.

```
let controller = OCKConnectViewController(coder: ...)
...
controller.contacts = []    // <--
```

**Comment by akshay-yadav-apple** [comment]
Hey @p2 ,

Thank you for bringing this to our attention. 
Would you like to do the PR?
