### ISSUE TITLE
Carekit Documentation

### ISSUE THREAD

**Issue by atcg0101** [carekit-apple/CareKit#340]
Looks like there's a new website for carekit/researchkit https://www.researchandcare.org/, it looks great!

However, it looks like the old carekit.org website is down along with the detailed documentation. We're unable to find documentation on the Insights feature (we looked on https://developer.apple.com/documentation/carekit), does anyone know where we can find information relating to this feature? We saw this page (https://developer.apple.com/design/human-interface-guidelines/carekit/app-architecture/reports/) but it lacks the detail we need.

**Comment by gavirawson-apple** [comment]
With the new CareKit 2.0 release, we no longer support documentation for the previous version of CareKit. What feature are you looking to build with Insights? You might want to check out the new charts in 2.0.

**Comment by maurovz** [comment]
@gavirawson-apple We need to create a report and export it to a PDF. I guess we might be able to use charts to create the report, but how can we export it?

**Comment by gavirawson-apple** [comment]
I see, unfortunately we do not support exporting charts to a PDF in 1.0. To do so in CareKit 1.2.1:

```swift
// Create the document elements.
let subheadElement = OCKDocumentElementSubtitle(subtitle: "Weekly Summary")
let chartElement = OCKDocumentElementChart(chart: chart)
let paragraphElement = OCKDocumentElementParagraph(content: "Lorem ipsum dolor sit amet...")

// Create a document from the elements.
let document = OCKDocument(title: "Weekly Update", elements: [subheadElement, chartElement, paragraphElement])
document.pageHeader = "\(dateString) update for \(userName)"

// Create a PDF of the document.
document.createPDFDataWithCompletion { (PDFData, errorOrNil) in
    if let error = errorOrNil {
        // perform proper error checking here...
        fatalError(error.localizedDescription)
    }

    // Do something with the PDF data here...
}
```

**Comment by atcg0101** [comment]
Thanks @gavirawson-apple ! We'll probably figure out how to accomplish this some other way to accomplish this as we would like to continue using 2.0
