### ISSUE TITLE
Use of OCKHealthKitLinkage

### ISSUE THREAD

**Issue by drdavec** [carekit-apple/CareKit#345]
I discovered OCKHealthKitLinkage and it appears that there is support for tasks that pull outcomes from HealthKit, e.g. a task to walk 8000 steps per day.  However, I cannot find any public var/func to set this linkage on an OCKTask.  Is this available for use, and can you provide an example?

Thank you!
   Dave C

**Comment by erik-apple** [comment]
There aren't any APIs that consume `OCKHealthKitLinkage` yet!
