### ISSUE TITLE
CareKit Bridge Documentation

### ISSUE THREAD

**Issue by lucaspozzi** [carekit-apple/CareKit#348]
Is there any documentation around how to incorporate CareKit bridge in an existing project to a custom cloud backend, perhaps Firebase? The WWDC session only talked about third-party vendors and did not link to any resources that describe how to build a custom solution.

**Comment by erik-apple** [comment]
The paradigm has changed pretty significantly with the release of CareKit 2.0.
Take a look at the answers given in #322 and then let us know if you have any specific questions that haven't been answered there.

**Comment by lucaspozzi** [comment]
Thank you #322 was helpful. I'm still having issues with the implementation, specially on my SwiftUI sandbox.

**Comment by gavirawson-apple** [comment]
Is there a specific issue that you are running into?

**Comment by lucaspozzi** [comment]
Starting from the OCKSample app, how do you customize the image inside the OCKDetailView instructions?
The card is an OCKChecklistTaskViewController, but I don't seem to be able to set the image for the instructions.
Doing .asset on the OCKTask doesn't seem to work.

**Comment by lucaspozzi** [comment]
Backend integration I will save for last

**Comment by gavirawson-apple** [comment]
> Starting from the OCKSample app, how do you customize the image inside the OCKDetailView instructions?

You can accomplish this by subclassing a task view controller. Suppose you would like to present an `OCKChecklistTaskViewController`:

```swift
// Define your custom view controller
class CustomChecklistTaskViewController: OCKChecklistTaskViewController {

    // Override the method that sets up the details view.
    override func didSelectTaskView(_ taskView: UIView & OCKTaskDisplayable, eventIndexPath: IndexPath) {
        do {
            // Create the view controller.
            let detailsViewController = try controller.initiateDetailsViewController(forIndexPath: eventIndexPath)

            // Customize the image.
            detailsViewController.detailView.imageView.image = UIImage(systemName: "pencil")
            detailsViewController.detailView.imageView.contentMode = .scaleAspectFit
            detailsViewController.detailView.imageView.tintColor = .white

            // Present the view controller.
            let navigationController = UINavigationController(rootViewController: detailsViewController)
            present(navigationController, animated: true, completion: nil)
        } catch {
            delegate?.taskViewController(self, didEncounterError: error)
        }
    }
}
```

Wherever you are presenting this view controller, make sure it is your new custom type.

**Comment by lucaspozzi** [comment]
That's great. Thank you much.
