### ISSUE TITLE
Crash and bugs after deleting "performUnversionedUpdate"

### ISSUE THREAD

**Issue by tmbiOS** [carekit-apple/CareKit#349]
Hi there!
After deleting property `updatesCreateNewVersions` and functionality `performUnversionedUpdate` there are the crash and bugs with updating items: (You can test by adding `updateTask(nausea)` after creating first items) 
1. Bug: I tested only `store.fetchContacts`. We need to filter contacts with $0.nextVersionID == nil to fetch last version of contacts. On the `OCKContactsListViewController` we need to filter contacts too to avoid duplicates.
2. Crash:
```
OCKEventStore.
private func fetchEvents(task: Task, query: OCKEventQuery, previousEvents: [Event],
                             callbackQueue: DispatchQueue = .main, completion: @escaping (Result<[Event], OCKStoreError>) -> Void)
let nextInterval = DateInterval(start: nextStartDate, end: nextEndDate)
```
`Fatal error: Reverse intervals are not allowed: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_overlay_Foundation_Sim/swiftlang-1100.2.280/swift/stdlib/public/Darwin/Foundation/DateInterval.swift, line 58`

So, the crash when creating `nextInterval` of the tasks.

**Comment by erik-apple** [comment]
Thanks for reporting this. I've been able to reproduce this on our end. We'll begin looking into it!

**Comment by erik-apple** [comment]
A fix for the bug you helped us find has just landed on master. Thanks for making us aware of it!
