### ISSUE TITLE
HealthKit integration with swift UI

### ISSUE THREAD

**Issue by miguelc95** [carekit-apple/CareKit#352]
Hi! I've done what you mentioned in the documentation about subclassing OCKInstructionsTaskViewController, but as I am using Swift UI I cannot make it a UIViewController representable since I am "redeclarating" SurveyViewController, do you know of a way of integrating a ResearchKit survey using swift ui?

I am using the SurveyViewController shown in the HealthKit integration example and it is showing as a regular OCKInstructionsTaskViewController, I am guessing it is because it isn't a UIViewRepresentable

<img width="382" alt="Screen Shot 2020-01-26 at 17 34 43" src="https://user-images.githubusercontent.com/15070387/73143643-42ce2400-4062-11ea-8419-1652f0919ea2.png">
<img width="493" alt="Screen Shot 2020-01-26 at 17 35 20" src="https://user-images.githubusercontent.com/15070387/73143644-42ce2400-4062-11ea-87ce-e5a3057f19e4.png">

**Comment by miguelc95** [comment]
I am sorry, now I am able to display my card, but for some reason when clicking the complete button this: "exception 'NSInvalidArgumentException', reason: '-[Panacea.AppDelegate window]: unrecognized selector sent to instance" error is shown, I am trying to display the pain survey when the button is clicked, and after it enter the didCompleteEvent method it crashes.

<img width="670" alt="Screen Shot 2020-01-27 at 9 37 55" src="https://user-images.githubusercontent.com/15070387/73188601-bf0b4a80-40e8-11ea-9723-52cf446ff091.png">
<img width="869" alt="Screen Shot 2020-01-27 at 9 38 02" src="https://user-images.githubusercontent.com/15070387/73188615-c29ed180-40e8-11ea-8f00-969b14ef6d76.png">

Do you know why this could be happening?

**Comment by erik-apple** [comment]
It looks like you might be hitting a known bug in ResearchKit. It was recently patched, so if you pull the latest version of ResearchKit your problem should go away!

For reference, see this PR on ResearchKit's repository.
https://github.com/ResearchKit/ResearchKit/pull/1324

**Comment by miguelc95** [comment]
Pulling from the latest version fixed the issue! Thanks for the quick response!

**Comment by erik-apple** [comment]
Glad to hear it!
