### ISSUE TITLE
Issue fetching contacts using "tags"

### ISSUE THREAD

**Issue by cbaker6** [carekit-apple/CareKit#356]
I was having issues fetching OCKContacts using tags. When I query for a Contact via a specific tag, the CarePlanStore returns no items found. Querying does work for finding contacts based on ids and other items.

I have replicated my issue using OCKSample here: https://github.com/cbaker6/ocksample. I added a tag, `doctorTag = "Doctor"` to the default contacts in AppDelegate. I then added a simple class, ContactViewController that replaces the current OCKContactsListViewController when "Care Team" is tapped. The ContactViewController has 3 segments: 

- All: displays all contacts
- Doctor: displays the contacts tagged with "Doctor" (this is the one that isn't working)
- Daniels: displays the contacts with id = "jane"

The code I used to query for tags is:

```
    var query = OCKContactQuery()
    query.tags = [doctorTag]
           
    storeManager.store.fetchAnyContacts(query: query, callbackQueue: .main) { [weak self] result in
        guard let self = self else { return }
                switch result {
                case .failure(let error):
                    print(error)
                case .success(let contacts):
                    self.allContacts = contacts
                    self.displayContacts(self.allContacts)
                }
        }
```

I also included a print statement that shows the tags for each contact in the console output for each segment change.

**Comment by erik-apple** [comment]
Thanks for reporting this. We've confirmed that it's a problem with our code and isolated the root cause. We'll start working on a solution, but it won't be ready immediately.

In the meantime, you can work around this issue by querying for all contacts and then manually filtering out the ones that don't match the tags you're interested in. It's less efficient, but it really won't make a difference unless you've got thousands of contacts.

```swift
storeManager.store.fetchAnyContacts(query: .init(), callbackQueue: .main) { result in 
    let contacts = try! result.get()
    let taggedContacts = contacts.filter { $0.tags.contains(doctorTag) }
    // ... The rest of your code
}
```
