### ISSUE TITLE
Crash on iPad when clicking on a log entry for OCKButtonLogTaskViewController

### ISSUE THREAD

**Issue by cbaker6** [carekit-apple/CareKit#358]
For iPad only... After logging an outcome value when using OCKButtonLogTaskViewController. A crash occurs when you attempt to delete the value by tapping on it.

My guess is that the picker view isn't anchored to the time label on this Card since this doesn't occur on the iPhone.

If this is the issue I can look into making the fix and do a pull request.

**Comment by erik-apple** [comment]
We don't officially support iPad, but you're welcome to submit a PR if you're able to isolate the problem!

**Comment by erik-apple** [comment]
I believe this was closed out by #410!
Thanks again for the contribution!
