### ISSUE TITLE
OCKSynchronizedStoreManager not exposing publisher

### ISSUE THREAD

**Issue by dwatson0101** [carekit-apple/CareKit#360]
It appears that you cannot access the publisher for the OCKSyncronizedStoreManager to catch events through combine.  I believe the internal access restriction is preventing the ability to declare a cancellable as described in #322 // suggestion 2 to handle notification events.

```
/// An `OCKSynchronizedStoreManager` wraps any store that conforms to `OCKStore` and provides synchronization to CareKit view
/// controllers by listening in on the store's activity by setting itself as the store delegate.
open class OCKSynchronizedStoreManager:
OCKPatientStoreDelegate, OCKCarePlanStoreDelegate, OCKContactStoreDelegate, OCKTaskStoreDelegate, OCKOutcomeStoreDelegate {

    /// The underlying database.
    public let store: OCKAnyStoreProtocol

    internal lazy var subject = PassthroughSubject<OCKStoreNotification, Never>()
    internal private (set) lazy var notificationPublisher = subject.share()
```

**Comment by gavirawson-apple** [comment]
You're absolutely right, the publisher is currently internal which stops you from hooking into our synchronization system. Given that the publisher will be a necessary tool for creating custom synchronized view controllers, we can work on making it public!

Stay tuned for a PR!
