### ISSUE TITLE
Migration from 1.2 to 2.0

### ISSUE THREAD

**Issue by Hengyu** [carekit-apple/CareKit#362]
Hi, 

Recently I am going to use CareKit 2.0 for an existed project which is using CareKit 1.2. Since CareKit 2.0 is completely rewrite using Swift 5.1 and introduces a lot of new features. There could be many warnings and errors for the project.

As for UI part, we can start using the new components introduced in WWDC 19 session 217. And deprecate old ones. However, speaking of the migration of data store, it looks like the session does not mention this nor can we find them in the docs. I am wondering if there is any best practice/instructions on how to migrate the data store?

Thanks 🙏

**Comment by erik-apple** [comment]
Unfortunately, the 1.2 and 2.0 versions of CareKit's store are not compatible with one another.

If you do need to migrate your data, you'll have to do it manually. You would follow these steps.

1.  Add the core data schema files from CareKit 1.2 into your CareKit 2.0 app
2. Open the old store using `NSPersistContainer` and the schema from CareKit 1.2
3. Create an empty `OCKStore` using CareKit 2.0
4. Using CoreData APIs, fetch each object that you want to migrate from the old store
5. Convert each fetched instance to a CareKit 2.0 type (such as `OCKTask` or `OCKOutcome`)
6. Save the converted values into CareKit 2.0's store

**Comment by Hengyu** [comment]
Hey @erik-apple , thanks for these helpful instructions!
