### ISSUE TITLE
Issues with OCKTaskAnchor

### ISSUE THREAD

**Issue by ishanjainofficial** [carekit-apple/CareKit#364]
The OCKTaskAnchor identifier seems to be unresolved when using the line `let anchor = OCKTaskAnchor.taskIdentifiers(identifiers)`

Is there any newly updated syntax for this with the new updates? If so, what would be a replacement to create such an anchor variable?

**Comment by erik-apple** [comment]
Yes, that was a change that was made during beta, prior to stable release!

The new API is available in the official docs!
https://developer.apple.com/documentation/carekit/ocktaskquery

You can also look for example code in the sample app!
```swift
var query = OCKTaskQuery(for: date)
query.ids = ["doxylamine", "nausea"]
query.excludesTasksWithNoEvents = true

storeManager.store.fetchAnyTasks(query: query, callbackQueue: .main) { result in
   // Handle result here
}
```

The change was made to allow intersecting more constraints when running queries.
