### ISSUE TITLE
RK integration

### ISSUE THREAD

**Issue by scdi** [carekit-apple/CareKit#366]
![4245DBE0-5E39-403D-9F9A-CCC572094018](https://user-images.githubusercontent.com/13545391/74597299-21da6c80-502b-11ea-9bdf-e987129f3397.png)
![4C510A4B-C2F1-46A3-A8C0-9DF4524B3C7C](https://user-
![A9EA6A33-B307-43BA-9E2A-E15CC3A3E1F8](https://user-images.githubusercontent.com/13545391/74597302-23a43000-502b-11ea-8bc1-9e4ee1786da5.png)
images.githubusercontent.com/13545391/74597300-230b9980-502b-11ea-87ba-a281d69ffa2d.png)
![3DE78372-9941-4723-AA7B-CBE8DC91A378](https://user-images.githubusercontent.com/13545391/74597301-230b9980-502b-11ea-9457-bfca2a9dfe34.png)
These picturesustrates what happens Feb 14 day when data is changed for Feb 15.
All the previous day's will take on the value.

**Comment by erik-apple** [comment]
I've seen this happen before! I have a feeling you might be passing _today's date_ to the task card instead of the _selected date_.

Can you confirm?
```swift
// You might have this...
let surveyCard = SurveyViewController(
    taskID: "survey",
    eventQuery: OCKEventQuery(for: Date()), // Passing in today's date
    storeManager: storeManager)

// You probably want this...
let surveyCard = SurveyViewController(
    taskID: "survey",
    eventQuery: OCKEventQuery(for: date), // Passing in the selected date
    storeManager: storeManager)
```

**Comment by scdi** [comment]
You're a life saver. That is correct.

**Comment by erik-apple** [comment]
Happy to help!
