### ISSUE TITLE
Displaying a Certain Date on DailyPageViewController

### ISSUE THREAD

**Issue by tommysarni** [carekit-apple/CareKit#370]
I am currently trying to create deep links that when the user clicks the link, it will open up a certain date on the DailyPageViewController. I see now in the source that it requires access to the CalendarWeekPageViewController, however that variable is private. Is there any workaround for this? Thanks

**Comment by erik-apple** [comment]
Presently I can't think of a convenient work around.

But this seems like something we should support, and not something that should require a workaround. If you'd like to submit a PR, we'll review it and give you guidance.

If you unable to make the change yourself, we'll add this to our to-do list and get around to it at some future date.

**Comment by tommysarni** [comment]
I created support for this but I don't have access to push

**Comment by erik-apple** [comment]
You'll need to fork CareKit, push the changes to your own branch, and then open a PR across forks!

**Comment by erik-apple** [comment]
This was just closed out by #371
