### ISSUE TITLE
[QUESTION] How to fetch outcomes' max date.

### ISSUE THREAD

**Issue by tmbiOS** [carekit-apple/CareKit#377]
Hi there!
I need to update tasks with the outcomes.
How can I calculate the outcomes' max date and send the right task's effective date for successfully updating the task?
In the function `private func confirmUpdateWillNotCauseDataLoss(tasks: [Task])`
the `latestDate` calculates like this:
`let latestDate = allOutcomes.map({ $0.date }).max()`
But this function is private and use core data fetching and I need to send tasks with right effective dates in this function.

**Comment by erik-apple** [comment]
Good question!
You can use the public `fetchOutcomes` method with a query that doesn't specify any date.

```swift
// Let's assume you've already queried the task and have it available
let task: OCKTask 

// Create a query for all outcomes belonging to the version of the task you have on hand
var query = OCKOutcomeQuery()
query.taskIDs = [task.localDatabaseID!]

// Query all outcomes belonging to the task
store.fetchOutcomes(query: query, callbackQueue: .main) { result in 
    let outcomes = try! result.get()

    // Get a calendar event for each outcome from the task's schedule
    let scheduleEvents = outcomes.map { task.schedule.event(forOccurrenceIndex: $0.taskOccurrenceIndex)! }

    // Determine which is the last date
    let maxDate = scheduleEvents.map { $0.start }.max()!
} 
```

You'll want to be a bit more careful with the force unwraps in production code, but that's the gist!

**Comment by tmbiOS** [comment]
> Good question!
> You can use the public `fetchOutcomes` method with a query that doesn't specify any date.
> 
> ```swift
> // Let's assume you've already queried the task and have it available
> let task: OCKTask 
> 
> // Create a query for all outcomes belonging to the version of the task you have on hand
> var query = OCKOutcomeQuery()
> query.taskIDs = [task.localDatabaseID!]
> 
> // Query all outcomes belonging to the task
> store.fetchOutcomes(query: query, callbackQueue: .main) { result in 
>     let outcomes = try! result.get()
> 
>     // Get a calendar event for each outcome from the task's schedule
>     let scheduleEvents = outcomes.map { task.schedule.event(forOccurrenceIndex: $0.taskOccurrenceIndex)! }
> 
>     // Determine which is the last date
>     let maxDate = scheduleEvents.map { $0.start }.max()!
> } 
> ```
> 
> You'll want to be a bit more careful with the force unwraps in production code, but that's the gist!

That's all I need, thanks.
But I think we should change to 
`query.taskIDs = [task.id]` because with `query.taskIDs = [task.localDatabaseID!]` I get zero outcomes
