### ISSUE TITLE
Question: Implementing Multiple Stores

### ISSUE THREAD

**Issue by tommysarni** [carekit-apple/CareKit#378]
I am implementing log in for users, however, there is no way to delete a store. This is an issue in that I don't want multiple stores to be available at once on one device. What is the best way to handle this situation?

**Comment by erik-apple** [comment]
Can you expand on how the stores are related to log in? 

Do you intend to do delete the user's store each time they log out? And if so, what is the plan for once they log back in?

**Comment by tommysarni** [comment]
I am preparing for the potential to have multiple users on the same device and trying want to make sure that I can both easily access their data after switching users and more importantly making sure that each individual data is secure between the different accounts.

**Comment by erik-apple** [comment]
And at what point do you wish to delete the store?

Presently we don't offer an API for deleting the store, but we can add one for you (or you can submit it as a PR!) if your use case reasonably requires it.

**Comment by tommysarni** [comment]
I wish to delete the store every time a person logs out. (I have implemented a single sign on, so it would only occur if someone manually logs out) and that would be great.

**Comment by erik-apple** [comment]
Their data will be irreversibly lost if you delete the store when they log out. Is that the intention?

**Comment by tommysarni** [comment]
Yup exactly. As a side effect of this. Would I still be able to create a store with the same name on the device you think?

**Comment by erik-apple** [comment]
Yes, if the store is deleted, you will be able to reuse names.

**Comment by erik-apple** [comment]
You should have all the tools you need now!
