### ISSUE TITLE
Unable to remove a task properly

### ISSUE THREAD

**Issue by Lukas182** [carekit-apple/CareKit#379]
Hello!

Im just using this framework since 3-4 days ago but Im so interested on it! Awesome work!

I have a problem with the tasks:

When I add a new one lets call it "Paracetamol" , its being added properly and its appear on my dailypageviewcontroller. From my server I send a new data to device telling that the task has been deleted so on device I use store.deleteAnyTask(task) to delete the task that I won't use anymore from now.. its working good till there.. Buuut If I send again the same task to be added on device with the exact same name "Paracetamol" , when I try to add it again to the store Im getting this error:

Invalid value: OCKCDVersionedObject.Type with IDs [[\"Paracetamol\"]] already exists!"

And the task is not being added at all.. So.. is the deleteAnyTask working properly? Need I add something more on the call to remove the task completely? 

Thanks for your time and help!

Regards,

David.

**Comment by Lukas182** [comment]
If you try to update the same registry that the system says that exists...

It throws an error:

Error: updateFailed(reason: "Invalid value: No matching object could be found for id: Paracetamol")

So I don't understand at all :S

**Comment by erik-apple** [comment]
David,

The task store we provide as part of CareKit is a lossless store. When you “delete” a task, it is not actually removed from disk. Instead, it is marked with a flag that prevents it from being returned from queries. This is to ensure that important medical records cannot be permanently lost easily. 

The solution in your case might be to use a different id the second time you want to add the task. 

We haven’t considered a way to “undelete” deleted tasks, but that might be a feature we need to look into as well.

**Comment by cbaker6** [comment]
Not sure if this is the intended way, but I get around this by using unique identifier's for all entities and if I want to do do something like "Paracetamol", I place this is the "tag" for querying. Depending on your use case, I suppose "Paracetamol" can be the groupIdentifier or in userInfo if needed.

**Comment by erik-apple** [comment]
@cbaker6 That sounds like a solid practice to me!

**Comment by Lukas182** [comment]
Thanks for your answers!

@erik-apple ok! there is no problem on create a new one with another 'id' but lets say that in 1 year using the application may we could have around 10.000 "disabled" tasks , so 2 questions:

- How much space it would take on device?
- Is there anyway to recover all the outcomming info from all those "disabled" tasks? Or all are "deleted" and there is no way to see them?

@cbaker6 seems a pretty neat idea , thanks 👍.

**Comment by erik-apple** [comment]
The space it will take up on disk is largely negligible. Tasks task up about 10kb each of disk space, so even 10,000 of them only adds up to 1MB.

Presently the only way permanently remove or "undelete" deleted tasks is to open the SQLite database files in a database browser and manually set the `deletedDate` value back to `nil`. It probably would be worth introducing an API for restoring them and permanently deleting them though.

**Comment by Lukas182** [comment]
Ok great then! Thanks @erik-apple 

I have another ( and hopefully last question for now ) , I have 3 plans for a same patient ( with the same dates -> 24-25-26 February ) . Each plan have 1 task each to take some medicament daily. 

So.. lets suppose I have a dailyPageController that **only** shows the Task from Plan 1, so on days 24-25-26 its appear a GridTaskController to check the schedules.. then If I set on the check from there on day 24th .. the WeekCalendarView ring from  that day appear on a 33% computed when I suppose that should appear 100% , no? If I remove Plans 2 and 3, and keep the 1 ( that was already started ) Im still getting the same results on the circle ring.. The only way to obtain the desired 100% ring is to remove all the task from Plans 2 and 3.

There is no way to have more than 1 plan on a patient and just set one ( ONLY ) that will be counted on rings? 

Thanks again for your patience.

**Comment by erik-apple** [comment]
That's a great question!

I think we need to add a clear way to do what you're asking. In the meantime, I can point you toward a work around.

When you create an `OCKDailyPageViewController`, you have the option to pass in an `OCKAdherenceAggregator`. It defaults to `.compareTargetValues`, but you can also set it to a custom value.

When you use a custom value, you must define a function that operates on an array of events and returns an `OCKAdherence` value.

You can do something like this...

```swift
extension OCKAdherenceAggregator {
    func forCarePlan(_ carePlan: OCKAnyCarePlan) -> OCKAdherenceAggregator {
        .custom { events -> OCKAdherence in
            self.aggregate(events: events.filter { $0.task.belongs(to: carePlan) })
        }
    }
}
```

This extension adds a new function onto all `OCKAdherenceAggregator`s that filters out events not related to the given care plan before computing adherence. 

You would use it like this...

```swift
let plan: OCKCarePlan = //...Assuming you have already have the care plan available

let careViewController = OCKDailyPageViewController(
    storeManager: manager,
    adherenceAggregator: OCKAdherenceAggregator.compareTargetValues.forCarePlan(plan)
)
```

**Comment by Lukas182** [comment]
![carekit_gif](https://user-images.githubusercontent.com/5369988/75710878-a8e34200-5cc5-11ea-9331-ab0e84beb42d.gif)

Cool!! @erik-apple 

I tried what you said there and works way better than before but still the ring not being updated properly .. dunno why.. its keep full and its dont care what buttons I tap on there :S. 

Just did what you said, I took the CarePlan from the Store before create the OCKDailyPageViewController and passed the data con adherenceAggregator to keep the eye only on this one, seems pretty ok cos only appear the filtered tasks but as I said the ring keep hanging out.

I uploaded a gif for you.

**Comment by erik-apple** [comment]
I tested this out on our end, and the sample code I provided works for me.
I suspect that perhaps your task is not being properly associated with its care plan.

Is this how you're tying the care plan and task together?

```swift
let plan = OCKCarePlan(id: "flu", title: "Flue", patientID: nil)

store.addCarePlan(plan) { result in
    switch result {
    case .failure(let error): print(error)
    case .success(let plan):

        let thisMorning = Calendar.current.startOfDay(for: Date())
        let aFewDaysAgo = Calendar.current.date(byAdding: .day, value: -4, to: thisMorning)!
        let beforeBreakfast = Calendar.current.date(byAdding: .hour, value: 8, to: aFewDaysAgo)!
        let afterLunch = Calendar.current.date(byAdding: .hour, value: 14, to: aFewDaysAgo)!

        let schedule = OCKSchedule(composing: [
            OCKScheduleElement(start: beforeBreakfast, end: nil,
                               interval: DateComponents(day: 1)),

            OCKScheduleElement(start: afterLunch, end: nil,
                               interval: DateComponents(day: 2))
        ])

        var doxylamine = OCKTask(id: "doxylamine", title: "Take Doxylamine",
                             carePlanID: nil, schedule: schedule)
        doxylamine.instructions = "Take 25mg of doxylamine when you experience nausea."

        // Associate the task with the care plan
        doxylamine.carePlanID = plan.localDatabaseID!

        store.addTask(doxylamine, callbackQueue: .main, completion: nil)
    }
}
```

**Comment by Lukas182** [comment]
Yeeea! My mistake!

I was adding the tasks properly but I found the problem was that I wasn't taking the proper Plan.. I was doing a for through the fetched query plan and returning the last plan every time without filtering the search by id.. so the functions wasn't returning the good one and the sync's fails between the tapped buttons and the week days :(

Thanks mate!

You can close the issue right now

**Comment by erik-apple** [comment]
Glad you got it figured out!
