### ISSUE TITLE
[UI] OCKListViewController change background color

### ISSUE THREAD

**Issue by Lukas182** [carekit-apple/CareKit#382]
Hello,

It's possible to change the gray background color from the OCKListViewController?

Thanks!

**Comment by gavirawson-apple** [comment]
The best way to set the background color for the `OCKListViewController` is to use CareKit's styling mechanism. The view controller's view derives the background color from a style struct that can be injected into the view. By providing a custom style struct, you can change the background color. 

By going this route, your custom style will pass through the view hierarchy. That means you can easily style an entire view hierarchy by setting the custom style of a root view.

```swift
// Create your custom style struct.
struct CustomStyle: OCKStyler {

    struct CustomColors: OCKColorStyler {

        // The `OCKListViewController`'s view uses this property for the background color.
        let customGroupedBackground: UIColor = .systemBackground
    }

    let color: OCKColorStyler = CustomColors()
}

// You can now apply this style to any view that conforms to `Stylable`, and the style will pass down to any subviews.
let listViewController = OCKListViewController()
var stylableView = (vc.view as? OCKStylable)
stylableView?.customStyle = CustomStyle()
```

**Comment by Lukas182** [comment]
Hey Gavi!

Sorry for the delay on the answer!

That was so helpful!! 

Thanks!
