### ISSUE TITLE
CareKit latest stable 2.0.0 unavailable via Pods

### ISSUE THREAD

**Issue by majeedyaseen** [carekit-apple/CareKit#383]
I am unable to install the latest Carekit 2.0.0 via cocoa pods. When I checked the cocoa pods website I see it has 1.2.1 as its latest there. When will 2.0.0 be available via cocoa pods?

Thanks

**Comment by erik-apple** [comment]
Acute observation! You're right, the newest version on cocoapods is 1.2.1.

We've transitioned from distributing CareKit via cocoapods to using Swift Package Manager and will no longer be updating the podspec file. If you need any help transitioning, we'd be happy to assist!

**Comment by majeedyaseen** [comment]
Thanks a lot but this video [Adopting Swift Packages in Xcode](https://developer.apple.com/videos/play/wwdc2019/408/) helped me and I was able to install it via Swift Package Manager. Pretty easier than Pods 😄

**Comment by erik-apple** [comment]
Awesome! 
Yep, that's one of the reasons we switched!

Glad you got it worked out!

**Comment by majeedyaseen** [comment]
Just wondering if Apple is forcing to use Swift Package Manager ?

**Comment by erik-apple** [comment]
The CareKit framework team has chosen to drop support for cocoapods in favor of SPM, but Apple does not provide any explicit guidelines.

**Comment by majeedyaseen** [comment]
Understood, but What is wrong in supporting cocoa pods? 
My question is if a person has already dependencies via cocoa pods and adds one supported via SPM like carekit. Will they be able to use both (SPM and cocoapods) simultaneously? as their might be any required dependency which don't have SPM support yet. 

I appreciate your replies but I am a bit curious. Thank you once again

**Comment by erik-apple** [comment]
Yes, cocoapods and SPM can be used together. You can include CareKit with SPM and other dependencies (like ResearchKit!) with cocoapods.

**Comment by majeedyaseen** [comment]
That is great then, Thanks a lot. 
Happy Weekends 😄
