### ISSUE TITLE
Scroll view display different on iPhone 8s Plus vs iPhone XR

### ISSUE THREAD

**Issue by scdi** [carekit-apple/CareKit#385]
![Screen Shot 2020-03-13 at 10 55 54 PM](https://user-images.githubusercontent.com/13545391/76673728-3b18ff00-657e-11ea-9c2d-b1606b93670f.png)
![Screen Shot 2020-03-13 at 10 55 46 PM](https://user-images.githubusercontent.com/13545391/76673729-3eac8600-657e-11ea-932f-0ef6f0881f49.png)
The same code produces the different displays above. 
Here is the code.
let scdPainLocationArray = ["Head", "Neck", "Chest","Back","Abdomen","Stomach", "Sides", "Arms", "Legs", "Pelvis/Waist", "Joints (shoulder, elbow, hip, knee, or other joints)" ]
        
        var choices:[ORKTextChoice] = []
        for item in scdPainLocationArray {
            let textString = item
            let choice =    ORKTextChoice(text: textString, value:textString as NSCoding & NSCopying & NSObjectProtocol)
            choices.append(choice)
        }
        let scdPainLocationAnswerFormat: ORKTextChoiceAnswerFormat = ORKAnswerFormat.choiceAnswerFormat(with: .multipleChoice, textChoices: choices)
        let scdPainLocationStep = ORKQuestionStep(identifier: "scdPainLocation_fs", title: "Pain Location", question: "Where on your body is your pain? Select all that apply, and scroll down for more options", answer: scdPainLocationAnswerFormat)
        scdPainLocationStep.isOptional = false
        steps += [scdPainLocationStep]

**Comment by srinathtm-apple** [comment]
Please update to latest RK master.

**Comment by scdi** [comment]
Thank you. It did fix the problem. Unfortunately, a new display problem is showing. See image below.
![Screen Shot 2020-03-14 at 9 16 21 AM](https://user-images.githubusercontent.com/13545391/76682727-db017780-65d4-11ea-8f9e-c5ba498d75a9.png)
The problem only shows for the first step in the task. The displays in the other steps of the same task are fine.
Here is the code. 
//Pregnancy Status
        let pregnantTextChoices = [     
            ORKTextChoice(text: "Yes", value: "YES" as NSCoding & NSCopying & NSObjectProtocol),
            ORKTextChoice(text: "No", value: "NO" as NSCoding & NSCopying & NSObjectProtocol),
            ORKTextChoice(text: "Not sure", value: "Not sure" as NSCoding & NSCopying & NSObjectProtocol)
        ]

        let pregnantAnswerFormat: ORKTextChoiceAnswerFormat = ORKAnswerFormat.choiceAnswerFormat(with: .singleChoice, textChoices: pregnantTextChoices)
        let pregnantQuestionStep = ORKQuestionStep(identifier: "pregnant_f", title: "Pregnancy Status", question: "Are you pregnant?", answer: pregnantAnswerFormat)
        pregnantQuestionStep.isOptional = false

**Comment by scdi** [comment]
We have a display problem also with Image Choices. Unless one scrolls, the value representing the image selected does not show unless one scrolls. See screenshot below on the iPhone XR. It happens also on other devices (e.g., 8 Plus)
![Screen Shot 2020-03-14 at 11 23 23 AM](https://user-images.githubusercontent.com/13545391/76684969-7818dc00-65e6-11ea-9855-fc25655ddf0f.png)

**Comment by scdi** [comment]
@srinathtm-apple, do you happened to know what was changed in the latest release of RK that fixed the scrolling problem described above. Changing to the latest release fixed the problem but that version will not let me upload to the App Store. So, I am thinking of using a earlier version and just fix the problem in that version for the scrolling.

**Comment by erik-apple** [comment]
@scdi I believe the App Store upload problem has been resolved. If you're still having problems, please re-open this issue on the ResearchKit GitHub page. (Feel free to tag me and link back to this issue)
