### ISSUE TITLE
Invalid Bundle

### ISSUE THREAD

**Issue by scdi** [carekit-apple/CareKit#388]
I keep on getting this error and it seems related to Carekit.
**ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.
Any thoughts?**
I could upload just fine prior to having the CareKit framework up. I use the latest Master version of both CareKit and ResearchKit. The older versions of CareKit and ResearchKit works but I need the newer versions.

**Comment by scdi** [comment]
Please note that the error message comes from the AppStore after the archived file is uploaded successfully. 
"Dear Developer,We identified one or more issues with a recent delivery for your app, ... Please correct the following issues, then upload again. ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

**Comment by gavirawson-apple** [comment]
Are you installing CareKit using SPM or the embedded framework route?

**Comment by gavirawson-apple** [comment]
If you have gone the embedded framework route, this update might fix your issue: https://github.com/carekit-apple/CareKit/pull/389

**Comment by scdi** [comment]
Thank you. The fix worked.
