### ISSUE TITLE
Question: How to get a consistent color scheme

### ISSUE THREAD

**Issue by scdi** [carekit-apple/CareKit#400]
I am not sure why the blue color is still showing. How do we get all the elements of views to be of one color throughout? We would like to have the color purple but the blue button shows until an action is taken such as making a selection.
![Screen Shot 2020-04-01 at 1 14 17 AM](https://user-images.githubusercontent.com/13545391/78101724-6ee58880-73b6-11ea-851c-45e3e5521981.png)
![Screen Shot 2020-04-01 at 1 13 51 AM](https://user-images.githubusercontent.com/13545391/78101725-6ee58880-73b6-11ea-9d8e-5b07d56a0369.png)
![Screen Shot 2020-04-01 at 1 13 40 AM](https://user-images.githubusercontent.com/13545391/78101727-6ee58880-73b6-11ea-9f4e-9d8300ece8e5.png)

**Comment by erik-apple** [comment]
This appears to be a ResearchKit task view controller. If this is a ResearchKit question/bug, I’d recommend opening an issue on that repo.

**Comment by scdi** [comment]
Thank you so much for the prompt response. I think there might be a problem in the integration of RK with CK. The code to change the color scheme is UIView.appearance(whenContainedInInstancesOf: [ORKTaskViewController.self]).tintColor = UIColor.purple in AppDelegate.
It works well in a purely RK sample project (see below).
![Screen Shot 2020-04-01 at 10 14 16 AM](https://user-images.githubusercontent.com/13545391/78147499-97df3b00-7401-11ea-8a39-3245947f07ec.png)

**Comment by erik-apple** [comment]
I've looked into this a bit more and confirmed that it is an RK bug. It reproduces even in projects that don't include CareKit at all. I've alerted the RK team about it, but I would still recommend opening an issue over there as well.

While you're waiting for this to be fixed, I found 2 workarounds that you can use.

1. Set the tint color on your `ORKTaskViewController`s directly.
2. Set the tint color on your window in `SceneDelegate`.

```swift
// 1.
let taskController = ORKTaskViewController(task: myTask, runID: nil)
taskController.delegate = self
taskController.view.tintColor = .purple

// 2.
window = UIWindow(scene: scene as! UIWindowScene)
window!.tintColor = .purple
window!.makeKeyAndVisible()
```

**Comment by scdi** [comment]
Thank you so much. I will add the issue for the ResearchKit team as well. I very much appreciate your help.
