### ISSUE TITLE
Need help to find selected task information OCKTaskViewController

### ISSUE THREAD

**Issue by majidsaleem105** [carekit-apple/CareKit#401]
I was using the earlier version of the Carekit 2.0 and I was using OCKTaskViewControllerDelegate functions to get the selected task information from the following function:

`func didSelect<Store>(taskViewController: OCKTaskViewController<Store>) where Store : OCKStoreProtocol {
        let task = taskViewController.task?.convert()
        lastOCKTaskViewController = (taskViewController as! OCKTaskViewController<OCKStore>)
....
}`

I've taken the latest updates and noticed a lot of new changes in this version.
I've found the alternate function of didselect:
`func didSelectTaskView(_ taskView: UIView & OCKTaskDisplayable, eventIndexPath: IndexPath) `

but I can't find a way to find the selected task in this function.

Can anyone guide me on:
- How can I create an object of OCKTaskViewController in my custom class?
- How can I get the selected task information? 
- I was using `OCKButton` to create the buttons but I'm unable to use these in this version can you please guide me what is the alternative ways to use or replicate my functionalities.

Thanks in advance!

**Comment by gavirawson-apple** [comment]
Hello! Great questions, there were a bunch of changes after our beta release. I can go through each of your questions one by one to offer some guidance.

### Custom Task View Controller

To create a custom view controller for a task view provided by CareKit, you can subclass an already existing view controller. This first snippet assumes you are creating a custom view controller for the `OCKSimpleTaskView`:

```swift
class CustomSimpleTaskViewController: OCKSimpleTaskViewController {

    override func didSelectTaskView(_ taskView: UIView & OCKTaskDisplayable, eventIndexPath: IndexPath) {
        let event = controller.eventFor(indexPath: eventIndexPath)
        let task = event?.task

        // Use the event and corresponding task as needed here...
    }
}
```

You also have the option of creating a custom view that can be synchronized with the store. If you go this route, there are a couple of pieces you will need to build - A view, view synchronizer, controller, and view controller. 

1. **View**: Responsible for displaying the task, and can notify a delegate when certain UI interactions occur.

2. **View Synchronizer**: Responsible for updating the view when the data backing the view changes in the store. 

3. **Controller**: Responsible for manipulating the data in the store.

4. **View Controller**: Ties all of the previous pieces together.

```swift
// 1. Custom view that displays a task.
class CustomTaskView: UIView, OCKTaskDisplayable {

    // Use the delegate to send out notifications when certain events occur in the UI.
    var delegate: OCKTaskViewDelegate?

    // ...
}

// 2. Custom view synchronizer that updates the view when the data in the store changes.
class CustomTaskViewSynchronizer: OCKTaskViewSynchronizerProtocol {

    func makeView() -> CustomTaskView {
        // Initialize the view here...
    }

    func updateView(_ view: CustomTaskView, context: OCKSynchronizationContext<OCKTaskEvents?>) {
        // Update the view with the new data here...
    }
}

// 3. Custom controller responsible for manipulating the data in the store. You can start with subclassing our default controller, and override
// methods as needed.
class CustomTaskController: OCKTaskController {

    // Override methods as needed...
}

// 4. Custom view controller responsible tying all the pieces together. You can start with subclassing our default view controller, and override
// methods as needed.
class CustomTaskViewController: OCKTaskViewController<CustomTaskController, CustomTaskViewSynchronizer> {

    // Override methods as needed...
}
```

That should answer your first two questions, but let me know if I have missed anything.

### Creating a Button

`OCKButton` has been deprecated in favor of `OCKAnimatedButton`, a more lightweight implementation. The new button type allows you to define custom content to display inside of the button's frame. It also allows for animations when the view is highlighted, and can automatically toggle the selected state when the button is tapped.

```swift
class CustomView: UIView {

    override init(frame: CGRect) {
        super.init(frame: frame)

        let buttonContentView = UIView()
        let button = OCKAnimatedButton(contentView: buttonContentView,    // The content to display in the button
                                       highlightOptions: [.defaultFade],  // Animation options for when the button is highlighted
                                       handlesSelection: true)            // If true, the button will automatically toggle the selection state when tapped

        // Add and constrain views here. Note that the `buttonContentView` is already added to the view hierarchy for you, and constrained to fill
        // the button.
    }
}
```

Note that if you do not need the custom functionality provided by an `OCKAnimatedButton`, you can always use a `UIButton`.

**Comment by majidsaleem105** [comment]
Thanks, @gavirawson-apple for your detailed reply and your suggestions. I tried the ways you suggested but it didn't work and I think that's because I'm using the structure from the sample app.

I used the basic structure from your Sample App from `CareViewController.swift` file like 
`class CareViewController: OCKDailyPageViewController, ORKTaskViewControllerDelegate, OCKTaskViewControllerDelegate, OCKTaskViewDelegate {

override func dailyPageViewController(_ dailyPageViewController: OCKDailyPageViewController,
                                          prepare listViewController: OCKListViewController, for date: Date) {
...
}
...
}`

With this structure, I've successfully listed my tasks on the main screen.
![tasks-app-v 1](https://user-images.githubusercontent.com/1611600/78564628-2b67a000-7836-11ea-9735-d571ac17ddb0.png)

- Can you please also suggest how I can hide the displayed time from the bottom of the circle? I don't want to display that time to the patients. It seems that we're forcing the patients to take action at the displayed time.
- I want to `override` the `TaskView Detail` screen so I could customize the information to be displayed and with some additional buttons with customized functionalities.

All this was done with the earlier CareKit version. Please guide me what is the best ways to achieve our goals.

**Comment by majidsaleem105** [comment]
@gavirawson-apple any suggestions please.

**Comment by gavirawson-apple** [comment]
> Can you please also suggest how I can hide the displayed time from the bottom of the circle? I don't want to display that time to the patients. It seems that we're forcing the patients to take action at the displayed time.

Unfortunately this can't be done with a view synchronizer. The best way to accomplish this is to create a custom view controller and map your desired text to each cell. You can then use your custom view controller in place of an `OCKGridTaskViewController`.

```swift
class CustomGridTaskViewController: OCKGridTaskViewController {

    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = super.collectionView(collectionView, cellForItemAt: indexPath) as! OCKGridTaskView.DefaultCellType
        cell.completionButton.label.text = "Custom Text"    // Set your custom text here
        return cell
    }
}
```

> I want to override the TaskView Detail screen so I could customize the information to be displayed and with some additional buttons with customized functionalities.

To customize the details page, you can override a method in the custom view controller that you have just created.

```swift
class CustomGridTaskViewController: OCKGridTaskViewController {

    // ...
  
    override func didSelectTaskView(_ taskView: UIView & OCKTaskDisplayable, eventIndexPath: IndexPath) {
        let viewController = try! controller.initiateDetailsViewController(forIndexPath: eventIndexPath)

        // Customize view here
        viewController.detailView.titleLabel.text = "Custom Title"
        // ...

        present(viewController, animated: true)
    }
}
```

Does that cover all of the issues you are facing?

**Comment by majidsaleem105** [comment]
@gavirawson-apple Thanks for your suggestions. I tried the ways you suggested but it says **"Use of unresolved identifier 'controller' "**

I think I'm missing something that's why I'm sharing my code for your suggestions.

`class CareViewController: OCKDailyPageViewController, OCKTaskViewDelegate, OCKTaskViewControllerDelegate {

    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.rightBarButtonItem =
            UIBarButtonItem(title: "Care Team", style: .plain, target: self,
                            action: #selector(presentContactsListViewController))
    }
    
    func taskViewController<C: OCKTaskControllerProtocol, VS: OCKTaskViewSynchronizerProtocol>(
    _ viewController: OCKTaskViewController<C, VS>, didEncounterError: Error)
    {
        
    }

    @objc private func presentContactsListViewController() {
        let viewController = OCKContactsListViewController(storeManager: storeManager)
        viewController.title = "Care Team"
        viewController.isModalInPresentation = true
        viewController.navigationItem.rightBarButtonItem =
            UIBarButtonItem(title: "Done", style: .plain, target: self,
                            action: #selector(dismissContactsListViewController))

        let navigationController = UINavigationController(rootViewController: viewController)
        present(navigationController, animated: true, completion: nil)
    }

    @objc private func dismissContactsListViewController() {
        dismiss(animated: true, completion: nil)
    }

    // This will be called each time the selected date changes.
    // Use this as an opportunity to rebuild the content shown to the user.
    override func dailyPageViewController(_ dailyPageViewController: OCKDailyPageViewController,
                                          prepare listViewController: OCKListViewController, for date: Date) {

        var query = OCKTaskQuery(for: date)
//        query.ids = identifiers
        query.excludesTasksWithNoEvents = true

        storeManager.store.fetchAnyTasks(query: query, callbackQueue: .main) { result in
            switch result {
            case .failure(let error): print("Error: \(error)")
            case .success(let tasks):

                // Add a non-CareKit view into the list
                let tipTitle = "Benefits of exercising"
                let tipText = "Learn how activity can promote a healthy pregnancy."

                // Only show the tip view on the current date
                if Calendar.current.isDate(date, inSameDayAs: Date()) {
                    let tipView = TipView()
                    tipView.headerView.titleLabel.text = tipTitle
                    tipView.headerView.detailLabel.text = tipText
                    tipView.imageView.image = UIImage(named: "exercise.jpg")
                    listViewController.appendView(tipView, animated: false)
                }

                tasks.forEach { (newTask) in
                    
                    print("ID# \(newTask.groupIdentifier)")
                    if newTask.groupIdentifier == "Informational Activities" {
                                                
                        let newTaskCard = OCKSimpleTaskViewController(task: newTask, eventQuery: .init(for: date), storeManager: self.storeManager)
                        
//                        listViewController.appendViewController(newTaskCard, animated: false)
                    }
                    else {
                        
                        print("Group Identifier: \(String(describing: newTask.groupIdentifier)) : \(newTask.title)")
                        
                        let newTaskCard = OCKGridTaskViewController(task: newTask, eventQuery: .init(for: Date()), storeManager: self.storeManager)

                        newTaskCard.taskView.largeContentImage = UIImage(named: "logo.png")
                        newTaskCard.title = "Majid Saleem Says!"

                        newTaskCard.taskView.collectionView.isUserInteractionEnabled = false
//                        newTaskCard.delegate = self
                        newTaskCard.taskView.delegate = self
                        
                        listViewController.appendViewController(newTaskCard, animated: false)
                    }
                    
                }
            }
        }
    }
    
    func taskView(_ taskView: UIView & OCKTaskDisplayable, didCompleteEvent isComplete: Bool, at indexPath: IndexPath, sender: Any?)
    {
    }
    
    func taskView(_ taskView: UIView & OCKTaskDisplayable, didSelectOutcomeValueAt index: Int, eventIndexPath: IndexPath, sender: Any?)
    {
    }
    func taskView(_ taskView: UIView & OCKTaskDisplayable, didCreateOutcomeValueAt index: Int, eventIndexPath: IndexPath, sender: Any?)
    {
    }
    func didSelectTaskView(_ taskView: UIView & OCKTaskDisplayable, eventIndexPath: IndexPath)
    {
        //let viewController = try! controller.initiateDetailsViewController(forIndexPath: eventIndexPath)
        let event = controller.eventFor(indexPath: eventIndexPath)
        let task = event?.task

    }
    
}`

Thanks for your time.

**Comment by gavirawson-apple** [comment]
The `OCKDailyTasksPageViewController` will be responsible for displaying the `CustomGridTaskViewController `, and should not conform to `OCKTaskViewDelegate`. When you have access to a task that you would like to display, you can create the custom view controller:

```swift
// Create a custom task view controller.
class CustomGridTaskViewController: OCKGridTaskViewController {
    // Define your custom class here...
}

// Create another view controller that is responsible for displaying the custom view controller.
class CareViewController: OCKDailyPageViewController {

    // ...

    override func dailyPageViewController(_ dailyPageViewController: OCKDailyPageViewController, prepare listViewController: OCKListViewController, for date: Date) {

        let identifiers = ["task-id"]
        var query = OCKTaskQuery(for: date)
        query.ids = identifiers
        query.excludesTasksWithNoEvents = true

        storeManager.store.fetchAnyTasks(query: query, callbackQueue: .main) { result in
            switch result {
            case .failure(let error): print("Error: \(error)")
            case .success(let tasks):

               // Instantiate and display the custom view controller here.
                if let task = tasks.first(where: { $0.id == "task-id" }) {
                   let customViewController = CustomGridTaskViewController(task: task, eventQuery: .init(for: date), storeManager: self.storeManager)
                   listViewController.appendViewController(customViewController, animated: false)
                }
            }
        }
    }
}
```

**Comment by majidsaleem105** [comment]
@gavirawson-apple Thank you very much for your help. 
I am able to resolve the problem with your suggestions. 

I'm struggling with the following issues now:
- How can I add/update the Outcome value to `tick` the circle in the card?
- How can I add the adherence to the top circle to show the daily progress? With the customViewController, it's not adding the adherence to the top circle. 
- Is there a way to hide/remove the `imageView` if there is no image to display? It's an `ORKTaskViewControler`. Please see the attached screenshot. 
![empty-image-view](https://user-images.githubusercontent.com/1611600/79002637-4f92ec00-7b6a-11ea-90e2-5bca52a8ad34.png)
- How can I change the background color of the `imageView`? 
- How can I set the alignment of the text/instructions to the center?
- Is there a way to add some custom buttons to this screen? Please see the attached screenshot. 
![detailed-screen](https://user-images.githubusercontent.com/1611600/79002945-fb3c3c00-7b6a-11ea-8e41-867099a12bbd.png)
- Please see the above screenshot that the timer is being displayed twice. Timer with the bigger font is static and the timer with the smaller font counts down. How can I remove one of them? I used the following code to display this timer.

`exerciseStep.shouldShowDefaultTimer = true
 exerciseStep.shouldStartTimerAutomatically = true`

I really appreciate your time and help :).
Thanks,
- Majid S.

**Comment by majidsaleem105** [comment]
@gavirawson-apple any suggestions please.

**Comment by erik-apple** [comment]
There are kind of two parts to your question.

1. How do I get the checkmark to fill in and the adherence ring to fill?
2. How do I setup the ResearchKit view controller the way I want?

We can help you out with the first part, but I'd recommend you open an issue on ResearchKit's GitHub page for the second one. It's a bit out of CareKit's scope.

To get the completion ring to fill up, you need to make sure an outcome is added into the store.
There is example code in our README that you can follow. You can mimic `3b.` and `4b.` from the example we provide.

```swift
// 1. Subclass a task view controller to customize the control flow and present a ResearchKit survey!
class SurveyViewController: OCKInstructionsTaskViewController, ORKTaskViewControllerDelegate {

    // 2. This method is called when the use taps the button!
    override func taskView(_ taskView: UIView & OCKTaskDisplayable, didCompleteEvent isComplete: Bool, at indexPath: IndexPath, sender: Any?) {

        // 2a. If the task was marked incomplete, fall back on the super class's default behavior or deleting the outcome.
        if !isComplete {
            super.taskView(taskView, didCompleteEvent: isComplete, at: indexPath, sender: sender)
            return
        }

        // 2b. If the user attempted to mark the task complete, display a ResearchKit survey.
        let answerFormat = ORKAnswerFormat.scale(withMaximumValue: 10, minimumValue: 1, defaultValue: 5, step: 1, vertical: false,
                                                 maximumValueDescription: "Very painful", minimumValueDescription: "No pain")
        let painStep = ORKQuestionStep(identifier: "pain", title: "Pain Survey", question: "Rate your pain", answer: answerFormat)
        let surveyTask = ORKOrderedTask(identifier: "survey", steps: [painStep])
        let surveyViewController = ORKTaskViewController(task: surveyTask, taskRun: nil)
        surveyViewController.delegate = self

        // 3a. Present the survey to the user
        present(surveyViewController, animated: true, completion: nil)
    }

    // 3b. This method will be called when the user completes the survey.
    func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?) {        
        taskViewController.dismiss(animated: true, completion: nil)
        guard reason == .completed else {
            taskView.completionButton.isSelected = false
            return
        }

        // 4a. Retrieve the result from the ResearchKit survey
        let survey = taskViewController.result.results!.first(where: { $0.identifier == "pain" }) as! ORKStepResult
        let painResult = survey.results!.first as! ORKScaleQuestionResult
        let answer = Int(truncating: painResult.scaleAnswer!)

        // 4b. Save the result into CareKit's store
        controller.appendOutcomeValue(withType: answer, at: IndexPath(item: 0, section: 0), completion: nil)
    }
}
```

**Comment by erik-apple** [comment]
I'm going to close this out since there hasn't been any activity. If you still need more clarification, feel free to re-open the issue and continue our conversation!

**Comment by gavirawson-apple** [comment]
Hi @majidsaleem105, I'll need a bit more context to help - do you mind sharing the class declaration?

**Comment by majidsaleem105** [comment]
Thanks, @gavirawson-apple, for your kind reply.

Here is my class declaration. I defined it in the same way you suggested at the beginning of our conversation. I just wanted the latest versions of the CakeKit and ResearchKit frameworks to upgrade the app code to Swift 6 with support for iOS 16+.

```
class ActivitiesViewController: OCKChecklistTaskViewController, UINavigationControllerDelegate, UIImagePickerControllerDelegate {

         override func taskView(_ taskView: any UIView & OCKTaskDisplayable, didCompleteEvent isComplete: Bool, at indexPath: IndexPath, sender: Any?) {
        
                 super.taskView(taskView, didCompleteEvent: isComplete, at: indexPath, sender: sender)
                 selectedEvent = controller.eventFor(indexPath: indexPath)
                 let totalOccurances = Int( (selectedEvent?.task.schedule.elements.count)! )
        
                .....
       }
       override func didSelectTaskView(_ taskView: UIView & OCKTaskDisplayable, eventIndexPath: IndexPath) {
                let event = controller.eventFor(indexPath: eventIndexPath)
                let task = event?.task
                
               ....
      }

}
```

**Comment by gavirawson-apple** [comment]
Thanks! That clears it up. The API has changed a bit since we last spoke, try this instead:

```swift
class ActivitiesViewController: OCKChecklistTaskViewController, UINavigationControllerDelegate, UIImagePickerControllerDelegate {

    override func taskView(_ taskView: any UIView & OCKTaskDisplayable, didCompleteEvent isComplete: Bool, at indexPath: IndexPath, sender: Any?) {
        super.taskView(taskView, didCompleteEvent: isComplete, at: indexPath, sender: sender)
        let selectedEvent = viewModel[indexPath.section][indexPath.row]
        let totalOccurances = Int( (selectedEvent.task.schedule.elements.count) )
    }

    override func didSelectTaskView(_ taskView: UIView & OCKTaskDisplayable, eventIndexPath: IndexPath) {
        let event = viewModel[eventIndexPath.section][eventIndexPath.row]
        let task = event.task
    }

}
```

**Comment by gavirawson-apple** [comment]
The controller object was removed a while ago. This particular method you're looking for is unfortunately no longer public API, but it was moved to `OCKAnyEventStore+Extension.swift` if you need to copy the code.

**Comment by majidsaleem105** [comment]
@gavirawson-apple,

What should I do if this method is no longer available? 
Where can I find OCKAnyEventStore+Extension.swift file?
Could you provide a sample code demonstrating how to use this function?

Best,
- Majid S.

**Comment by gavirawson-apple** [comment]
```
```

**Comment by gavirawson-apple** [comment]
Here's a copy of that method in `OCKAnyEventStore+Extension.swift`:

```swift
func append(
    outcomeValue: OCKOutcomeValueUnderlyingType,
    event: OCKAnyEvent,
    completion: @escaping OCKResultClosure<OCKAnyOutcome> = { _ in }
) {
    // Retrieve the event from the store so that
    // we modify the outcome for the data at the
    // source of truth.
    fetch(event: event) { result in
        switch result {

        case let .failure(error):
            error.log("Failed to fetch event while appending outcome value to event")
            completion(.failure(error))

        case let .success(event):

            // If an outcome exists, append the new outcome value
            if var outcome = event.outcome {
                outcome.values.append(OCKOutcomeValue(outcomeValue))
                self.updateAnyOutcome(outcome, callbackQueue: .main) { result in
                    result.error?.log("Failed to update outcome while appending outcome value to event")
                    completion(result)
                }

            // Else if one does not exist, save a new outcome
            } else {
                let outcome = OCKOutcome(
                    taskUUID: event.task.uuid,
                    taskOccurrenceIndex: event.scheduleEvent.occurrence,
                    values: [OCKOutcomeValue(outcomeValue)]
                )
                self.addAnyOutcome(outcome, callbackQueue: .main) { result in
                    result.error?.log("Failed to update outcome while appending outcome value to event")
                    completion(result)
                }
            }
        }
    }
}
```
