### ISSUE TITLE
Creating PDF from Patient Charts 

### ISSUE THREAD

**Issue by MihirJoe** [carekit-apple/CareKit#408]
Hello, 

I know there have been a few threads about generating a PDF, but I am a little confused on how to exactly generate a pdf from the bar charts that I have. For reference, I'm using a project similar to the OCKSample, in which I'm utilizing the dailyPageViewController. What's the best way of going about something like this?

Thanks in advance!

**Comment by erik-apple** [comment]
The export to PDF feature was present in CareKit 1.2 but is not in CareKit 2.0
This is a bit confusing, we should probably document it a bit better!

We may add the PDF feature back in if there is enough interest in it. In the meantime, you can use the PDF creation features available natively in iOS.

This is a contrived example, but within the scope of your app, you could add an extension on `UIViewController` that allows *any* view controller to render itself as a PDF. You'd just need to hook up a button or gesture recognizer to trigger such a method.

```swift
extension UIViewController {

    func saveAsPDF(filename: String) {

        let pdfData = NSMutableData()
        UIGraphicsBeginPDFContextToData(pdfData, view.bounds, nil)
        UIGraphicsBeginPDFPage()

        let pdfContext = UIGraphicsGetCurrentContext()!
        view.layer.render(in: pdfContext)
        UIGraphicsEndPDFContext()

        let documentDirectories = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first!
        let filePath = documentDirectories + "/" + filename
        pdfData.write(toFile: filePath, atomically: true)

        print("Wrote PDF file to \(filePath)")
    }
}
```

**Comment by MihirJoe** [comment]
Thanks for the response! Is there any way to get just a section of the view controller to be included in the pdf? What about the whole page? Right now it’s just capturing what my screen was on but I have information below the current frame that I would want to capture as well.

**Comment by erik-apple** [comment]
If you want to capture the whole content, then you need to render the entire contents of the scroll view into the PDF. You can use the `contentSize`, which will typically be much larger than the view's `bounds` for scroll views.

The challenge may be getting access to the scroll view to call this method on.

```swift
extension UIScrollView {
    func saveAsPDF(filename: String) {

        let pdfData = NSMutableData()
        let drawRegion = CGRect(origin: .zero, size: contentSize) // This is the important part
        UIGraphicsBeginPDFContextToData(pdfData, drawRegion, nil)
        UIGraphicsBeginPDFPage()

        let pdfContext = UIGraphicsGetCurrentContext()!
        layer.render(in: pdfContext)
        UIGraphicsEndPDFContext()

        let documentDirectories = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first!
        let filePath = documentDirectories + "/" + filename
        pdfData.write(toFile: filePath, atomically: true)

        print("Wrote PDF file to \(filePath)")
    }
}
```

**Comment by erik-apple** [comment]
We're going to go ahead and close this issue out since there hasn't been any activity recently. Feel free to re-open the issue if you still have any questions!
