### ISSUE TITLE
Displaying tasks on OCKDailyPageViewController input by user

### ISSUE THREAD

**Issue by desmondbaldwin** [carekit-apple/CareKit#411]
Hi,
I created a screen that I use to add new tasks. This input screen is called from my OCKDailyPageViewController. When the data is saved and I dismiss the input screen. I can't get the OCKDailyPageViewController to update with the new data unlessI reload the app or by clicking on the calendar to change the date. What approach should I using to refresh the data without changing the date or reloading?

I've been trying to call "func dailyPageViewController" after dismissing my input screen, I can see where it is querying the data and returning results but no new view controllers are added.

Thanks,
DB

**Comment by erik-apple** [comment]
Can you clarify which method you are calling after your view controller is dismissed?
Where are you looking that you see the data being queried and results being returned?

**Comment by desmondbaldwin** [comment]
I call 
dailyPageViewController(_ dailyPageViewController: OCKDailyPageViewController,
                                          prepare listViewController: OCKListViewController, for date: Date)

the code is similar to what is in OCKSample (CareViewController.swift).
I print to the console to see if it is querying correctly and it does, however it is not appending the view controllers to the stack.

**Comment by desmondbaldwin** [comment]
figured it out...just needed to call viewDidLoad()
