### ISSUE TITLE
HealthKit <-> CareKit Syncing?

### ISSUE THREAD

**Issue by SunburstEnzo** [carekit-apple/CareKit#415]
Hi there! I'm working on a CareKit app at the moment to replace my current HealthKit only app, but I want the new CareKit app to be able to import all the current HealthKit data and also export any new results taken in CareKit, to HealthKit. So as an example, the app could read a typical simple value like Number of Times Fallen data from HealthKit, but also let the user add their own Number of Times Fallen data into the CareKit app, which will then be passed on to HealthKit.

Is there already baked in support for this kind of behaviour? If not, I know how to read the HealthKit data (using HKHealthStore to return [HKSample]) and the opposite, saving a HKCategorySample is easy enough with .save(HKObject), but I have no idea how to do the CareKit side of things, such as getting all the "fake" Number of Times Fallen samples and saving that to HealthKit. I guess there's more questions as to merges and such as well though.

**Comment by erik-apple** [comment]
CareKit doesn't have built in integrations with HealthKit right now, but it's an often requested feature and we're considering it for a future release.

Until then, there are two things you'll need to do to put the rigging place.

#### 1. Save/delete an HKSample when the user interacts with a CareKit card.
This best place to do this is probably in the `taskView(_:didCompleteEvent:at:sender)` method that you can override in subclasses of `OCKTaskViewController`.

```swift
class HealthKitTaskViewController: OCKInstructionsTaskViewController {

    // 1. This method is called when the use completes or deletes an outcome
    override func taskView(_ taskView: UIView & OCKTaskDisplayable, didCompleteEvent isComplete: Bool, at indexPath: IndexPath, sender: Any?) {

        // 2. Call the super class implementation to add/delete from CareKit's store
        super.taskView(taskView, didCompleteEvent: isComplete, at: indexPath, sender: sender)

        // 3. Call into HealthKit to add/delete an HK outcome as well.
        // ...
    }
}
```

#### 2. Update CareKit's store when HKSamples are modified in other apps
If you only want to display HK samples that were added by your app, you can skip this step.
You'll need to use an `HKAnchoredObjectQuery` to subscribe to changes for the sample identifiers you care about (in this case, fall count). Each time a new sample is added or deleted, you'll need to translate the HKSample into an OCKOutcome and add it into your store. 

That will require implementing some logic that when given an HKSample can
1. Determine which `OCKTask` it belongs to
2. Fetch the task and get its schedule
3. Determine based on the schedule and the HKSample's date what the `taskOccurrenceIndex` of the new `OCKOutcome` should be
4. Create a new OCKOutcome with the desired OCKOutcomeValue
5. Save it to your OCKStore

Hint: To protect against adding duplicate samples, you can use the `source` property on `HKSample` to determine if newly added samples were created by your app, or another one.

**Comment by SunburstEnzo** [comment]
Thank you erik-apple for the quick and super in-depth reply!

I think (1) should be pretty straightforward — my only worries are if I’m logging (currently) non-HealthKit linkable task and iOS 14 introduces these into HealthKit natively (example like number of times hit head or something), that I wouldn’t know how to backtrack them currently (not essential for my project but something for me to think about). Maybe an example is if a user temporarily disabled HealthKit access (for good reason though?)
I guess in the future there may be a way to add a HealthKit identifier to a task so it does it automatically?

I’ll definitely look into HKAnchoredObjectQuery, so thanks for letting me know about that! I think that’s going to solve nearly all my current woes. 

I think I was struggling with (2) but now it makes sense to find a HealthKit recording for a given date and find an appropriate task for the same date. I guess there should never be a CareKit “entry” (that is HealthKit compatible) on its own, unless denied HealthKit permissions as mentioned above. 

Is it worth me figuring out how to use OCKHealthKitLinkage? Is what I’ve done (posting on Github) the best place for any future HealthKit discussions? I want to be wary that I don’t spam the Issues section with any ideas. Perhaps once I’m done it would be worthwhile me making a sample project to contribute? Thanks again, that’s really helped my understanding of this process!

**Comment by erik-apple** [comment]
For (1), I would suggest that you take advantage of the `userInfo` dictionary on `OCKOutcome`. Consider adding some metadata into user info to track whether it has been saved into HealthKit or not. You could even save the HKSample's `uuid` into user info so that you know exactly which sample it corresponds to.

```swift
extension OCKOutcome {
    var healthKitUUID: UUID? {
        get { 
             guard let uuidString = userInfo?["uuid"] as? String else { return nil }
             return UUID(uuidString: uuidString)!
        }
        set {
            userInfo = userInfo ?? [:]
            userInfo!["uuid"] = newValue.uuidString
        }
    }
}
``` 

This will allow you iterate through all the outcomes in your store and determine which exist in HealthKit already and which don't. 

> Is it worth me figuring out how to use OCKHealthKitLinkage?

No, that is an internal type that is presently unused. We're going to remove it from the documentation soon because it is a common point of confusion.

> Is what I’ve done (posting on Github) the best place for any future HealthKit discussions?
Yes! GitHub is our preferred communication channel! If you'd like to submit an example or write up a tutorial, that would be fantastic! I'm sure there are lots of people trying to do something similar to what you are!

**Comment by SunburstEnzo** [comment]
Big fan of the healthKitUUID idea, definitely going to try (something like) that.

I feel like I've fallen at the first hurdle; in your first post (1), I'm struggling even to get the task's selected date – all the examples I could find only reference the current date using Date(), which I think does make sense as why would a patient backtrack their date, right? Is this then by design? And if so is there a way to prevent past/future edits? For example if I scroll to yesterday and log a completed task, it would still save the HealthKit version as today instead of yesterday.

I tried to override the OCKInstructionsTaskViewController init so I could pass the date myself but couldn't find a solution. Thanks again!

**Comment by erik-apple** [comment]
Based on your edit it sounds like you've managed to work it out, so I'm going to close this issue. If you have any further questions, feel free to re-open it!
