### ISSUE TITLE
Checklist task gets checked even though VC is overwritten

### ISSUE THREAD

**Issue by macintosh-HD** [carekit-apple/CareKit#417]
I have a question regarding the `OCKChecklistViewController`.
I have overwritten it's delegate method like this:
``` Swift
class ChecklistTaskViewController: OCKTaskViewController<OCKChecklistTaskController, OCKChecklistTaskViewSynchronizer> {
    override func taskView(_ taskView: UIView & OCKTaskDisplayable, didCompleteEvent isComplete: Bool, at indexPath: IndexPath, sender: Any?) {
        guard let _ = try? controller.validatedViewModel(), let event = try? controller.validatedEvent(forIndexPath: indexPath) else {
            return
        }
        
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let practiceView = storyboard.instantiateViewController(withIdentifier: "biofeedbackView") as! BiofeedbackViewController
        
        practiceView.origin = .overview
        practiceView.practiceTimer.updateTimerStartValue(from: "2 min")
        practiceView.sendingTaskId = event.task.id
        practiceView.modalPresentationStyle = .fullScreen
        
        UserDefaults.standard.set(ResonanceController.respirationRates[indexPath.row], forKey: "respirationRate")
        
        show(practiceView, sender: false)
    }
}
```
When I tap on a task in the checklist now I transition to a new VC, but the tasks still gets un-/checked. Where can I prevent the task completion?

**Comment by gavirawson-apple** [comment]
The completion button automatically toggles itself when tapped. That way, there is no lag between the user tapping the button and the reflection of the change of the data in the store. In other words, we assume that when the button is tapped, the event will be successfully completed/uncompleted in the store. If for some reason that does fail, we update the button in the UI. In this overriden method, the event is not actually getting toggled in the store, but the UI still assumes it is getting toggled.

To turn off this functionality, you'll need to turn off the button's auto toggling:

```swift
completionButton.handlesSelection = false
```

The best place to do this is inside of `viewDidLoad`, or in the `makeView` function of the view synchronizer.

Aside, you might want to consider using the `didSelectTaskView` method, which is more suited to presenting a new view controller.

**Comment by macintosh-HD** [comment]
Thank you Gavi for your quick response!
```Swift
class ChecklistTaskViewSynchronizer: OCKChecklistTaskViewSynchronizer {
    
    func updateView(_ view: ChecklistTaskView, context: OCKSynchronizationContext<OCKTaskEvents?>) {
        view.updateWith(events: context.viewModel?.firstEvents, animated: context.animated)
        view.items.forEach {
            $0.handlesSelection = false
        }
    }

    override func makeView() -> OCKChecklistTaskView {
        let view = OCKChecklistTaskView()
        view.items.forEach {
            $0.handlesSelection = false
        }
        return view
    }
}
```
I created my own `ViewSynchronizer` to be able to turn off the `handlesSelection` on all the items in the Checklist.
But that still doesn't do the trick for me, because `items` returns just a copy of the buttons right? So changing the `handlesSelection` property here has no affect.
It looks to me that I have no access to the `checklistItemsStackView` inside of the View and that way I am unable to change the property for every Button that gets added or updated.
Am I guessing right here or is there something I am missing right now?

**Comment by gavirawson-apple** [comment]
The custom view synchronizer looks great to me, good catch moving the code to the `updateView` method. Given that the buttons are classes, `items` will return the correct objects. I'm thinking the issue is that the custom view synchronizer is not being passed to the view controller. Try this out and let me know if it works:

```swift
class CustomChecklistTaskViewSynchronizer: OCKChecklistTaskViewSynchronizer {

    // My mistake earlier, `handlesSelection` needs to be set to `false` only here.
    override func updateView(_ view: OCKChecklistTaskView, context: OCKSynchronizationContext<OCKTaskEvents?>) {
        super.updateView(view, context: context)
        view.items.forEach { $0.handlesSelection = false }
    }
}

class CustomChecklistTaskViewController: OCKChecklistTaskViewController {

    override func taskView(_ taskView: UIView & OCKTaskDisplayable, didCompleteEvent isComplete: Bool, at indexPath: IndexPath, sender: Any?) {
        // custom implementation
    }
}

// Now make sure to pass in the custom view synchronizer when instantiating the view controller
CustomChecklistTaskViewController(
    viewSynchronizer: CustomChecklistTaskViewSynchronizer(),
    taskID: taskID,
    eventQuery: date,
    storeManager: storeManager)
```

**Comment by macintosh-HD** [comment]
Updating the ViewSynchronizer with the code you provided did the trick for me.
Thank you very much for your help! 👍
