### ISSUE TITLE
[Connect] Adding a BarButtonItem to NavigationBar

### ISSUE THREAD

**Issue by SNagra** [carekit-apple/CareKit#42]
Is there is recommended way to add a BarButtonItem to the NavigationBar of the detailed view of the Connect View (after clicking on a contact)?

![1](https://cloud.githubusercontent.com/assets/1387954/15232399/dd6fd816-1855-11e6-90fe-dc32cb75fd5d.jpg)

**Comment by YuanZhu-apple** [comment]
Can you try this?
```
UIBarButtonItem *button = [[UIBarButtonItem alloc] initWithBarButtonSystemItem: UIBarButtonSystemItemDone target:self action:@selector(myAction:)];      
[connectViewController.navigationItem setLeftBarButtonItem:leftBarButton animated:NO];
```

**Comment by SNagra** [comment]
I believe this only adds the Bar Button Item to the Table View that lists all the contacts, I only want the button to show up in the Detail View, as shown in the photo above.

**Comment by YuanZhu-apple** [comment]
@SNagra https://developer.apple.com/library/ios/documentation/UIKit/Reference/UINavigationControllerDelegate_Protocol/index.html#//apple_ref/doc/uid/TP40007662

Implement this delegate to add button when `detail page view controller` is pushed.
