### ISSUE TITLE
Modify OCKSimpleTaskViewController

### ISSUE THREAD

**Issue by desmondbaldwin** [carekit-apple/CareKit#420]
<img width="329" alt="Screen Shot 2020-04-22 at 12 35 08 PM" src="https://user-images.githubusercontent.com/23667035/80015018-c0090980-8496-11ea-8585-ecc7c7bfec8a.png">

Hi,
I would like to add my own custom button in front of the header view text (see picture). How do you recommend  I do that?

Thanks,
DB

**Comment by SunburstEnzo** [comment]
Hi DB, it looks like the OCKSimpleTaskView that sits in OCKSimpleTaskViewController is quite restricted, doesn't look like you can add any views to the horizontalContentStackView (private), but you could subclass OCKView (with protocol OCKTaskDisplayable) and almost copy the way OCKSimpleTaskView works? There could be a better way of doing it (I'm fairly new to CareKit). What is the new button going to do?

**Comment by erik-apple** [comment]
Perhaps something else you could try would be to create the view you want using composition.

Your new view would need to conform to `OCKCardable` and have a horizontal stack view that contains your button and an `OCKSimpleTaskView`. If you use the methods on the cartable protocol to turn on card styling for your outer view and turn off card styling for the simple task view, you'll probably get the effect you want.

**Comment by desmondbaldwin** [comment]
@erik-apple thanks for your help. I've been able to create the below so far but I don't understand how to turn the styling off of the OCKSimpleTaskView and to turn it on on the outer view. I'm trying to figure it out but I'd appreciate any help you can provide.
![Screen Shot 2020-04-28 at 5 16 01 PM](https://user-images.githubusercontent.com/23667035/80543244-1df49000-8974-11ea-80b9-295e1fb8e12b.png)

**Comment by desmondbaldwin** [comment]
Ok figured it out....I created a subclass of OCKSimpleTaskView and removed the styling on that new class. I then used that instead of the original OCKSimpleTaskView for my new view.
![Screen Shot 2020-04-29 at 4 10 34 PM](https://user-images.githubusercontent.com/23667035/80647422-0f6dad80-8a34-11ea-9078-6a62db531855.png)

**Comment by erik-apple** [comment]
Looks good! I'm glad you were able to figure it out!

**Comment by desmondbaldwin** [comment]
Same here, thanks for the guidance.

**Comment by SunburstEnzo** [comment]
Just to be clear, you’re laying out the headerView, completionButton, and your custom view yourself instead of using horizontalContentStackView right?

**Comment by desmondbaldwin** [comment]
I used a horizontal OCKStackView, added a UIButton and OCKSImpleTaskView as arrangedsubviews to the stack view. I could have used the components of the OCKSImpleTaskView to build this also.
