### ISSUE TITLE
Questions about OCKDailyPageViewController and OCKInstructionsTaskViewController

### ISSUE THREAD

**Issue by athanasiospap** [carekit-apple/CareKit#422]
Hello, 

I am building an app with a `OCKDailyPageViewController` in the main tab with four `OCKInstructionsTaskViewControllers` as tasks, but when I append them to the listViewController, they get sorted randomly. Is there any way to sort these view controllers with a specific order? I tried to use `listViewController.insertViewController(task, at: 0, animated: false)` for each task, but the app keeps crashing when loading the view because the stackView gets out of bounds.

Also, each `OCKInstructionsTaskViewController` presents a custom view controller with a .xib for completing the task. What would be the most optimal way to save an outcome to the store, when the user completes the steps in that view controller, in order to update the current task progress of the day?

Thank you in advance.

**Comment by erik-apple** [comment]
Can you provide a code snippet that shows how you are appending the instruction cards? It sounds like there may be something asynchronous in nature at play.

As for the second part of your question, please see the example in the readme about integration with ResearchKit. You can follow a pattern very similar to what we demonstrate there. The only difference will be that you present your own view controller instead of using one from ResearchKit.

```swift
// 1. Subclass a task view controller to customize the control flow and present a ResearchKit survey!
class SurveyViewController: OCKInstructionsTaskViewController, ORKTaskViewControllerDelegate {

    // 2. This method is called when the use taps the button!
    override func taskView(_ taskView: UIView & OCKTaskDisplayable, didCompleteEvent isComplete: Bool, at indexPath: IndexPath, sender: Any?) {

        // 2a. If the task was marked incomplete, fall back on the super class's default behavior or deleting the outcome.
        if !isComplete {
            super.taskView(taskView, didCompleteEvent: isComplete, at: indexPath, sender: sender)
            return
        }

        // 2b. If the user attempted to mark the task complete, display a ResearchKit survey.
        let answerFormat = ORKAnswerFormat.scale(withMaximumValue: 10, minimumValue: 1, defaultValue: 5, step: 1, vertical: false,
                                                 maximumValueDescription: "Very painful", minimumValueDescription: "No pain")
        let painStep = ORKQuestionStep(identifier: "pain", title: "Pain Survey", question: "Rate your pain", answer: answerFormat)
        let surveyTask = ORKOrderedTask(identifier: "survey", steps: [painStep])
        let surveyViewController = ORKTaskViewController(task: surveyTask, taskRun: nil)
        surveyViewController.delegate = self

        // 3a. Present the survey to the user
        present(surveyViewController, animated: true, completion: nil)
    }

    // 3b. This method will be called when the user completes the survey.
    func taskViewController(_ taskViewController: ORKTaskViewController, didFinishWith reason: ORKTaskViewControllerFinishReason, error: Error?) {        
        taskViewController.dismiss(animated: true, completion: nil)
        guard reason == .completed else {
            taskView.completionButton.isSelected = false
            return
        }

        // 4a. Retrieve the result from the ResearchKit survey
        let survey = taskViewController.result.results!.first(where: { $0.identifier == "pain" }) as! ORKStepResult
        let painResult = survey.results!.first as! ORKScaleQuestionResult
        let answer = Int(truncating: painResult.scaleAnswer!)

        // 4b. Save the result into CareKit's store
        controller.appendOutcomeValue(withType: answer, at: IndexPath(item: 0, section: 0), completion: nil)
    }
}
```

**Comment by athanasiospap** [comment]
I am appending the Instructions cards like this:

```swift
override func dailyPageViewController(_ dailyPageViewController: OCKDailyPageViewController, prepare listViewController: OCKListViewController, for date: Date) {
        let identifiers = ActivitiesIdentifiers.allCases.map { $0.rawValue }
        var query = OCKTaskQuery(for: date)
        query.ids = identifiers
        query.excludesTasksWithNoEvents = true

        storeManager.store.fetchAnyTasks(query: query, callbackQueue: .main) { (result) in
            guard let tasks = try? result.get() else { return }

                     tasks.forEach { (task) in
                     switch task.id {
                     case ActivitiesIdentifiers.task1.rawValue:
                           let task1 = Task1ViewController(viewSynchronizer:  Task1ViewControllerSynchronizer(), task: task, eventQuery: .init(for: date), storeManager: self.storeManager)                            
                           listViewController.insertViewController(task1, at: 1, animated: false)
                           case ActivitiesIdentifiers.task2.rawValue:
                           let task2 = Task2ViewController(viewSynchronizer:  Task2ViewControllerSynchronizer(), task: task, eventQuery: .init(for: date), storeManager: self.storeManager)                            
                           listViewController.insertViewController(task2, at: 2, animated: false)
                           case ActivitiesIdentifiers.task3.rawValue:
                           let task3 = Task3ViewController(viewSynchronizer:  Task3ViewControllerSynchronizer(), task: task, eventQuery: .init(for: date), storeManager: self.storeManager)                            
                           listViewController.insertViewController(task3, at: 3, animated: false)
                      }
        }
}
```

I have already implemented a ResearchKit task which has the specific structure that you provided. How can I structure our custom view controller in order to notify the store that a task is completed?

Furthermore, when user cancels a task, the completion button remains "Completed", while it should go to the initial state ( inherited from the ViewSynchronizer() ).

**Comment by gavirawson-apple** [comment]
> A. I am appending the Instructions cards like this:

I would recommend using the `appendViewController(viewController:animated:)` method over the `insertViewController(viewController:index:animated:)` method. There is some initial setup done in the framework to the `listViewController` before it is passed to this method that will affect the count of elements in the stack view.

> B. I have already implemented a ResearchKit task which has the specific structure that you provided. How can I structure our custom view controller in order to notify the store that a task is completed?

You can notify the store that the task is completed by storing an outcome for an event. This is done in Erik's example here:

```swift
// 4b. Save the result into CareKit's store
controller.appendOutcomeValue(withType: answer, at: IndexPath(item: 0, section: 0), completion: nil)
```

</br>

> C. Furthermore, when user cancels a task, the completion button remains "Completed", while it should go to the initial state ( inherited from the ViewSynchronizer() ).

The button in the UI automatically toggles itself when tapped. See the conversation here for details on how to turn off that behavior.

https://github.com/carekit-apple/CareKit/issues/417

**Comment by erik-apple** [comment]
@athanasiospap It's not quite clear which step in the process you're stuck at. Can you provide more detail? Is your custom view controller already setup with a delegate, and have you set the instructions task view controller that presents the custom view controller as the custom view controller's delegate?

**Comment by erik-apple** [comment]
I'm going to close this since the question has been addressed. If you need any further clarification, feel free to re-open the issue to ask!
