### ISSUE TITLE
Note is not being added to task

### ISSUE THREAD

**Issue by desmondbaldwin** [carekit-apple/CareKit#427]
After creating a task I tried adding a note to it but this does not seem to be working.

var newTask = OCKTask(id: auto_ID_Label.text!, title: habit_Title_TextBox.text, carePlanID: nil, schedule: finalSetOfSchedules)

newTask.impactsAdherence = true   
let newNote = OCKNote(author: "Test", title: "Test", content: "Test") newTask.notes?.append(newNote)

When I do a print of newTask.notes?.count, I'm seeing nil

**Comment by erik-apple** [comment]
Notes is `nil` by default, which means that `notes?.append(newNote)` doesn't actually do anything.

Try this instead.

```swift
var newTask = OCKTask(id: auto_ID_Label.text!, title: habit_Title_TextBox.text, carePlanID: nil, schedule: finalSetOfSchedules)

newTask.impactsAdherence = true
let newNote = OCKNote(author: "Test", title: "Test", content: "Test")
newTask.notes = [newNote]
```

**Comment by desmondbaldwin** [comment]
![tenor](https://user-images.githubusercontent.com/23667035/81125661-742a7b80-8efe-11ea-8942-f66a44495487.gif)

Thank you!
