### ISSUE TITLE
Reasoning about CareKit and HelthKit

### ISSUE THREAD

**Issue by cojoj** [carekit-apple/CareKit#429]
Hi,

I'm starting a new project, and I'm trying to reason about the technology I should be using to deliver the best and safest solution to our users.

We're planning to create an app which will be gathering some medical information about the user (from different 3rd party devices and sensors) and pushing it to our iOS app. We want to store this data locally so that user can always preview it, but we also need to send it to our backend as at the opposite end there'll be a doctor monitoring patient's health on the dig dashboard. It should be a continuous stream of data, so that doctor can react ASAP when some anomaly is being reported by the user's device.

At first, I thought it's a perfect use case for CareKit, but then I thought about HealthKit and how it gives me this amazing global store for all of the health-related data. On the other hand, I may not be able to push to our backend some medical data from 3rd party devices and applications since HealthKit is just an aggregator. On the other hand, CarKit seems to be more oriented towards some medical treatment, while what we want to do is observe and monitor our patients.

I'm confused now which framework should be our default one, and I'm looking for some guidance, in-depth explanation of how they're different. I'm sorry for dropping something like this in GitHub issues, but none of the existing materials on the Internet are able to convince me which solution is the right solution.

**Comment by erik-apple** [comment]
CareKit and HealthKit are complimentary. It sounds like you’ll need to use both.

---------

**HealthKit** provides a central repository for health and fitness data on iPhone and Apple Watch.

**CareKit** is a UI framework for health apps.

--------
Use CareKit for:
- **Creating UI and UX related to health and wellness**
- Delivering instructions to and scheduling tasks for patients
- Prompting patients to enter data or answer questions
- Visualizing trends
- Connecting users to their healthcare providers
- _Collection, persistence, and synchronization of care-centric data not supported by HealthKit_


You can learn more about HealthKit here - https://developer.apple.com/documentation/healthkit/about_the_healthkit_framework

**Comment by cojoj** [comment]
@erik-apple, thanks for your explanation. I believe my understanding was pretty similar, but I just needed insight from someone with more experience and in-depth knowledge in this area.

Just to sum up. I should be storing (and reading) all of my health data in HealthKit and use CareKit as a frontend for it, right? Additionally, if we'd encounter any issue or lacking data type in HealthKit we should fallback to CareKit's store and persist data in it in a way that makes sense for us.

Again, thank you very much! 😉

**Comment by erik-apple** [comment]
Yes, that all sounds right, generally speaking!
