### ISSUE TITLE
Issue migrating CareStore from 2.01 to latest on master

### ISSUE THREAD

**Issue by cbaker6** [carekit-apple/CareKit#431]
the latest version doesn't migrate from the old OCKStore. I get the following error when running on a device that had an older version of CareKit. 

> file:///var/mobile/Containers/Data/Application/F8014D3E-2B4F-4D05-A697-DC6120CB874E/Library/Application%20Support/AssuageCarkitDB_7358B5B4-1F38-441B-8CED-55E9D0084021_Patient.sqlite, "reason": Cannot migrate store in-place: Validation error missing attribute values on mandatory destination attribute]: file /Users/.../Documents/Xcode Projects/Assuage/Pods/CareKitStore/CareKitStore/CareKitStore/Protocols/CoreData/OCKCoreDataStoreProtocol.swift, line 87

Ignoring the pod part as that's pulling from the latest on the master. 

Deleting the app and reinstalling doesn't have an issue

**Comment by erik-apple** [comment]
It is likely that there will be occasional changes to the schema while the features on master are in beta. We will provide a migration from 2.0.1 to 2.1 when we deem those features stable and officially release them. 

For the time being we recommend folks who have production apps point to their dependencies at the `stable` branch, which is currently tagged at 2.0.1.
