### ISSUE TITLE
OutcomeValue.kind is not stored

### ISSUE THREAD

**Issue by drdavec** [carekit-apple/CareKit#439]
I found an issue where the 'kind' attribute of OutcomeValue is not persisted by the framework.  I create OutcomeValue as shown below and both 'groupIdentifier' and 'tags' are stored, but not 'kind'.
	var outcomeValue = OCKOutcomeValue(value)
	outcomeValue.groupIdentifier = stepResult.identifier
	outcomeValue.kind = item.code
	outcomeValue.tags = [item.code]

**Comment by erik-apple** [comment]
Thanks for filing a bug, we'll begin looking into this!
