### ISSUE TITLE
pressedToday Bug

### ISSUE THREAD

**Issue by tommysarni** [carekit-apple/CareKit#442]
This bug causes the UI to not update the DailyPageTaskViewController

How to reproduce bug:
1) go to a day other than the current day
2) press Today button
3) click the circle to the day you were just at

This happens when the function selectDate gets called.
Note: This does not occur when swiping

**Comment by erik-apple** [comment]
I was able to reproduce. Thanks for reporting this bug.

**Comment by erik-apple** [comment]
@tommysarni This was fixed as part of #475 and #480! Thanks for reporting this bug to us!

**Comment by tommysarni** [comment]
Thanks so much guys !
