### ISSUE TITLE
Handling the remote synchronization of a deleted Outcome

### ISSUE THREAD

**Issue by cbaker6** [carekit-apple/CareKit#446]
Hi @erik-apple, I've been looking at the tombstoning of an outcome when a "delete" occurs and it doesn't seem like the tombstoned outcome in `updateOutcomesLeavingTombstone`:

```swift
currentOutcomes.forEach {
            $0.deletedDate = Date()
            $0.values = Set()
}
```

gets added to the revision record. I do see the new outcome in the revision record with a deletedDate set, but this leaves the original outcome with no deletedDate on the remote still referencing it's outcomeValue. So on the remote, the original outcome is still active, though in the OCKStore it's correctly tombstoned.

I'm guessing the `logicalClock` of the tombstoned outcome isn't being incremented when it's tombstoned, so `changedQuery` isn't picking it up, but I couldn't find where `logicalClock` should be updated

**Comment by cbaker6** [comment]
I've tested this in OCKSample by setting the `currentOutcomes` significantly high and it seems like my previous comment may be a step in the right direction

```swift
currentOutcomes.forEach {
            $0.deletedDate = Date()
            $0.values = Set()
            $0.logicalClock = 10
        }
```

At the time the clock of the KnowledgeVector was ~5, so this tombstone was added to revision record and pushed to the remote

**Comment by cbaker6** [comment]
I finally found where the logicalClock is initially set, https://github.com/carekit-apple/CareKit/blob/f84d1ed481ed8a4f00abec745b7eec7f5583f86c/CareKitStore/CareKitStore/CoreData/OCKCDObject.swift#L50

It seems the `awakeFromInsert` method is only called by CoreData when the entity is first created which is why it never triggered during updates/deletes, but triggered during adds.

**Comment by erik-apple** [comment]
Thanks for working on this Corey!
We'll try to look into this in more detail next week, but what you've written so far all sounds right to me.

Since all the entities are intended to be immutable, _it should be_ sufficient to only set the logical clock on insert, and then never update it again. But you're right that tombstoned outcomes can presently be missed unless their clock is manually bumped.

**Comment by erik-apple** [comment]
I'm going over your PR again and wanted to loop back on this issue as well!

The current intended behavior is this:
```
1. An outcome is created and sync'd to the remote
   - Device: 1 outcome
   - Server: 1 outcome

2. The outcome is deleted locally
   - Device: 2 outcomes [1 tombstone, 1 "live" outcome with its deletedDate set]

3. A diff is generated containing 1 record
   - The new "live" version with non-nil deletedDate

4. The server receives the diff and inserts a new record. 
   - The presence of a new record indicates to the server it should tombstone its old record

5. The server and the device both have two records.
   - Device: 2 outcomes [1 tombstone, 1 live outcome with its deletedDate set]
   - Server: 2 outcomes [1 tombstone, 1 live outcome with its deletedDate set]
```

I believe your desired behavior is this (please correct me if I'm misunderstanding):

```
1. An outcome is created and sync'd to the remote
   - Device: 1 outcome
   - Server: 1 outcome

2. The outcome is deleted locally
   - Device: 2 outcomes [1 tombstone, 1 "live" outcome with its deletedDate set]

3. A diff is generated containing 2 records
   - The tombstoned outcome. 
   - The new "live" version with non-nil deletedDate

4. The server receives the diff and updates both of its records
   - Device: 2 outcomes [1 tombstone, 1 live outcome with its deletedDate set]
   - Server: 2 outcomes [1 tombstone, 1 live outcome with its deletedDate set]
```

Your proposal makes implementing the server correctly just a bit less error prone by moving the responsibility for declaring the old outcome a tombstone onto CareKit instead of the integration developer.

Does that accurately summarize this issue?

**Comment by cbaker6** [comment]
Yes! I will mention in step 4 in the “intended behavior” case, it currently seems hard to tell what outcome was tombstoned because the UUID of the outcome with the `deletedDate` set is different (new) from the original outcome. If the uuids were the same then it would be easy to tell what outcome to tombstone on the remote.

Since a new `uuid` is generated, the “desired behavior” helps the remote know what to tombstone.
