### ISSUE TITLE
UiCollectionView in Custom OCKGridTaskView

### ISSUE THREAD

**Issue by desmondbaldwin** [carekit-apple/CareKit#447]
I've created a custom OCKGridTaskView. I've added a stack view that contains a button. I am not sure what I'm doing wrong with the contrasts but the collectionView does not show unless I make its height a fixed value in the constraints. I want the height to adjust automatically like in OCKGridTaskView.

**Comment by desmondbaldwin** [comment]
Fixed. Needed to fix error in OCKSelfSizingCollectionView

**Comment by gavirawson-apple** [comment]
Glad you got it sorted out. If you've discovered a fix needed at the framework level, please consider contributing it back in a PR!
