### ISSUE TITLE
OCKContact+Extensions

### ISSUE THREAD

**Issue by garyphilipp** [carekit-apple/CareKit#451]
private extension OCKLabeledValue {
...
    func toLabeledPhoneNumber() -> CNLabeledValue<CNPhoneNumber> { CNLabeledValue(label: label, value: CNPhoneNumber(stringValue: **label**)) }
}

end of line should be CNPhoneNumber(stringValue: **value**)) }

**Comment by erik-apple** [comment]
Thanks for reporting this! We've just merged in a fix!
