### ISSUE TITLE
OCKContactUtility nameFormatter should use style .long

### ISSUE THREAD

**Issue by garyphilipp** [carekit-apple/CareKit#452]
The OCKContactUtility nameFormatter currently uses .medium for the formatter style, which displays given and family names only. Since it is very likely the contacts for Carekit include those in the medical field, i.e., Doctors, it would be more appropriate to use the formatter style .long so that the prefix (Dr.) is included in the formatted string that is displayed. Some medical professionals would find the current approach offensive.

**Comment by erik-apple** [comment]
That's a great suggestion! Would you like to submit a PR to make that change?

**Comment by garyphilipp** [comment]
Pull Request 454 submitted

**Comment by erik-apple** [comment]
Great, thank you!

**Comment by erik-apple** [comment]
Closed by #454
