### ISSUE TITLE
Symptom Tracker does not display multiple circles if an activity  has multiple events

### ISSUE THREAD

**Issue by jrames** [carekit-apple/CareKit#46]
The doc on Symptom Tracker states:

> Assessment activities also require valid schedule, title, and text parameters. The schedule sets the number of circles to be filled on each day.

However, in actuality, OCKSymptomTrackerViewController displays a new row for every assessment activity.  If one has multiple events, it simply appears on more than one row.

Not sure if the doc is wrong or if the code is wrong, but to me, what is documented is the more appropriate behavior.

**Comment by YuanZhu-apple** [comment]
>The schedule sets the number of circles to be filled on each day.

Documentation is wrong, your observation is expected.

**Comment by Pariecemckinney-apple** [comment]
https://github.com/carekit-apple/CareKit/issues/27
