### ISSUE TITLE
OCKSample is missing exercise.jpg

### ISSUE THREAD

**Issue by mkausas** [carekit-apple/CareKit#460]
The OCKSample app is missing the `exercise.jpg` image used by `TipView` [here](https://github.com/carekit-apple/CareKit/blob/3a5f8470626a2af9026dcaed5ad3d8f955e2fe14/OCKSample/OCKSample/CareViewController.swift#L86). 

The impact is an empty view when the app is loaded:
![image](https://user-images.githubusercontent.com/2219183/85868842-ae3a3000-b77f-11ea-9f6e-fb3e4b627590.png)

**Comment by mkausas** [comment]
Tagging @oalejel-apple who made the change in [this PR](https://github.com/carekit-apple/CareKit/commit/f66e72921c447e05672e9c8129d7f6144e2f9d6b).

**Comment by erik-apple** [comment]
Thanks for opening an issue!

This is actually intentional. We don't have the rights to distribute the original image in an open source project. We'd encourage you to add an image of your own choosing to your local copy of the repo if you'd like to see how it looks with a photo.
