### ISSUE TITLE
Show Custom Individual Image or multiple images on clicking Care card in detail view with Instructions 

### ISSUE THREAD

**Issue by UmairShams** [carekit-apple/CareKit#468]
Hello
I am facing issue regarding detail View of care card. I created the tasks but i am unable to show image in detail of care card.
Like in previous care card version (1.2) have the feature of individual imageView or multiple images and additional information on detail view but in Carekit 2.0 i am struggling to find these features. As i needed to have full screen image on detail of card or small images with additional information.If carekit 2.0 has these features please suggest with code.
Please suggest to resolve these issues. Like i am following task and how i can add the above requested features

var excerciseTask = OCKTask(id: CareStoreReferenceManager.TaskIdentifiers.exercisesTypes.rawValue,
                                   title: "Types of Excercise",
                                   carePlanID: nil, schedule: excerciseSchedule)
addTask(excerciseTask)

**Comment by gavirawson-apple** [comment]
Hello @UmairShams! How are you presenting the `OCKDetailView`? Are you presenting a task view controller such as the `OCKInstructionsTaskViewController`, that when tapped, automatically presents the detail view? Or are you creating the detail view and presenting it manually?

**Comment by UmairShams** [comment]
Hey @gavirawson-apple 
Thanks for your quick response.
I created the detail view with OCKDetailView
I am closing this issue.
