### ISSUE TITLE
Consider to merge `Symptom Tracker not updating fix` to stable

### ISSUE THREAD

**Issue by YuanZhu-apple** [carekit-apple/CareKit#47]
The PR https://github.com/carekit-apple/CareKit/pull/38 has been merged into master. It is kind of critical.

**Comment by umerkhan-apple** [comment]
r=m3.

**Comment by YuanZhu-apple** [comment]
https://github.com/carekit-apple/CareKit/commit/aa7b3e68407432488b908825fb9e3ba01d089772 in stable, released with https://github.com/carekit-apple/CareKit/releases/tag/1.0.1
