### ISSUE TITLE
Swift Compile Errors While adding CareKitFHIR to the project

### ISSUE THREAD

**Issue by hkolasani** [carekit-apple/CareKit#472]
Added https://github.com/carekit-apple/CareKit as a Swift Package to my project and tired to include CareKitFHIR library to my project target. I get these compile errors. Everything else works fine, once I remove CareKitFHIR library. 

<img width="627" alt="Screen Shot 2020-07-07 at 12 08 42 PM" src="https://user-images.githubusercontent.com/1964719/86831505-d06b6200-c04b-11ea-8091-c0b2c1394368.png">

**Comment by erik-apple** [comment]
Can you show us the contents of your `Package.resolved` file?
That might help us diagnose your problem.

**Comment by cbaker6** [comment]
@erik-apple to help replicate this, these errors pop up when you open the CareKit project from the Package.swift file and attempt to build "CareKit-Package".

**Comment by erik-apple** [comment]
This was fixed by #480! 
Thank you both for reporting this issue and helping us reproduce it!
