### ISSUE TITLE
UpdateAnyTasks calling addAnyTasks internally

### ISSUE THREAD

**Issue by garyphilipp** [carekit-apple/CareKit#474]
open func updateAnyTasks(_ tasks: [OCKAnyTask], callbackQueue: DispatchQueue = .main,
                             completion: ((Result<[OCKAnyTask], OCKStoreError>) -> Void)? = nil) {
        do {
            try findStore(forTasks: tasks).**addAnyTasks**(tasks, callbackQueue: callbackQueue, completion: completion)
        } catch {
            callbackQueue.async {
                completion?(.failure(.updateFailed(
                    reason: "Failed to find store accepting tasks. Error: \(error.localizedDescription)")))
            }
        }
    }

I suspect line #4 should have **updateAnyTasks**, not **addAnyTasks**. Since as it is, it does not update the task, but attempts to add a new one, and then fails as it is a duplicate.

**Comment by erik-apple** [comment]
That is definitely incorrect, thanks for letting us know!

**Comment by garyphilipp** [comment]
Thanks! I appreciate the awesome work you guys do, and I loved the WWDC session you did!

**Comment by erik-apple** [comment]
Thanks! We'd love to hear about how you're using CareKit too!

This issue was just patched in #480. Thanks again for spotting it!
