### ISSUE TITLE
Refresh CareViewController screen with pull-down refresh

### ISSUE THREAD

**Issue by majidsaleem105** [carekit-apple/CareKit#476]
Hello Everyone,

I'm using OCKDailyPageViewController to build my home/main activities screen. But I'm facing an issue that the app does not load any task when it opens for the first time. I've to click on a different date circle and then click back on the current day circle to view the tasks list of today. How can I fix this?

`var query = OCKTaskQuery(for: date)
query.excludesTasksWithNoEvents = true
storeManager.store.fetchAnyTasks(query: query, callbackQueue: .main) { result in
            switch result {

...

listViewController.appendViewController(newTaskCard, animated: false)

}}
`
1. Pull Down Refresh
How can I refresh the OCKDailyPeageViewController screen to update (add/remove any task) the tasks list? I remember that in the old CareKit version, there was a delegate method for pull-down refresh and I used to call a line like to update the tasks list view:

`viewController.tableView.reloadData()`

2. Grouping of tasks
Currently, mixed tasks are listed on the home screen, as these tasks are added. But we want to display tasks in Groups like we had Groups view in the old CareKit version.

 - How can we list all Physical activities altogether, no matter when a Physical task is added?
 - How can we list all Read-Only activities altogether, no matter when a Read-Only task is added?
 - How can we list all Surveys altogether, no matter when a survey task is added?

Thanks for your help.

**Comment by erik-apple** [comment]
Thanks for opening an issue!

## Pull To Refresh
Pull to refresh is a feature we will consider implementing within CareKit, but in the meantime, it's possible for you to set it up yourself!

```swift
override func dailyPageViewController(
    _ dailyPageViewController: OCKDailyPageViewController,
    prepare listViewController: OCKListViewController,
    for date: Date) {

        // ... Other work to setup the list view controller

        let refresher = UIRefreshControl()

        let action = UIAction(title: "Refresh") { action in
            // Do anything you want to when the user pulls to refresh.
            // This will likely include removing, recreating, and re-adding
            // any content you've added to the listViewController.
        }

        // actions are only available in iOS 14
        // If you need to support iOS 13, use addTarget with a selector instead
        refresher.addAction(action, for: .valueChanged)

        listViewController.listView.scrollView.refreshControl = refresher
}
```

## Grouping Tasks
Previous versions of CareKit were pretty prescriptive about how tasks were grouped, and we found that many developers needed more flexibility. Recent versions of CareKit allow you to do anything you'd like, but it requires a bit more work on your part.

If you'd like to put break the groups out into their own tabs, you'll just need to use a tab bar controller and filter which tasks you show in each tab. An easier way to do this is to set a `groupIdentifier` on your tasks when you add them to the store, and then query all tasks with a given `groupIdentifier` to populate one of your tabs.

If you'd like to group them together all on one screen, then you'll need to query your tasks, manually group them by some condition. Here too, `groupIdentifier` or `tags` can be useful properties. Swift's [Dictionary(grouping:by:)](https://developer.apple.com/documentation/swift/dictionary/3127163-init) is often a good tool for this. You can apply any sorting you want too. After that, add a card for each task, inserting some kind of separator between each section.

```swift
override func dailyPageViewController(
    _ dailyPageViewController: OCKDailyPageViewController,
    prepare listViewController: OCKListViewController,
    for date: Date) {

        var query = OCKTaskQuery(for: date)
        query.excludesTasksWithNoEvents = true

        storeManager.store.fetchAnyTasks(query: query, callbackQueue: .main) { result in
            switch result {
            case .failure(let error): print("Error: \(error)")
            case .success(let tasks):

            let groups: [String: OCKAnyTask] = Dictionary(grouping: tasks, by: { $0.groupIdentifier! })

            for (group, tasks) in groups {

                let sectionHeader = MyHeaderView(title: group)
                listViewController.appendView(sectionHeader, animated: false)

                for task in tasks {
                    let card = // ... OCKSimpleTaskView, OCKInstructionsTaskView, etc.
                    listViewController.appendViewController(card)
                }
            }
        }
}

You can use this same basic strategy to achieve any kind of grouping you want.
If you know which tasks are going to be in your app a priori, then you don't even have to rely on querying them or grouping them based on an identifier.
```

**Comment by majidsaleem105** [comment]
Thanks, @erik-apple for your replies. But you didn't answer the following question, can you please guide me on how can I resolve this issue?

I'm using OCKDailyPageViewController to build my home/main activities screen. But I'm facing an issue that the app does not load any task when it opens for the first time. I've to click on a different date circle and then click back on the current day circle to view the tasks list of today. How can I fix this?

`var query = OCKTaskQuery(for: date)
query.excludesTasksWithNoEvents = true
storeManager.store.fetchAnyTasks(query: query, callbackQueue: .main) { result in
switch result {

...

listViewController.appendViewController(newTaskCard, animated: false)

}}

**Comment by erik-apple** [comment]
> I'm using OCKDailyPageViewController to build my home/main activities screen. But I'm facing an issue that the app does not load any task when it opens for the first time. I've to click on a different date circle and then click back on the current day circle to view the tasks list of today. How can I fix this?

It's hard to tell what the problem is without seeing your app.

My best guess is that you're beginning to display the `OCKDailyPageViewController` before you begin adding the tasks into the store.

CareKit's `OCKStore` operates on a single serial background queue. What that means is that writes and queries are not concurrent - they happen serially in the order that you queue them, albeit in the background. If you start writing tasks before you display the `OCKDailyPageViewController`, CareKit will wait until writing the tasks to the store is complete before starting the fetch tasks query in the view controller, and you'll get the result you expect.

If you do it in the other order though - kicking of the query before the write - you'll get the behavior you're experiencing now. The query will complete first, returning no results, and then the tasks will be added into the store.
