### ISSUE TITLE
Swift Compiler Error Help

### ISSUE THREAD

**Issue by wchian2** [carekit-apple/CareKit#485]
Hello, I am trying to integrate CareKit into my iOS project through the SPM route (e.g. 'File > Swift Packages > Add Package Dependency') but I keep getting the same errors:

Swift Compiler Error
-Consecutive statements on a line must be separated by ';' in the LinkButton.swift and SimpleTaskView.swift files
-Expected expression
-Use of unresolved identifier 'label'
-Unable to infer complex closure return type; add explicitly type to disambiguate

Initially, I tried building using Storyboards, and the SwiftUI, both of which I couldn't get the build to run on the simulator. Is there an additional step I had to take to import CareKit?

**Comment by wchian2** [comment]
I've got the issue resolved. At the Choose Package Options, I selected the Version up to next major instead of Branch: master, and I have the sample running on simulator.

**Comment by gavirawson-apple** [comment]
Glad you got it resolved! If you decide you use the `master` branch, you will need the latest Xcode beta.
