### ISSUE TITLE
Unable to integrate CareKit into a Single View App

### ISSUE THREAD

**Issue by wchian2** [carekit-apple/CareKit#491]
Hello, I am having issues integrating CareKit into a single view app. Here's what I did:

- Create a new project
- File > Swift Packages > Add Package Dependency
- Enter the url https://github.com/carekit-apple/CareKit and tapped Next
- Selected radio button, Branch: master and tapped Next
- Checkmarked CareKit, CareKitUI, and CareKitStore, and tapped Finish

And I am getting these build errors. Is there other build steps that I need to take?

![Screen Shot 2020-07-28 at 10 03 54 PM](https://user-images.githubusercontent.com/15719491/88751904-3c5a5b00-d11e-11ea-90c6-030f7d064771.jpg)

**Comment by wchian2** [comment]
I played around with the settings, and it seems like selecting 'Version: Up to Next Major 2.0.1 < 3.0.0' at Choose Package Options, and then selecting CareKit, CareKitUI, and CareKitStore afterwards did the trick. I can build and run the app on the simulator without any problems. Can I use either Storyboards or SwiftUI when integrating CareKit?

**Comment by gavirawson-apple** [comment]
Based on the errors above, it looks like you don't have the latest beta version of Xcode. 

If you would like to use the SwiftUI API, you'll have to pull Master.  But either route you go, we don't support storyboards!

**Comment by vietmticts** [comment]
I have the same problem. Any ideas?

**Comment by gavirawson-apple** [comment]
What version of Xcode are you running? You'll need to be running the latest beta version.

**Comment by erik-apple** [comment]
wchian's problem has been resolved, so we're going to close this issue for now.
@vietmticts If you're still having problems and need further help, you may reopen this issue.
