### ISSUE TITLE
Missing localization in OCKScheduleUtility

### ISSUE THREAD

**Issue by Hatsushira** [carekit-apple/CareKit#502]
In OCKScheduleUtility are several places which are not localizable with the strings files provided:

`private static let dateFormatter: DateFormatter = {
  let formatter = DateFormatter()
  formatter.dateFormat = "M/d"
  return formatter
}()`

Additionally, there are hardcoded strings in:
`func timeLabel` and `func dateLabel`

**Comment by erik-apple** [comment]
Thanks for calling these to our attention!
