### ISSUE TITLE
Passcode screen does not appear

### ISSUE THREAD

**Issue by majidsaleem105** [carekit-apple/CareKit#513]
Hello everyone,

We have an app using the CareKit framework and it is working great but a few of our users are experiencing a very strange issue. After the successful authentication, we ask users to set up a passcode for quick access, the PassCode screen does not appear for some of the people and they can't use the app.

It displays the following message in the console `Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 25889_PortraitChoco_iPhone-Simple-Pad_Default`

We tried to use the different keyboard types but none of them is working. 
![number-pad-keyboard](https://user-images.githubusercontent.com/1611600/96258372-5e54d280-0fd5-11eb-849b-dec2a70d6f4c.png)

People are using the latest iPhone models iPhone X, 11, 11 Pro with iOS 13 & 14.

Please note that we're experiencing this issue on Real Devices, not in Simulators. 

Please advise on this issue that how it can be fixed?

Thanks,
- Majid S.

**Comment by erik-apple** [comment]
Hi Majid, this appears to be an issue more related to ResearchKit than CareKit. Would you mind opening an issue against ResearchKit instead?

When you do, please include the code used to create the `ORKPasscodeStep` so that we can try to replicate your issue.

**Comment by pthealthtech** [comment]
This [was opened initially on Researchkit](https://github.com/ResearchKit/ResearchKit/issues/1427) but there wasn't a response.

Best,
John
