### ISSUE TITLE
OCKWatchCatalog; Lifecycle issue

### ISSUE THREAD

**Issue by advatar** [carekit-apple/CareKit#517]
When using the latest version from master and trying to run the OCKWatchCatalog target I get:

Warning: Error creating LLDB target at path '/Users/johansellstrom/Library/Developer/Xcode/DerivedData/CKWorkspace-azisstsdszouesaxuxrhisnusxfp/Build/Products/Debug-watchsimulator/OCKWatchCatalog.app'- using an empty LLDB target which can cause slow memory reads from remote devices.
skipping /Applications/Xcode-beta.app/Contents/Developer/Platforms/WatchOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/watchOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/dyld_sim
2020-11-09 16:01:18.782049+0100 OCKWatchCatalog Extension[45278:7362563] [default] lookupMainFuncAddressInMachHeader:71: Invalid Swift entry point data
2020-11-09 16:01:18.782764+0100 OCKWatchCatalog Extension[45278:7362563] [default] lookupMainFuncAddressInMachHeader:77: Swift entry point addres could not be determined.
New session state: WCSessionActivationState
Sync failed: Companion app is not reachable

The sync issue is not relevant as it is running in the simulator but "Invalid Swift entry point data" is.

**Comment by gavirawson-apple** [comment]
Hey @advatar, what version of Xcode are you running? That'll help us spot the issue. I'd also recommend cleaning the derived data on your machine and building the target again.

As a side note, we've transitioned from the `master` branch to the `main` branch going forwards.

**Comment by advatar** [comment]
I have tried several versions but most recently Xcode 12.2 Release Candidate

Right, I am using the PC main branch.

**Comment by gavirawson-apple** [comment]
Great! I was able to reproduce the issue so we can look into a fix. Are you just seeing warnings in the console or are you not able to run the watch app at all?

**Comment by advatar** [comment]
It freezes and does not sync

**Comment by advatar** [comment]
I was however able to get something to work by using this

@main
struct VagusApp: App {

    @WKExtensionDelegateAdaptor(ExtensionDelegate.self) var extensionDelegate
    @Environment(\.scenePhase) private var scenePhase

    @SceneBuilder var body: some Scene {
        WindowGroup {
            NavigationView {
                if #available(watchOS 7, *) {
                    ScrollView {
                        VStack(spacing: 16) {
                            SimpleTaskView(taskID: "hrmin", eventQuery: .init(for: Date()), storeManager: extensionDelegate.storeManager)
                        }
                    }
                }
            }
        }.onChange(of: scenePhase) { phase in
            print("phase \(phase)")
            if phase == .background {
               //perform cleanup
            }
        }
        WKNotificationScene(controller: NotificationController.self, category: "myCategory")
    }
}

**Comment by advatar** [comment]
I guess the main difference is @main that does provide the missing entry point.

**Comment by advatar** [comment]
btw, once this works I would like to render a chart. None of the iOS charts are however available so I am trying to copy the design of InstructionsTaskView but it is a bit complex with many dependencies like DataSeries etc. While doing so I noticed that 

var event: OCKAnyEvent? {
        controller.objectWillChange.value?.firstEvent
    }

Is no longer correct. value is not available there.

**Comment by advatar** [comment]
Getting off topic here but why all the #if !os(watchOS) so that for instance this method can not be used for SwiftUI on the Watch?  https://github.com/carekit-apple/CareKit/issues/316#issuecomment-567738536

**Comment by advatar** [comment]
> Great! I was able to reproduce the issue so we can look into a fix. Are you just seeing warnings in the console or are you not able to run the watch app at all?

Any progress on this? Is this the recommended way?

@main
struct MyApp: App {
}

**Comment by gavirawson-apple** [comment]
> Any progress on this? Is this the recommended way?

Yes, I'd recommend removing the storyboard file and using the new `@main` entry point marker. If you're up for it, would you like to submit a PR with the fix?

> btw, once this works I would like to render a chart.

We do not currently support charting on the watch. If that would be useful, we can look into it in the future!

> Getting off topic here but why all the #if !os(watchOS) so that for instance this method can not be used for SwiftUI on the Watch?

Only a subset of the iOS CareKit features are currently supported on WatchOS. Is there a specific feature you're trying to use on the watch? Is it charting?
