### ISSUE TITLE
How to get the last selected intervention event?

### ISSUE THREAD

**Issue by ninoguba** [carekit-apple/CareKit#52]
With SymptomTrackerViewController, it provides the lastSelectedAssessmentEvent method to get access to the last assessment event.

I need the same for CareCardViewController but unfortunately it's not provided.

What I'm doing is present a custom TaskViewController on the didSelectRowWithInterventionActivity and didSelectButtonWithInterventionEvent delegates of the CareCardViewController but once the TaskViewController finishes with .Completed reason, I need to do something and I need to know the exact InterventionEvent that initiated it.     Would be great if the CareCardViewController can also provide the last selected Intervention Event.

Any suggestions how to do this?

**Comment by YuanZhu-apple** [comment]
@ninoguba Can your app preserve `interventionEvent` from `didSelectButtonWithInterventionEvent:(OCKCarePlanEvent`?

**Comment by ninoguba** [comment]
Yes that's what I did.   Just wonder why this is provided for the
assessment activity and not the intervention activity. They have a similar
use case.

On Monday, May 23, 2016, Yuan Zhu <notifications@github.com> wrote:

> @ninoguba <https://github.com/ninoguba> Can your app preserve
> interventionEvent from
> didSelectButtonWithInterventionEvent:(OCKCarePlanEvent?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/carekit-apple/CareKit/issues/52#issuecomment-221133991>
>


-- 
Sent from Gmail Mobile

**Comment by YuanZhu-apple** [comment]
Sure, we can add that.

**Comment by ninoguba** [comment]
Created this https://github.com/carekit-apple/CareKit/pull/73 to address this issue.

**Comment by tktsubota** [comment]
Should we close this issue now that #73 is merged?
