### ISSUE TITLE
Care-kit 2.1 & Xcode Compatibility?

### ISSUE THREAD

**Issue by Atamanam** [carekit-apple/CareKit#521]
I am updating my App from Carekit 1.0 to 2.0 

When I created a sample app with Xcode 11.3.1 it was fine but now when I downloaded the OCKSample from Github & try to run on the same Xcode 11.3.1 I am getting some errors.

I am currently on Xcode 11.3.1 & Mac OS Mojave. (I have dependency with another third party app where I need to maintain Xcode version to 11.3.1 & If I have multiple versions of Xcode I am getting errors while submitting to AppStore)

Can I still be on Xcode 11.3.1 & use Carekit 2.1 Framework in my project?

**Comment by gavirawson-apple** [comment]
The `main` branch requires Xcode 12, but you can run the `stable` branch in Xcode 13.

**Comment by amrutha786** [comment]
@gavirawson-  Thank you for the comment, but instead I I was able to upgrade my Mac OS to Catalina & have Xcode 12.1. 

Thank you,
