### ISSUE TITLE
Issue adding an image to an OCKChecklistTaskViewController card

### ISSUE THREAD

**Issue by gabe-l-rivera** [carekit-apple/CareKit#524]
I cannot find a way to add an image to an OCKChecklistTaskViewController card. In the attachment, the top portion above the instructions and label is light gray- this is where the image _should_ go.

![github issue carekit 2](https://user-images.githubusercontent.com/58158031/100527449-38a41700-3198-11eb-8a07-c5e27524bc76.png)

**Comment by erik-apple** [comment]
We should tweak CareKit to display the task's `asset` in this view by default.

In the meantime, you can set the image to whatever you'd like by subclassing the view controller.

```swift
class MyTaskViewController: OCKChecklistTaskViewController {


    /// Create a detail view that displays information about a task.
    /// - Parameter indexPath: Index path of the event whose task should be displayed.
    override func initiateDetailsViewController(forIndexPath indexPath: IndexPath) throws -> OCKDetailViewController {
        
        let detailViewController = super.initiateDetailsViewController(forIndexPath: indexPath)

        detailViewController.detailsView.imageView.image = /* Anything you want */

        return detailViewController
    }
}
