### ISSUE TITLE
BP Display

### ISSUE THREAD

**Issue by md0u80c9** [carekit-apple/CareKit#53]
Hi,

Is there a way of displaying blood pressure results, in the same way that there is in HealthKit? Can't see anything in the charting functions to do this.

Is there a simple solution to this without having to write a custom function?

**Comment by umerkhan-apple** [comment]
@md0u80c9 I think you are referring to the charts in the Health app. Unfortunately, that chart is not available for CareKit. One possible solution could be to use `ORKDiscreteGraphChartView` from ResearchKit. The approach would be to create a subclass of `OCKChart` and return `ORKDiscreteGraphCartView` for the `chartView` method override in your `OCKChart` subclass.

**Comment by akshay-yadav-apple** [comment]
Hey! @md0u80c9 

Do you need any further assistance with this issue?

**Comment by md0u80c9** [comment]
Hi,

I haven't managed to progress wth this any further (been busy with the HL7 CDA submission). I still think it would be useful in CareKit - blood pressure is obviously a fairly major measure.

**Comment by dukemike** [comment]
@akshay-yadav-apple, I thought it would be as simple as subclassing `OCKChart`, and returning the ORK chart for `chartView` like I did in this [gist](https://gist.github.com/dukemike/79f7fa2d062a39bfaa4a32339f8da891), but I always get _No Data_. What am I doing wrong?

Thanks!

**Comment by akshay-yadav-apple** [comment]
Try setting the height anchor on the chartView. 

Could you also upload the screenshot of what you're seeing.

Thanks!

**Comment by ninoguba** [comment]
@akshay-yadav-apple if Apple or someone who's done it successfully already could provide us examples on how to achieve showing ResearchKit-based charts onto CareKit's Insights, this would be tremendously helpful to the community.

**Comment by damer** [comment]
I came across this issue too and noticed that "_No Data_" was coming from the ORKLineGraphChartView object and not something that the OCKInsightItem object was doing. (I could set the noDataText property on the ORKLineGraphChartView and it would show up in the Insights View Controller).

The solution that worked for me was to declare the LineGraphDataSource as an optional and instantiate it within the chartView function and then connect it to the OCKLineGraphChartView.datasource.

Im no expert at Swift/ObjC/Cocoa so I really cant say why @dukemike 's gist doesn't work -- seems to me that it should.

**Comment by dukemike** [comment]
@damer, did you implement `copy`? I have something along the lines of:

```
    override func copy(with zone: NSZone? = nil) -> Any {
        let chart: SampleORKChart = super.copy(with: zone) as! SampleORKChart
        // copy any class-specific attributes...
        return chart
   }
```

where `SampleORKChart ` is my custom chart type.

**Comment by damer** [comment]
@dukemike - Yes I implemented copy similarly (it works correctly).

**Comment by kelseydedoshka-apple** [comment]
@md0u80c9, @dukemike, @ninoguba, @damer  - apologies its been a while here. We love the idea of being able to use ResearchKit charts in CareKit. Unfortunately we don't have an existing solution that we can share with you at this time however it seems as though @damer and @dukemike may have implementations here that have worked for them. Would you both mind sharing some additional information here or even sharing some code for others to take a look at?

**Comment by dukemike** [comment]
This code works for me, using RK's `PieChartDataSource` (eg, copy it into your project or into `OCKSample`.)

```
import UIKit
import CareKit
import ResearchKit

class MyChart: OCKChart {

    override func chartView() -> UIView {
        let chart = ORKPieChartView()
        let dataSource = PieChartDataSource()
        chart.dataSource = dataSource

        chart.heightAnchor.constraint(equalToConstant: 200).isActive = true
        return chart
    }
    
    override func copy(with zone: NSZone? = nil) -> Any {
        let chart: MyChart = super.copy(with: zone) as! MyChart
        return chart
    }
}
```

**Comment by kelseydedoshka-apple** [comment]
@dukemike - really appreciate the additional information and code snippet here!

**Comment by ninoguba** [comment]
Yes the examples from @dukemike helped me a lot.  Would just be nice if the example was included in OCKSample so others can find it easier.

**Comment by kelseydedoshka-apple** [comment]
@ninoguba great to hear and good suggestion for the sample app!

**Comment by erik-apple** [comment]
We will continue tracking this request under the proposal for new chart type #285.
