### ISSUE TITLE
Cannot add OCKHealthKitTask to OCKCarePlan

### ISSUE THREAD

**Issue by drdavec** [carekit-apple/CareKit#535]
I am trying to add a new OCKHealthKitTask to an existing OCKCarePlan, but the stored health kit task is always saved and fetched with a null carePlanUUID.  Tracing this through, it appears to be a problem in OCKCoreDataTaskStore.swift, in func copyTask.

On this line, the fetchObject returns nil, even tho the planUUID is valid.  This works for non-CareKit tasks added to the same planUUID.
        if let planUUID = task.carePlanUUID { persistableTask.carePlan = try? fetchObject(uuid: planUUID) }

I suspect that fetchObject is attempting to find a the planUUID within a OCKHealthKitTaskStore, which is not the correct store.  There also does not appear to be any way to create an OCKCarePlan within a OCKHealthKitTaskStore.

I can't see any workaround for this.  Any insight into this error or a possible solution?

Thanks!
  Dave Carlson

**Comment by erik-apple** [comment]
Dave, thanks for bringing this to our attention. Yes, this is currently a limitation of HealthKit linked CareKit tasks. We'll need to look into a way to support your use case.

**Comment by erik-apple** [comment]
@drdavec Thanks for raising this issue. It was fixed as part of our latest PR.

When you create an instance of `OCKHealthKitPassthroughStore`, you're now required to pass a reference an existing `OCKStore`. Doing so will allow us to make the proper associations.
