### ISSUE TITLE
Change DateFormat in OCKDailyPageViewController

### ISSUE THREAD

**Issue by MaiBS** [carekit-apple/CareKit#536]
I've been trying to customize and change the date format in OCKTaskControllers (circled in red in the attached image) in The OCKDailyPageViewController but didn't find a way to make it. I would appreciate it if you could provide me a solution to this `issue.`
Thanks 
![issue](https://user-images.githubusercontent.com/76703998/103243485-45b05380-495a-11eb-8407-69201c4c5628.jpg)

**Comment by gavirawson-apple** [comment]
Hey @MaiBS! The text can be customized by creating custom view synchronizers for the task cards. For a full reference, check out the Readme [here](https://github.com/carekit-apple/CareKit#custom-synchronized-view-controllers).

The task view controller updates each time the relevant task data in the store changes. When the task data changes, the  view controller's view synchronizer method `updateView(view:context)` gets called. It's a great place to map data from a task to the view. 

Your custom view synchronizer might look something like this:

```swift
class CustomSimpleTaskViewSynchronizer: OCKSimpleTaskViewSynchronizer {

    override func updateView(
        _ view: OCKSimpleTaskView,
        context: OCKSynchronizationContext<OCKTaskEvents>
    ) {
        super.updateView(view, context: context)
        view.headerView.detailLabel.text = "Custom text"   // Apply custom date format here
    }
}
```

And make sure to use the custom view synchronizer when the task view controller is created and displayed:

```swift
let taskViewController = OCKSimpleTaskViewController(
    viewSynchronizer: CustomSimpleTaskViewSynchronizer(),
    taskID: taskID,
    eventQuery: eventQuery,
    storeManager: storeManager
)
```

**Comment by MaiBS** [comment]
Thank you @gavirawson-apple
