### ISSUE TITLE
Question about OCKScheduleElement

### ISSUE THREAD

**Issue by zhang-bo-lilly** [carekit-apple/CareKit#537]
My understanding of the method 
https://github.com/carekit-apple/CareKit/blob/4936c622d55d876ccf43d7a4f4fa6acdf4db6747/CareKitStore/CareKitStore/Structs/OCKScheduleElement.swift#L184
is that it returns an array of events that happen between the given start and end dates. 

I noticed that the `end` parameter is first adjusted to not exceed the end date of the schedule element. Next, the method creates an array of events consisting of all the occurrences of the schedule from the `self.start` to the adjusted end date. At the end of the method, it applies a filter. 

The line here suggests that it will not filter out anything if the duration is all day. 
https://github.com/carekit-apple/CareKit/blob/4936c622d55d876ccf43d7a4f4fa6acdf4db6747/CareKitStore/CareKitStore/Structs/OCKScheduleElement.swift#L194 

Otherwise, it seems to filter out the ones happening before the `start` parameter passed into the method.  
https://github.com/carekit-apple/CareKit/blob/4936c622d55d876ccf43d7a4f4fa6acdf4db6747/CareKitStore/CareKitStore/Structs/OCKScheduleElement.swift#L195

What is the reason behind this different treatment? Am I reading the code wrong here?

**Comment by erik-apple** [comment]
I believe that line 194 was recently added. It sounds like you're suggesting that it may be resulting in unexpected behavior when the schedule element's start date is several days before the the start date passed into the function. If so, I suspect you're right, and there is probably a bug to be fixed.

The motivation behind the different treatment is this:

Consider a schedule that that repeats everyday at 5PM, but is marked as an all-day event. If we try to get all the events between morning and 12:00 noon, the all-day event associated with 5PM will be missed. The check performed on line 194 is to ensure that we include that event in the results.

It's a bit confusing that schedule events can be "all-day" and still have a specific time associated with them, but it has a handful of use cases.

**Comment by zhang-bo-lilly** [comment]
@erik-apple Thank you for providing the "all-day" example. I understand now that you are trying to find all the events that intersect with the time interval `[start, end]` and line 194 tries not to miss an all-day event. However, as you have guessed in my previous post, if the schedule element's start date is several days before the start date passed into the function, then you may return additional all-day events which may subsequently caused unexpected behaviors.

**Comment by erik-apple** [comment]
Yes, we'll need to add a few unit tests and tweak the condition I believe. If you'd like the change to be made quickly, you can do it yourself and submit it as a PR. We're happy to provide guidance if you need it. Otherwise we'll put it in the queue and get it patched up, but it won't be quite as fast as doing it yourself.

**Comment by erik-apple** [comment]
@zhang-bo-lilly I just submitted a fix for the bug you discovered. If you pull the latest commit from `main` you should find that it behaves as you expect now.
