### ISSUE TITLE
[CareKitStore] OCKScheduleElement userInfo missing

### ISSUE THREAD

**Issue by wmalloc** [carekit-apple/CareKit#539]
Looking at the documents at https://developer.apple.com/documentation/carekit/ockscheduleelement, it lists the `userInfo` property, but in the code is missing

The `main` branch is missing it. But the `stable` branch has it.

**Comment by erik-apple** [comment]
`userInfo` is still present on `OCKScheduleElement` on CareKit's `stable` branch. The `main` branch is considered pre-release and may not match current documentation.

`userInfo` will is a candidate for removal in our next release, so I would recommend not using it you can get away without it. Do you have a specific use case in mind that you require it for?

**Comment by wmalloc** [comment]
The backend passes the metadata for the `LinkView`, Is there a better item suited to pass that info along.

**Comment by erik-apple** [comment]
Would it work to put your metadata on OCKTask's `userInfo` property instead?
Typically that is the right place to store metadata related to task views.

**Comment by wmalloc** [comment]
I think that will work for us.

**Comment by erik-apple** [comment]
Glad to hear it!
