### ISSUE TITLE
Question about next property in OCKCDVersionedObject

### ISSUE THREAD

**Issue by zhang-bo-lilly** [carekit-apple/CareKit#540]
The `OCKCDVersionedObject` class has a `next` property
https://github.com/carekit-apple/CareKit/blob/56796e8c7915b5813a47f54d746219a29685cb81/CareKitStore/CareKitStore/CoreData/OCKCDVersionedObject.swift#L41

And the property is used in places like 
https://github.com/carekit-apple/CareKit/blob/56796e8c7915b5813a47f54d746219a29685cb81/CareKitStore/CareKitStore/CoreData/Synchronization/OCKStore%2BSynchronization.swift#L476

I noticed that the `previous` property is set at 
https://github.com/carekit-apple/CareKit/blob/56796e8c7915b5813a47f54d746219a29685cb81/CareKitStore/CareKitStore/Protocols/CoreData/OCKCoreDataStoreProtocol.swift#L183

However, when I tried to refactor `next` property to see where it is set, I am unable to locate the code snippet. Would someone point me to the correct place for that operation? Thanks.

**Comment by erik-apple** [comment]
That's a good question!

CoreData requires that an inverse be specified for all relationships.
You can see here that the `next` and `previous` properties are inverses of one another.

https://github.com/carekit-apple/CareKit/blob/56796e8c7915b5813a47f54d746219a29685cb81/CareKitStore/CareKitStore/CoreData/OCKManagedObjectModel.swift#L508-L509

That means that setting the `previous` property *automatically* sets the `next` property on the corresponding object. This is all taken care of by CoreData to reduce the number of places where developer error is possible, ensuring that the object graph remains in a valid.

**Comment by zhang-bo-lilly** [comment]
Thank you @erik-apple for pointing that out. I find it a great way to learn how to use CoreData programatically, but I wonder if you can comment what are the advantages instead of using a `.xcdatamodeld` file?

**Comment by erik-apple** [comment]
Another great question!

When CareKit 2.0 was released, Swift Package Manager did not support bundling resources, so we decided to spell out the managed object model programmatically solely to make CareKit compatible with SPM. Fortunately, resources are now supported by SPM, so we'll be going back to a `xcdatamodeld` file in a future release of CareKit!
