### ISSUE TITLE
OCKSample app outcome selection not working

### ISSUE THREAD

**Issue by nizar** [carekit-apple/CareKit#546]
Selecting an outcome in the OCKSample app does not appear to work if the first store added to the store coordinator is the OCKHealthKitPassthroughStore.

**Comment by nizar** [comment]
The logic below should probably account for the case where store is OCKHealthKitPassthroughStore and the outcome is not OCKHealthKitOutcome

https://github.com/carekit-apple/CareKit/blob/7dfcdef4de7e91449e86ac963043b44188a6ba31/CareKitStore/CareKitStore/StoreCoordinator/OCKStoreCoordinator.swift#L280-L294

**Comment by erik-apple** [comment]
Yes, I think you're right. @cbaker6 reported seeing a bug related to this too.

Would you like to submit the fix yourself, or would you like us to take care of it?

**Comment by cbaker6** [comment]
Here’s the discussion about the issue: https://github.com/carekit-apple/CareKit/pull/543#issuecomment-768676755

**Comment by erik-apple** [comment]
The issue seems to have come in as part of the last PR.
https://github.com/carekit-apple/CareKit/pull/541/files#

Looks like the logic was unintentionally reversed. We can add a unit test and patch it up.

**Comment by nizar** [comment]
I just created a pull request for a proposed fix.

**Comment by erik-apple** [comment]
Thanks. Let's continue the discussion over #547.
