### ISSUE TITLE
OCKCartesianChartView odd y-axis intervals

### ISSUE THREAD

**Issue by LuisMFlores** [carekit-apple/CareKit#556]
Working on a personal project using CareKit and ResearchKit, I'm trying to display data in a chart form from the user's input. I am using CareKit for this purpose among other things, but I started to notice an odd behavior in the y-axis while using OCKCartesianChartView.

Trying to display the weight section

<img width="699" alt="Screen Shot 2021-03-12 at 11 31 57 AM" src="https://user-images.githubusercontent.com/24774992/110969425-abd83000-8326-11eb-988d-6777a0a9c4b7.png">

<img width="295" alt="Screen Shot 2021-03-12 at 11 32 30 AM" src="https://user-images.githubusercontent.com/24774992/110969430-aed32080-8326-11eb-9010-7c5707c26020.png">

You can barely see the downtrend from 329lbs to 320lbs because of the y-axis scaling. So rewriting this a bit to get a better scaling for the user to understand, I set the yMinimum and yMaximum

<img width="697" alt="Screen Shot 2021-03-12 at 11 35 55 AM" src="https://user-images.githubusercontent.com/24774992/110969958-42a4ec80-8327-11eb-9acf-451ba63f97b2.png">

<img width="288" alt="Screen Shot 2021-03-12 at 11 36 19 AM" src="https://user-images.githubusercontent.com/24774992/110969967-46d10a00-8327-11eb-87fd-7b7499c8779e.png">

Now the trend is clearly visible but then the y-axis labels makes no sense. In my mind, I would expect to see the top label to be 330 and the lower label to be 315.  Digging into how the y-axis level is generated I found this:

<img width="738" alt="Screen Shot 2021-03-12 at 11 39 35 AM" src="https://user-images.githubusercontent.com/24774992/110970363-af1feb80-8327-11eb-9592-990cc3099daf.png">

From the code in the picture above, it says that it naming the topValueLayer (yMax) from the graphBounds. From the start I thought that was kind of odd because a view size has nothing to do with the labeling of an axis (I could be wrong, but can figure out the correlation here). So went to see how are the bounds calculated:

<img width="673" alt="Screen Shot 2021-03-12 at 11 42 31 AM" src="https://user-images.githubusercontent.com/24774992/110970743-0f169200-8328-11eb-95b5-c8f2b480c457.png">

So the yMax is created from the height of the bounds which are calculated by yMax - yMin. But this makes sense for the size of a view, but not the y-axis. 329 (yMax) - 315 (yMin) = 14 which is what the graph is showing (15 close enough). 

So, have anyone encountered this issue? any workarounds? maybe something I'm missing? I am using CareKit 2.0. Thanks in advance for the response.

**Comment by erik-apple** [comment]
That does seem like a bug!
It's probably a relatively simple fix. If you'd like to patch it and submit a PR, I'd be happy to provide guidance.

We're also happy to fix it, but it might not get done as quickly as doing it yourself.

It might be as simple as changing...
```swift
// Current
topValueLayer.string = "\(graphBounds().height)"

// Fix?
topValueLayer.string = "\(graphBounds().maxY)"
```

**Comment by LuisMFlores** [comment]
@erik-apple, digging a bit more on this issue. I was checking the main branch against the release branch for this and noticed this 

<img width="930" alt="Screen Shot 2021-03-12 at 1 47 02 PM" src="https://user-images.githubusercontent.com/24774992/110984795-9c161700-8339-11eb-8871-3a00618504c5.png">

From the code above, I believe this issue has been fixed by you (middleValueLayer.string) and Erik (topValueLayer.String) it just need to be merge into the stable branch. I understand you folks are busy, but by any chance any timeframe when this might happen. Thanks again and feel free to close this issue in your response.

**Comment by erik-apple** [comment]
> Thanks for all the support on the CareKit forum that you have given

You're very welcome! 


Wow, sorry for not noticing that had been fixed already! I hope you didn't have to waste too much time on that!
I'll look at the possibility of cherry picking that change into stable.

In the meantime, your best bet is to either
a) Cherry pick commit f84d1ed481ed8a4f00abec745b7eec7f5583f86c onto your local checkout of `stable`
b) Checkout the `main` branch and build against it

**Comment by erik-apple** [comment]
We just merged the relevant changes into stable!
