### ISSUE TITLE
"Completed" InterventionActivityEvent on the CareCard reset to "not completed" when tapped

### ISSUE THREAD

**Issue by ninoguba** [carekit-apple/CareKit#56]
On the CareCard,  when I've completed an activity (I show a custom task here), the corresponding circle gets filled.  But when I tap the same circle, the state goes back to unfilled as if I've never completed it prior.  How can this be prevented?

**Comment by umerkhan-apple** [comment]
https://github.com/carekit-apple/CareKit/blob/master/CareKit/CareCard/OCKCareCardViewController.h#L57
You can use that method in the delegate to manually control the event completion.

**Comment by ninoguba** [comment]
Umer,

I'm returning NO for that delegate method already and implemented my own custom logic upon completion of the task presented.  This works as expected.

The issue I found is when the activity has been completed already (circle filled).  The moment you tap the completed circle, the fill is cleared right before the activity task gets presented.   Because they've completed the task before, they don't need to complete it anymore.  The problem is for the circle to be backed to filled status, they'll have to complete the whole task again.

Since I've implemented shouldHandleEventCompletionForActivity to return NO I expected to have complete control of the activity completion states but that clearly is still not the case.

**Comment by ninoguba** [comment]
Also noticed the corresponding OCKCarePlanEvent's state for the circle stays .Completed (if it was completed before) while the circle on the CareCard is not filled in this subsequent tap scenario.

**Comment by ninoguba** [comment]
To workaround this issue, I added a conditional check in my ORKTaskViewController's didFinishWithReason delegate, that regardless of the reason (.Completed or .Discarded), if the OCKCarePlanEvent's state was already .Completed then I just update the store again with the .Completed state and this keeps the completed circles filled.  A little redundant but it works for now. 

Thinking ahead though, this might skew the data for the Insights.

**Comment by umerkhan-apple** [comment]
@ninoguba Your approach is correct. You should override the delegate that disables automatic updating of events, and then use your logic to update the state of the event.

**Comment by ninoguba** [comment]
The problem is the subsequent updates to the state of the event that gets stored in the CarePlanStore.  The user really only completed the activity once but on the store it may appear to be completed several times.   Depending on the use case, this approach may or may not work.
