### ISSUE TITLE
OCKDailyTasksPageViewController tasksDelegate behavior

### ISSUE THREAD

**Issue by nizar** [carekit-apple/CareKit#562]
I noticed that there is a OCKDailyTasksPageViewControllerDelegate available on OCKDailyTasksPageViewController but no real way to attach to it since it is assigned to self in viewDidLoad.

https://github.com/carekit-apple/CareKit/blob/730037b1a3dd9bb18d61e8a2d0a88bb022ab963c/CareKit/CareKit/iOS/Higher%20Order/ViewController/OCKDailyTasksPageViewController.swift#L63-L66

Furthermore, in the following code, the nil coalescing operator doesn't have any effect since self is assigned to tasksDelegate already.

https://github.com/carekit-apple/CareKit/blob/730037b1a3dd9bb18d61e8a2d0a88bb022ab963c/CareKit/CareKit/iOS/Higher%20Order/ViewController/OCKDailyTasksPageViewController.swift#L115-L117

Perhaps tasksDelegate should be assigned to self in init() rather than viewDidLoad()?

**Comment by erik-apple** [comment]
Nice spot!

I think the real answer here is that the delegate shouldn't be set by default at all.

The intended behavior is that if you set the delegate, we call your method. If you don't set the delegate, then we fall back on our default implementation (the 2nd half of the nil coalescing operator).

**Comment by nizar** [comment]
@erik-apple if I can add one more suggestion to OCKDailyTasksPageViewController, I think there should be a guard at the top of dailyTasksPageViewController(viewControllerForTask) to check if events.count > 0. There is a case where you may have a task with a schedule where events occur on every other day where this method is called but the event count is zero. The current implementation returns a viewController that basically shows an empty card. The code below includes the guard.

```swift
    // MARK: - OCKDailyTasksPageViewControllerDelegate

    open func dailyTasksPageViewController(_ viewController: OCKDailyTasksPageViewController, viewControllerForTask task: OCKAnyTask,
                                           events: [OCKAnyEvent], eventQuery: OCKEventQuery) -> UIViewController? {

        guard events.count > 0 else { return nil }
        
        // If the task is linked to HealthKit, show a view geared towards displaying HealthKit data
        if #available(iOS 14, *), task is OCKHealthKitTask {
            let controller = OCKNumericProgressTaskController(storeManager: storeManager)
            controller.setViewModelAndObserve(events: events, query: eventQuery)
            return NumericProgressTaskView(controller: controller)
                .hosted()

        // Show the button log if the task does not impact adherence
        } else if !task.impactsAdherence {
            let taskViewController = OCKButtonLogTaskViewController(controller: .init(storeManager: self.storeManager), viewSynchronizer: .init())
            taskViewController.controller.setViewModelAndObserve(events: events, query: eventQuery)
            return taskViewController

        // Show the simple if there is only one event. Visually this is the best style for a single event.
        } else if events.count == 1 {
            let taskViewController = OCKSimpleTaskViewController(controller: .init(storeManager: self.storeManager), viewSynchronizer: .init())
            taskViewController.controller.setViewModelAndObserve(events: events, query: eventQuery)
            return taskViewController

        // Else default to the grid
        } else {
            let taskViewController = OCKGridTaskViewController(controller: .init(storeManager: self.storeManager), viewSynchronizer: .init())
            taskViewController.controller.setViewModelAndObserve(events: events, query: eventQuery)
            return taskViewController
        }
    }

    open func taskViewController<C, VS>(
        _ viewController: OCKTaskViewController<C, VS>,
        didEncounterError: Error) where C: OCKTaskController, VS: OCKTaskViewSynchronizerProtocol {

        log(.error, "An error occurred in the daily tasks controller, but it was no handled!", error: didEncounterError)
    }
}
```
