### ISSUE TITLE
Provide closure based reset method to clear store

### ISSUE THREAD

**Issue by wmalloc** [carekit-apple/CareKit#568]
Either of these will work.

```
	public func reset(completion: ((Result<Bool, Error>) -> Void)? = nil) {
		do {
			try context.performAndWait {
				for name in supportedTypes.map({ $0.entity().name! }) {
					let fetchRequest = NSFetchRequest<NSManagedObject>(entityName: name)
					fetchRequest.includesPropertyValues = false
					fetchRequest.includesSubentities = false

					let objects = try self.context.fetch(fetchRequest)
					objects.forEach { self.context.delete($0) }
				}
				try self.context.save()
			}
			completion?(.success(true))
		} catch {
			completion?(.failure(error))
		}
	}

	public func reset() -> Future<Bool, Error> {
		Future { [weak self] promise in
			do {
				try self?.context.performAndWait {
					for name in supportedTypes.map({ $0.entity().name! }) {
						let fetchRequest = NSFetchRequest<NSManagedObject>(entityName: name)
						fetchRequest.includesPropertyValues = false
						fetchRequest.includesSubentities = false

						let objects = try self?.context.fetch(fetchRequest)
						objects.forEach { self?.context.delete($0) }
					}
					try self?.context.save()
				}
				promise(.success(true))
			} catch {
				promise(.failure(error))
			}
		}
	}
```

forgive the code mistakes as typed in here

**Comment by erik-apple** [comment]
Thanks for opening an issue!

As it stands now, the `reset()` method on `OCKStore` is a synchronous method. The contents of the store will have already been wiped by the time your program returns from `reset()`, so there is no need for a callback.

Is your proposal to make the method asynchronous instead? What is your use case for adding a callback?

**Comment by wmalloc** [comment]
Since there is a delegate call back when the store is done with clearing the data. I wanted to. have a similar call with closure.

**Comment by erik-apple** [comment]
The delegate method exists so that `OCKSynchronizedStoreManager` can find out when you the developer reset the store.
We don't know when you are going to clear the store, so we set ourselves at the delegate and use the callback as an opportunity to do some book keeping.

As a developer, you don't need a callback because you have full control over when `reset()` is called, and `reset()` is synchronous. It finishes immediately, so there is no need to delay work until after it completes.

```swift
// Because reset() is synchronous method already...

// Your proposed change...
store.reset(completion: { result in
    self.doSomethingElse()
})

// Is exactly equivalent to...
try store.reset()
doSomethingElse()
```

**Comment by wmalloc** [comment]
Thank you
