### ISSUE TITLE
Group items in CareCard and SymptomTracker Views

### ISSUE THREAD

**Issue by ninoguba** [carekit-apple/CareKit#57]
It would be great if the activities that appear in both the Care Card and Symptom Tracker views can be grouped based on the CarePlan Activity's group identifier.

And to go further, it would be ideal if the order of these groups and items can be programmatically controlled.

**Comment by YuanZhu-apple** [comment]
@ninoguba This may relate to #51

**Comment by akshay-yadav-apple** [comment]
Hey @ninoguba ,

Do you need further assistance with this issue?

**Comment by ninoguba** [comment]
@akshay-yadav-apple @YuanZhu-apple can we tag this as an enhancement request?  #51 i agree can be related to this as that asks to control the display order while this asks for displaying group headings, both pertaining to the activities that show on the care card and symptom tracker.

**Comment by ninoguba** [comment]
I was just able to group my activities on the Symptom Tracker and control their display order a bit a hackish way by modifying and adding the necessary UITableViewDelegate and UITableViewDataSource methods in OCKSymptomTrackerViewController.m directly.

I was also able to change the font size and colors of the table view cells and headers.

If others need help on this I can share the code. I can work on making my custom code more generic and will contribute it back when I get the chance if there is any interest.

![simulator screen shot mar 17 2017 12 18 03 am](https://cloud.githubusercontent.com/assets/4361804/24032832/368ac52a-0aa7-11e7-9653-b37e5d1d3c88.png)

**Comment by xmlmodeling** [comment]
Hi @ninoguba 
The your UI for grouping and sorting activities in very close to an enhancement needed for my app, are you still willing to share the code?  I started working on iOS dev 2 years ago with Swift and not so comfortable with Objective C enhancements (hoping that a future release of CareKit will be all native Swift).  I looked at your repos and see a fork of CareKit, but it does not appear to include this enhancement.

Thanks!
  Dave

**Comment by ninoguba** [comment]
@xmlmodeling here you go:

https://github.com/ninoguba/CareKit/blob/grouped_symptom_tracker/CareKit/SymptomTracker/OCKSymptomTrackerViewController.m

**Comment by xmlmodeling** [comment]
@ninoguba Thanks Nino for your quick response!  I am researching use of the FHIR CarePlan standard to define all content of a care plan, and a generalized app that can read the care plan from any FHIR server, map to CareKit data structure, and present to the user.  I am interested in grouping both interventions and assessments in CareKit UI using categories from FHIR CarePlan.

**Comment by ninoguba** [comment]
@xmlmodeling that is a worthwhile effort. I suggest extending the Care Card and Symptom Tracker view controllers or its delegates to support displaying the events with dynamic groupings and sort orders.  Let me know if you need help on this.
