### ISSUE TITLE
Updating Task with Outcome

### ISSUE THREAD

**Issue by desmondbaldwin** [carekit-apple/CareKit#570]
Hello,
I am having a similar issue as that described in issue 353.

When I update the task without updating anything else the task updates correctly. However when there is an outcome I get the following error.

Error: invalidValue(reason: "Failed to update: Updating task 04DC8951-8228-432F-84CA-1516CDCE21EA failed. The new version of the task takes effect on 2021-04-14 13:00:00 +0000, but an outcome for a\nprevious version of the task exists on 2021-04-14 13:00:00 +0000. To prevent implicit data loss, you must explicitly delete all outcomes\nthat exist after the new version\'s `effectiveDate` before applying the update, or move the new version\'s `effectiveDate` to\nsome date past the latest outcome\'s date.")

I am using the main branch in my application. Commit - 746e47f

I perform a fetch of the task by ID. I change one value and then update it. As mentioned before, it works fine until I update the outcome on the interface and then it starts producing the error.

**Comment by erik-apple** [comment]
Hi Desmond. Thanks for opening an issue!

It sounds like perhaps you need to set the `effectiveDate` of your task to some date *after* the outcome.
If you've saved an outcome on April 15th, then you either need to set the date that the new version of the task takes effect to a date *after* the outcome (to prevent the outcome from being overwritten), or you need to delete the outcome before updating the task.

Is that what you're doing already?

**Comment by desmondbaldwin** [comment]
I've been updating the effective date to a future date but I see now that I did not fully understand the versioning concepts so I will go ahead and close this out. Thank you for your help.
