### ISSUE TITLE
OCKCareSchedule cannot be subclassed in swift

### ISSUE THREAD

**Issue by baxtercr** [carekit-apple/CareKit#58]
OCKCareSchedule.init() is marked as NS_UNAVAILABLE and the initialiser initWithStartDate(...) is set as private.   The documented comments advise to inherit from OCKCareSChedule and call initWithStartDate.  In this Swift this is not possible. (Not sure but it may not be possible in Objective C too)

**Comment by YuanZhu-apple** [comment]
@baxtercr Thanks for reporting it. 
Plan to get it fixed and push to stable branch.

**Comment by srinathtm-apple** [comment]
Closing out issues that are no longer relevant due to the CareKit 2.0 beta update.
