### ISSUE TITLE
Crash in fetchTasks

### ISSUE THREAD

**Issue by advatar** [carekit-apple/CareKit#588]
How can I possibly debug this?

It starts here

![image](https://user-images.githubusercontent.com/28670/120315435-a9a9c000-c2dc-11eb-911a-d4e21654679f.png)

and ends here

![image](https://user-images.githubusercontent.com/28670/120315735-f55c6980-c2dc-11eb-96e8-1bd927fb2f0f.png)

**Comment by advatar** [comment]
It also happens in OCKHealthKitPassthroughStore fetchTasks

![image](https://user-images.githubusercontent.com/28670/120316480-c4c8ff80-c2dd-11eb-9b44-e5ffaeb09f7b.png)

**Comment by erik-apple** [comment]
Can you describe the circumstances that cause this to happen? Is it readily reproducible, or is it one of those things that only happens every once in a while?

**Comment by advatar** [comment]
It happens quite often but mostly on lower end devices. It is a SIGKILL for spending more than 10s:

```
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, <RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-update watchdog transgression: application<ecg.vagus.app>:278 exhausted real (wall clock) time allowance of 10.00 seconds | ProcessVisibility: Background | ProcessState: Running | WatchdogEvent: scene-update | WatchdogVisibility: Background | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 17.770 (user 17.770, system 0.000), 89% CPU", | "Elapsed application CPU time (seconds): 9.260, 46% CPU" | ) reportType:CrashLog maxTerminationResistance:Interactive>
Triggered by Thread:  0

```

I am creating rather large OCKOutcomes with 30s of ECG voltages as Data. For each creation it gets slower and slower and might have to do with a leak?

**Comment by advatar** [comment]
So, the problem might not be exactly where the it crashes.

**Comment by erik-apple** [comment]
It's possible that the large file size is not the root issue, but is causing secondary problems that build up to the crash. How large are the `Data` that you're saving onto your outcomes?

As a general practice, we recommend not storing large amounts of data on CareKit outcome values. A better approach is to save the file into a folder on disk, then save that file's URL into an OCKOutcomeValue. Doing so allows CareKit queries to be performant. In views or controllers that display and interact the ECG voltages, you should lazily load the resource from disk so that your app doesn't use resources unless necessary.

**Comment by advatar** [comment]
Thanks, I can try that strategy instead. The OCKOutcomeValue is typically over 300k....

**Comment by advatar** [comment]
I changed to use the file system instead but it made no difference. In order to further investigate I

1. Removed display of charts from HealthKit
2. Removed the HealthKit tasks like:

```
let optical = OCKHealthKitTask(
            id: OCKStore.Tasks.heartRate.rawValue,
            title: NSLocalizedString("OPTICAL_HEARTRATE", comment: ""),
            carePlanUUID: nil,
            schedule: alldaySchedule,
            healthKitLinkage: OCKHealthKitLinkage(
                quantityIdentifier: .heartRate,
                quantityType: .discrete,
                unit: HKUnit(from: "count/min")))
```
1 made no difference but 2 did. It seems to me that somehow the continuous sync of HealthKit somehow interfere with my updates of the main OCKStore. For every addition of ECG it gets slower and slower to update the views in the OCKDailyPageViewController.
