### ISSUE TITLE
Sample doesn't exclude data from backup

### ISSUE THREAD

**Issue by stevemoser** [carekit-apple/CareKit#59]
According to the guidelines for CareKit and ResearchKit based apps data should not be stored in iCloud. Thus the data file(s) created in sample app for CareKit should be excluded from backup by using the `NSURLIsExcludedFromBackupKey` key but are not currently. Also is there a way to exclude files from being backed up to iCloud and unencrypted iTunes backups but not encrypted iTunes backups like Health.app does?

**Comment by ag14spirit** [comment]
Any further progress on this issue? #

**Comment by srinathtm-apple** [comment]
Hello @stevemoser , @ag14spirit  - I just started looking into this, can you please point me to the documentation which explicitly says that CK/RK app data should not be stored in iCloud? I am unable to find it. 

Also, currently there is no way to specify particular directory to exclude back up to iCloud/iTunes and allow backup only for iTunes encrypted backups. Both RK and CK leave it up to the developer to specify the directory where they want to store the results or care plan store respectively.

**Comment by stevemoser** [comment]
Hi @srinathtm-apple. On the wiki it says "Do not use iCloud to store health information."

https://github.com/carekit-apple/CareKit/wiki

And I was thinking of the sample specifically, not the framework. Thanks

**Comment by srinathtm-apple** [comment]
Hi all, this has been fixed in CareKit 2.0, in-fact all instances of CareKitStore now set the isExcludedFromBackup flag to true by default.
