### ISSUE TITLE
Integration with CloudKit

### ISSUE THREAD

**Issue by cadaniel** [carekit-apple/CareKit#590]
Since the care kit store is using CoreData, is it possible to use CloudKit to store data in the cloud? 

If so how?

**Comment by cadaniel** [comment]
Giving up on this

**Comment by erik-apple** [comment]
It depends where in the world you live and what kind of data your app creates. Most countries have strict regulations around the transport and storage of medical data.

The recommended approach is to identify a service that is compliant with the regulations in the region you will be releasing your app, and to use the `OCKRemoteSynchronizable` protocol to interface with that service.
