### ISSUE TITLE
[BUG?] OCKOutcome for task only found when querying all, and none by date

### ISSUE THREAD

**Issue by cadaniel** [carekit-apple/CareKit#593]
So I'm creating an app, and I'm trying to see if the task has been completed on a day. 

I've done all my debugging today, so all dates are at some point today. When I query all, I get 10 outcomes for a task, when I query for date or date interval, it comes up with nothing. 

![Screen Shot 2021-06-06 at 2 29 51 PM](https://user-images.githubusercontent.com/5515671/120939193-0b4e9d80-c6d4-11eb-848a-195496c4f530.png)
![Screen Shot 2021-06-06 at 2 29 38 PM](https://user-images.githubusercontent.com/5515671/120939194-0c7fca80-c6d4-11eb-9a44-63cfffc99724.png)

**Comment by cadaniel** [comment]
Now things are getting strange. 

querying for a date, or dateInterval returns results from two days ago. 

![Screen Shot 2021-06-08 at 9 20 32 AM](https://user-images.githubusercontent.com/5515671/121212721-d6108f80-c83a-11eb-8df9-fb8ab0176c7f.png)
![Screen Shot 2021-06-08 at 9 18 38 AM](https://user-images.githubusercontent.com/5515671/121212725-d741bc80-c83a-11eb-81e2-21fa52df50a3.png)

As you can see truncated is June 8th at midnight UTC. But the results were created on June 6. Becuase it's over 24 hours, it's not a timezone thing. Not to mention getting rid of setting it to UTC doesn't yield different results.

**Comment by cbaker6** [comment]
I believe your problem is you are not querying by the date which was brought up and answered here: https://github.com/carekit-apple/CareKit/issues/357#issuecomment-584368923

The CareKit team has since added a detailed explanation of this in the readme, https://github.com/carekit-apple/CareKit#store-

**Comment by cadaniel** [comment]
> I believe your problem is you are not querying by the date which was brought up and answered here (you can read my original question and the feedback for the reasoning): https://github.com/carekit-apple/CareKit/issues/357#issuecomment-584355132
> 
> 
> 
> The CareKit team has since added a detailed explanation of this in the readme, https://github.com/carekit-apple/CareKit#store-

I've tired queuing by date and gotten the same results. It still returns outcomes not from the date given. 

I'm trying to see if a task has been completed for a day. My understanding from the docs is that an outcome would signal that the task has been completed. The documentation is actually kinda poor here. And the swiftUI examples don't compile if you pull them, or copy the code. 

It seems from your linked issue is that it pulls all the ones from a given and prior? That doesn't make sense to me.

**Comment by cbaker6** [comment]
> It seems from your linked issue is that it pulls all the ones from a given and prior? That doesn't make sense to me.

No, it pulls the current task that is active for Date(). I’m pretty sure this is working correctly in the framework as it has testcases for this. I also use CareKit in a few apps without issue.

I recommend trying the queries I linked in the readme to see if your results match. The code you showed in your screenshots didn’t use for: Date() and because your setup, the results you showed seem to be expected.

**Comment by cadaniel** [comment]
Yeah, I just went to my computer to double-check

```
 func getOutcomes(queryDate: Date, queryTask: OCKTask, completion: @escaping ([OCKOutcome]) -> Void) {
        //get date internval for day
        var comp: DateComponents = Calendar.current.dateComponents([.year, .month, .day], from: queryDate)
        comp.timeZone = TimeZone(abbreviation: "UTC")!
        let truncated = Calendar.current.date(from: comp)!
//        let nextDay = Calendar.current.date(byAdding: .day, value: 1, to: truncated)!
//        let dateInterval = DateInterval(start: truncated, end: nextDay)
        
        var query = OCKOutcomeQuery(for: truncated)
        query.taskIDs = [queryTask.id]
//        var query = OCKOutcomeQuery(id: queryTask.id)
//        query.dateInterval = dateInterval
        store.fetchOutcomes(query: query, callbackQueue: .main) { result in
            switch(result) {
            case .failure(let error):
                self.logger.critical("Unable to get data: \(error)")
                completion([])
            case .success(let outcomes):
                completion(outcomes)
            }
        }
    }
```

I didn't have a screen grab of it because I was trying different things. for: Date was the first. 

But the code in this comment, when truncated is June 9th at midnight UTC, returns results from June 6th at 8PM UTC. 

![Screen Shot 2021-06-09 at 8 04 51 PM](https://user-images.githubusercontent.com/5515671/121453193-fe44df00-c95d-11eb-8c5e-f1f8aa845130.png)
![Screen Shot 2021-06-09 at 8 04 38 PM](https://user-images.githubusercontent.com/5515671/121453198-ff760c00-c95d-11eb-958d-72ab234eb8ae.png)

regardless I don't expect a date range to fetch me items from out of range as well. I don't see any other date objects attached to OCKOutcome beyond created and updated. So a date range should also return the expected results.

**Comment by erik-apple** [comment]
The correct way to check if a task is complete is to use an event query. You'll get back an `OCKEvent` that has an optional `outcome` property attached to it.

I haven't had time to look at your code in detail yet (WWDC is a busy week!) but I suspect that there might be a misunderstanding about how the date interval works in the event query.

If you query for June 9th, you will get back events (with outcomes) that were scheduled to occur on June 9th. It doesn't matter if the outcome was actually created on June 6th or June 18th. On a calendar, the event would show up on June 9th, and the appropriate outcome will come attached to the event. The `createdDate` for the outcome might be in the future or the past, if the user swiped forward into the future and completed it early, or swiped back in the past and marked it complete after the fact.

**Comment by cadaniel** [comment]
Thanks for your reply @erik-apple 

Is there any planned docs update? The documentation on this repo is really kinda poor. The samples don't compile and feel like they haven't in a long while. There's no list of what views are available either here or on the developer.apple.com, and how to modify them. 

I'm hoping the code with me on Friday covers a lot of this.

**Comment by cadaniel** [comment]
Thaks for your help guys! 

Looks like I was looking for events rather than outcomes. But I'd still like to see more documentation, and working sample apps.

**Comment by erik-apple** [comment]
@cadaniel Which sample app is not compiling, and which version of Xcode are you using?
