### ISSUE TITLE
Xcode 13; Namespace collision

### ISSUE THREAD

**Issue by advatar** [carekit-apple/CareKit#594]
The new Swift concurrency is using Task which clashes with CareKitStore, f.i here:

 public func addTasks(_ tasks: [Task], callbackQueue: DispatchQueue = .main,
                         completion: ((Result<[Task], OCKStoreError>) -> Void)? = nil) {
        transaction(inserts: tasks, updates: [], deletes: []) { result in
            callbackQueue.async {
                completion?(result.map(\.inserts))
            }
        }
    }

**Comment by erik-apple** [comment]
Thanks for reporting this! We'll look into it!

**Comment by cadaniel** [comment]
@erik-apple Is there any progress on this?

**Comment by erik-apple** [comment]
Yes, the latest commit on the `main` branch fixes the issue!
