### ISSUE TITLE
Sample Apps Dont Compile

### ISSUE THREAD

**Issue by cadaniel** [carekit-apple/CareKit#595]
So OCKSample and OCKCatalog don't compile. 

![Screen Shot 2021-06-10 at 9 07 35 AM](https://user-images.githubusercontent.com/5515671/121549765-61b92600-c9cb-11eb-9e64-e9d19af274d9.png)
![Screen Shot 2021-06-10 at 9 05 37 AM](https://user-images.githubusercontent.com/5515671/121549767-61b92600-c9cb-11eb-9ef0-ae681f34c0c9.png)

I've cloned the care kit repo and opened up the projects. It didn't pull relative imports for the libraries so I added them view SPM, and this is the build result.

**Comment by ztlfrancis** [comment]
use the stable version should solve your problem

**Comment by cadaniel** [comment]
Yup, that was the problem.

**Comment by cadaniel** [comment]
Worth noting the readme says master when the branch name is now main

**Comment by cadaniel** [comment]
so the problem wasn't the stable version, as that was what I was using, but I needed to actually use the main branch, while the readme says master

**Comment by erik-apple** [comment]
Thanks for pointing out the outdated branch in the README. I'll update it to be more accurate.
