### ISSUE TITLE
Module 'CareKit' has no member named 'InstructionsTaskView'

### ISSUE THREAD

**Issue by cadaniel** [carekit-apple/CareKit#596]
I'm trying to create a synced view for a task, and I'm trying to copy the Readme

```
let controller = OCKTaskController(storeManager: state.careKitStore.syncStore)
                CareKit.InstructionsTaskView(controller: controller) { config in
                    
                }
```

Produces 

`Module 'CareKit' has no member named 'InstructionsTaskView'`

I've imported CareKit and CareKitUI.

I've also tried to wrap a view in SwiftUI

```
struct CareKitTaskButtonView: UIViewControllerRepresentable {
    
    let storeManager: OCKSynchronizedStoreManager
    let task: OCKTask
    let forDate: Date
    
    func updateUIViewController(_ uiViewController: UIViewControllerType, context: Context) {
    }
    
    func makeUIViewController(context: Context) -> some UIViewController {        
        let viewController = OCKSimpleTaskViewController(taskID: task.id, eventQuery: OCKEventQuery(for: forDate), storeManager: storeManager)
        
        return viewController
    }
}
```

This displays properly, but does not click properly

**Comment by erik-apple** [comment]
Thanks for opening an issue! Can you confirm which branch of CareKit you have checked out?
The `InstructionsTaskView` should exist on `main` but has not been merged into `stable` yet.

**Comment by cadaniel** [comment]
@erik-apple I have it checked out view SPM, so I'm assuming stable?

**Comment by erik-apple** [comment]
Yes, believe it defaults to the 2.0 tag by default. Try deleting your SPM dependency, then, when you re-add it, choose to check out a branch, and enter `main` for the branch name.

**Comment by gavirawson-apple** [comment]
That's strange! I can help you out with that issue. 

It's possible that the controller isn't able to find a task with the provided query parameters. Can you share the code where this `View` is instantiated, and maybe the code that adds tasks to the store?

Aside, I might be a good idea to consider following this snippet below. I will help make sure the underlying CareKit view is always up to date when the task query parameters change.

```swift
struct CareKitTaskButtonView: UIViewControllerRepresentable {

    let storeManager: OCKSynchronizedStoreManager
    let taskID: String
    let date: Date

    func updateUIViewController(
        _ uiViewController: OCKButtonLogTaskViewController,
        context: Context
    ) {
        // Here is the place to update the task query performed by the view
        // controller's controller when the query parameters change. Currently
        // the controller API doesn't allow for switching the `storeManager`,
        // but that's something we're hoping to improve in the future. For now,
        // it's best to ensure the `storeManager` stays constant. 
        uiViewController.controller.fetchAndObserveEvents(
            forTaskIDs: [taskID],
            eventQuery: OCKEventQuery(for: date)
        )
    }

    func makeUIViewController(context: Context) -> OCKButtonLogTaskViewController {
        return OCKButtonLogTaskViewController(
            taskID: taskID,
            eventQuery: OCKEventQuery(for: date),
            storeManager: storeManager
        )
    }
}
```

**Comment by cadaniel** [comment]
Thanks for the help!

I think between this, and my supplying the proper date to the view, I was able to get it working!

**Comment by erik-apple** [comment]
Great, glad to hear you got it working!
