### ISSUE TITLE
ORKCarePlanStore.setEndDate doesn't take effect on the activity's schedule

### ISSUE THREAD

**Issue by ninoguba** [carekit-apple/CareKit#60]
I added an activity to the store without an endDate set initially.

I use the setEndDate function of the CarePlanStore to set it to today and it returned successful.

BUT the activity's endDate remained nil.

Documentation below says what I'm doing is suppose to work:

> Once an activity has been added to a store, only the endDate can be changed by using the setEndDate:forActivity:completion: method.

Bug?

**Comment by ninoguba** [comment]
I'm looking to use this endDate property to only show a custom task when the activity is still active (endDate == nil or endDate < today), otherwise don't show the task.

**Comment by YuanZhu-apple** [comment]
Get a copy from store again, then you can find end date set.
