### ISSUE TITLE
[Question] Store on changed callback/on changed listener

### ISSUE THREAD

**Issue by cadaniel** [carekit-apple/CareKit#607]
So I have an app that people can add or remove tasks. How can I listen to updates so other parts of my app know to refresh when something has changed?

**Comment by cbaker6** [comment]
It sounds like you are looking for [OCKSynchronizedStoreManager](https://developer.apple.com/documentation/carekit/ocksynchronizedstoremanager) discussed in the README: https://github.com/carekit-apple/CareKit#synchronized-view-controllers-

You can essentially use that to listen to updates for any of the CareKit Entities. In particular, you might be looking to create custom views/cards: https://github.com/carekit-apple/CareKit#custom-synchronized-view-controllers-

Here it mentions:

```swift
// Update the custom view when the data in the store changes.
    func updateView(_ view: TaskButton, context: OCKSynchronizationContext<OCKTaskEvents?>) {
        let event = context.viewModel?.firstEvent
        view.titleLabel?.text = event?.task.title
        view.isSelected = event?.outcome != nil
    }
```

**Comment by cadaniel** [comment]
So I'm not using the UI components. I'm building in SwiftUI and using queries from the store.

**Comment by cbaker6** [comment]
You can still use it with SwiftUI. Here’s an older PR #479 that used SwiftUI and the synchronizer to make a slider card. Views or other it can be used. Before OCKRemoteSynchronizer, ParseCareKit used the synchronizer to sync with a remote.

Parts of that PR was eventually merged into #529

**Comment by cadaniel** [comment]
That's still using care kit ui components. Which I'm not doing because it doesn't give me the flexibility that I'm looking for.

**Comment by erik-apple** [comment]
@cbaker6 is correct. Even if you're not using CareKitUI, the `notificationPublisher` property on an instance of `OCKSynchronizedStoreManager` is the often the best way to be notified when a new task is added, updated, or deleted.

**Comment by cadaniel** [comment]
> @cbaker6 is correct. Even if you're not using CareKitUI, the `notificationPublisher` property on an instance of `OCKSynchronizedStoreManager` is the often the best way to be notified when a new task is added, updated, or deleted.

Thanks, that property is what I was looking for. I wasn't able to easily find it in the docs.

**Comment by erik-apple** [comment]
> I wasn't able to easily find it in the docs.

Yeah, sorry about that. It's not in the docs yet because it's a newly added property that is still in beta.
