### ISSUE TITLE
OCKCarePlanStore should also have functions to get events of activities with a certain group identifier and enumerate them

### ISSUE THREAD

**Issue by ninoguba** [carekit-apple/CareKit#61]
Similar to the following:

http://carekit.org/docs/Classes/OCKCarePlanStore.html#//api/name/eventsForActivity:date:completion:
http://carekit.org/docs/Classes/OCKCarePlanStore.html#//api/name/enumerateEventsOfActivity:startDate:endDate:handler:completion:

There should also be the following counterpart functions for activities with a specified group identifier.
- eventsForActivitiesWithGroupIdentifier
- enumerateEventsOfActivitiesWithGroupIdentifier

**Comment by srinathtm-apple** [comment]
Let's use #293 to track this...
