### ISSUE TITLE
Question : How to display OCKNotes from within OCKDetailViewController

### ISSUE THREAD

**Issue by itspradhan** [carekit-apple/CareKit#612]
Hi CareKit Contributors,

I have been struggling to override the didSelectTaskView function which currently displays the default OCKDetailViewController rather to use my own controller and allow users to display OCKNotes for that task. As I try to override below by subclassing my OCKChecklistTaskViewController which displays my Checklist tasks, I get the error message "Method does not override any method from its superclass". I'm using the Swift Dependency Package Manager for CareKit. Appreciate any help on this.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/1300606/125278345-310b3a00-e345-11eb-8ba0-562443d846e8.png">

**Comment by Hatsushira** [comment]
You can't override it because it comes from the protocol OCKTaskDisplayable. You just have to implement it.
https://github.com/carekit-apple/CareKit/blob/main/CareKitUI/CareKitUI/iOS/Task/OCKTaskDisplayable.swift

**Comment by itspradhan** [comment]
Thank you @Hatsushira
