### ISSUE TITLE
How to get the weekday of an OCKTask

### ISSUE THREAD

**Issue by Hatsushira** [carekit-apple/CareKit#613]
I'm currently trying to get the weekday of an task where it should be executed but I have difficulties to get it.
I know it's there because if I print the ScheduleElement it's shown. But how can I access it?

**Comment by gavirawson-apple** [comment]
The best way to compute the occurrences of a task is to fetch its events. Using a reference to the store, you can call `store.fetchEvents(...)`. Will that help you accomplish your goal?

**Comment by Hatsushira** [comment]
Thank you for your respone. It kinda helps, but it's not actually what I want. I want my users to be able to create tasks only for a specific weekkday and they should be able to edit this tasks and, if they want to, move it to a different day.  So from your answer I suppose it's not possible to see directly if the task is only for a specific weekday. I have to calculate the difference between the next task and take the weekday which it's executed on.
I think I store the weekday in the userInfo dictionary of the task for easier access.
Thanks for your help!

**Comment by gavirawson-apple** [comment]
Gotcha, that context is helpful. You should be able to access the schedule element on the task itself, which holds the interval of the schedule. If that property not accessible for some reason, feel free to open a PR to make it public. 

Storing the weekday in the user info dictionary works too, but it may be redundant.

**Comment by Hatsushira** [comment]
Thank you. I went for the userInfo, because I need the weekday more often f.e. displaying it different views. So it's easier (at least for me) to access it :)

**Comment by gavirawson-apple** [comment]
Great! Glad things are working!
