### ISSUE TITLE
Build errors in Xcode 13 beta4

### ISSUE THREAD

**Issue by drdavec** [carekit-apple/CareKit#616]
I am trying to build the WWDC Recover app using Xcode 13 beta4, and get two errors in CareKit using main branch:

'open(_:options:completionHandler:)' is unavailable in application extensions for iOS

'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

    open func contactView(_ contactView: UIView & OCKContactDisplayable, senderDidInitiateCall sender: Any?) {
        handleThrowable(method: controller.initiateCall) { url in
            UIApplication.shared.open(url, options: [:], completionHandler: nil)
        }
    }

**Comment by drdavec** [comment]
Issue documented in this forum post:
https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/10

**Comment by drdavec** [comment]
Release notes indicate that this requirement was reverted in Xcode 13 beta 5, released today.  Closing this issue.

Resolved in Xcode 13 Beta 5
You don’t need to annotate code as unavailable for use in application extensions if it references APIs annotated as unavailable for use in application extensions. This reverts a requirement that Xcode 13 Beta 3 introduced. (80615922) (FB9332020)

**Comment by erik-apple** [comment]
Thanks for keeping tabs on this!
