### ISSUE TITLE
Remove "#if swift(>=5.5)" once Xcode 13 supported by CI

### ISSUE THREAD

**Issue by JWStaiert** [carekit-apple/CareKit#619]
Remove the conditional compile directives "#if swift(>=5.5)" and the closing "#endif" once Xcode 13 is supported by CI.

**Comment by cbaker6** [comment]
Xcode 13 beta is publicly available in Actions https://github.blog/changelog/2021-08-16-github-actions-macos-11-big-sur-is-generally-available-on-github-hosted-runners/

**Comment by erik-apple** [comment]
@JWStaiert Are you interested in tackling this one, or should we open it to others?

**Comment by JWStaiert** [comment]
I'll handle it. I have some time tomorrow morning and it won't take long.

Jason
