### ISSUE TITLE
OCKContact should have a userInfo property too

### ISSUE THREAD

**Issue by ninoguba** [carekit-apple/CareKit#62]
This would be handy for additional custom properties that is attached to the contact besides the properties already provided.

**Comment by hdmdmm** [comment]
What about updates of last committed changes on cocoapods? There is no OCKContactInfo now. (

**Comment by srinathtm-apple** [comment]
@ninoguba @hdmdmm - please checkout the OCKNote object in CareKit 2.0 and let us know if that is sufficient!
