### ISSUE TITLE
Changes in care plan

### ISSUE THREAD

**Issue by scdi** [carekit-apple/CareKit#63]
The documentation for CareKit seems to indicate that if one wants to change what is a Careplan, the old care plan has to be deleted and a new one instantiated. If that is the case, Carekit would be impractical as in real life care plan changes occur all the time (say take this medication A 2 times a day to take a different medication B 5 times a day). See statement "As you iteratively develop and test your app, you often need to change the design of your treatment plan. This usually means removing the old activities before you can add new ones." http://carekit.org/docs/docs/AccessingCarePlanData/AccessingCarePlanData.html

**Comment by YuanZhu-apple** [comment]
@scdi You can end your old activity with an end date and add a new activity with a different identifier. 
So their identifiers are not conflict. I also recommend you to let both of them share the same group identifier, so you can trace them.

**Comment by scdi** [comment]
Yuan, thank you. That makes sense. Is there also a way to add a new
medication while keeping a previous one without recoding.
It seems that each medication would be hard coded at this time.

**Comment by YuanZhu-apple** [comment]
@scdi Medication itself is not an activity. An activity is more like a prescription. You can hard code medication, but medication + start + end + schedule makes an activity.

**Comment by scdi** [comment]
Yuan: Thank you so much. That is helpful. Thanks for taking the time to
explain.
jude

**Comment by scdi** [comment]
Yuan:

Can a healthkit store be used on iPad devices to store data collected with
CareKit?

**Comment by YuanZhu-apple** [comment]
@scdi No.
