### ISSUE TITLE
delete any task with ID

### ISSUE THREAD

**Issue by magray** [carekit-apple/CareKit#641]
Why are we not able to delete a task with just an ID string? Why does it have to be the whole OCKAnyTask object to delete.
You can retrieve a task with just an ID, but cannot delete.

**Comment by grawson** [comment]
Do you have a particular use case in mind for needing to delete a task using the `identifier` string?

**Comment by magray** [comment]
I use a custom struct that I've written to manage my Tasks, this includes displaying a list of such structs data. I only retrieve the actual OCKAnyTask when required using the ID that is part of my struct and also would like to delete by just the ID

**Comment by grawson** [comment]
I see, deleting an object by a particular ID sounds useful for that use case. I'm curious if others out there have a similar need.

At the moment, you can accomplish this by:

1. First fetching the task by a particular ID,
2. Then deleting the task.
