### ISSUE TITLE
Ability to hide detail disclosure in header views

### ISSUE THREAD

**Issue by williamkey123** [carekit-apple/CareKit#643]
I'm subclassing `OCKGridTaskViewController` and I don't want there to be any detail view. I've followed @gavirawson-apple 's recommendation in [issue 401](https://github.com/carekit-apple/CareKit/issues/401#issuecomment-610459298) to override the detail behavior, and that works great. But the problem is that there is still a detail disclosure arrow on the header.

<img width="345" alt="Screen Shot 2022-02-23 at 10 38 42 AM" src="https://user-images.githubusercontent.com/5880915/155385569-cf581aaa-22ce-411b-be4c-622af5a31312.png">

Tantalizingly, `OCKHeaderView` has a property for `showsDetailDisclosure`, but it's a `let` constant and I can't find a way to edit this. It seems like this functionality should be easily customizable... any advice?

**Comment by williamkey123** [comment]
Also... why are these items disclosure indicators in the first place? Disclosure indicators should be used to indicate an action that will push a new item onto a navigation stack, not present a view modally. This should be an info button.

**Comment by grawson** [comment]
You've found the right spot, there is no current way to set `showsDetailDisclosure`. You can hide it by accessing the image directly:

```swift
headerView.detailDisclosureImage?.isHidden = true
```

@williamkey123 you can access that same property to change it to an info button if needed.

```swift
detailDisclosureImage?.image = someNewImage
```

**Comment by williamkey123** [comment]
Awesome, thanks @grawson !
