### ISSUE TITLE
How to refresh the OCKDailyPageView automatically?

### ISSUE THREAD

**Issue by zxcheergo** [carekit-apple/CareKit#647]
I need to present different surveys to the participants with conditions. I implement it by first checking some conditions and then creating different ResearchKit survey accordingly. My problem is, when I did some activities to change the conditions, I need to pull-down manually to refresh the page. How and when should I call some functions to refresh? Thanks in advance.

**Comment by magray** [comment]
My app is mainly swiftui so I wrapped mine into a UIViewControllerRepresentable.
I have a binding which then calls the reload() function of the OCKDailyPageViewController

**Comment by zxcheergo** [comment]
> My app is mainly swiftui so I wrapped mine into a UIViewControllerRepresentable.
> I have a binding which then calls the reload() function of the OCKDailyPageViewController

Thanks for your reply. Could you please provide more details? I also use the SwiftUI. How to call the reload() with the UIViewControllerReprsentable?

**Comment by magray** [comment]
add a binding to the struct
`@Binding var reload: Bool`
then ...
`func updateUIViewController(_ uiViewController: OCKDailyPageViewController, context: Context) {`
`        if reload {`
 `               uiViewController.reload()`
`                reload = false`
  `              }`
`         }`

**Comment by zxcheergo** [comment]
> add a binding to the struct
> `@Binding var reload: Bool`
> then ...
> `func updateUIViewController(_ uiViewController: OCKDailyPageViewController, context: Context) {`
> ` if reload {`
> ` uiViewController.reload()`
> ` reload = false`
> ` }`
> ` }`

Thanks for your reply. And how to use the @binding var reload? Where should I change it to true? As the change of the surveys for OCKDailyPageView happened inside the OCKDailyPageViewController.

**Comment by magray** [comment]
I used it with `onAppear` function
