### ISSUE TITLE
Navigation bar is clear for iOS 15.0+

### ISSUE THREAD

**Issue by Hengyu** [carekit-apple/CareKit#650]
Hi team,

The navigation bar in `OCKDailyPageViewController` is clear. And one can verify this visual bug when scrolling the content.
Please see the attachment below to find the details.

<img width="905" alt="1" src="https://user-images.githubusercontent.com/4032674/161711066-5616f950-4d4d-43e9-896d-439a349c4a71.png">

This issue happens in iOS 15.0+ devices, and it does not appear in iOS 14.0+ devices.

Can someone take a look? Thanks in advance!

**Comment by magray** [comment]
Hi, can confirm I am seeing this as well. #650

**Comment by magray** [comment]
Here's the fix

`if #available(iOS 15.0, *) {`
   `         let navigationBarAppearance = UINavigationBarAppearance()`
     `       navigationBarAppearance.configureWithDefaultBackground()`
    `        UINavigationBar.appearance().standardAppearance = navigationBarAppearance`
        `    UINavigationBar.appearance().compactAppearance = navigationBarAppearance`
 `           UINavigationBar.appearance().scrollEdgeAppearance = navigationBarAppearance`
  `      }`
