### ISSUE TITLE
How to add Pull To Refresh feature?

### ISSUE THREAD

**Issue by majidsaleem105** [carekit-apple/CareKit#653]
Hello everyone,

I want to add Pull To Refresh feature to my app. I saw that Pull To Refresh is already there on the CareViewCotroller but I'm unable to over-write it to add my custom logic to sync data with the server.

I tried the following code in the `dailyPageViewController` function.
`let refresher = UIRefreshControl()

        let action = UIAction(title: "Refresh") { action in
            // Do anything you want to when the user pulls to refresh.
            // This will likely include removing, recreating, and re-adding
            // any content you've added to the listViewController.
        }
        refresher.addAction(action, for: .valueChanged)
        listViewController.listView.scrollView.refreshControl = refresher`

But the line generates an error. `'listView' is inaccessible due to 'internal' protection level`

Thanks,
- Majid S.

**Comment by gavirawson-apple** [comment]
To add custom refresh logic, override the `reload` method in a subclass of the `OCKDailyPageViewController`:

```swift
override open func reload() {
    super.reload()

    // Custom logic goes here...
}
```

**Comment by majidsaleem105** [comment]
Thanks, @gavirawson-apple for your advice. It worked for me.

**Comment by gavirawson-apple** [comment]
Glad to hear it!
