### ISSUE TITLE
General Question extending OCKCarePlanStore Model

### ISSUE THREAD

**Issue by tillmannheigel** [carekit-apple/CareKit#66]
I'd like to extend the OCKCarePlanStore to add additional data to activities. The problem is the OCKCarePlanStore model has no property to store additional kind of data. As I haven't seen any recommendation in the documentation to do so, I think this should be a part of the documentation or at least for a blog entry.

For example, I'd like to create an activity that contains a property videos containing plain links to some video stream. where should I start?

Thank you!

**Comment by YuanZhu-apple** [comment]
@tillmannheigel You can start with using the `userInfo` dictionary on OCKCarePlanActivity to carry the URL.

**Comment by tillmannheigel** [comment]
thx!
