### ISSUE TITLE
present a ResearchKit survey using SwiftUI

### ISSUE THREAD

**Issue by ykworld** [carekit-apple/CareKit#668]
Hi,

Can I present a ResearchKit survey using SwiftUI(InstructionsTaskView) and receive outcomes from it?

Thanks,

**Comment by gavirawson-apple** [comment]
Yes! See the [`OCKSurveyTaskViewController`](https://github.com/carekit-apple/CareKit/blob/main/CareKit/CareKit/iOS/Task/View%20Controllers/OCKSurveyTaskViewController.swift):



We also walk through this use case in a lot of detail in our WWDC talks:

[Build a research and care app, part 1: Setup onboarding](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwijjsW-9vb5AhWgKkQIHcxQCVYQwqsBegQIDRAB&url=https%3A%2F%2Fdeveloper.apple.com%2Fvideos%2Fplay%2Fwwdc2021%2F10068%2F&usg=AOvVaw3epGKD6FN8QCwp2s2K30kc)
[Build a research and care app, part 2: Schedule tasks](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&cad=rja&uact=8&ved=2ahUKEwjR4Pjw9vb5AhV9L0QIHZD6BvMQtwJ6BAgHEAI&url=https%3A%2F%2Fdeveloper.apple.com%2Fvideos%2Fplay%2Fwwdc2021%2F10069%2F&usg=AOvVaw3fgWE5OC8E0ZwonnIL5GDu)
[Build a research and care app, part 3: Visualize progress](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwijjsW-9vb5AhWgKkQIHcxQCVYQwqsBegQICxAB&url=https%3A%2F%2Fdeveloper.apple.com%2Fvideos%2Fplay%2Fwwdc2021%2F10282%2F&usg=AOvVaw36Dnxl9K3MhHu3u4jbaWWh)

Let me know if that helps!
