### ISSUE TITLE
Care card sub-labels, optional reps, rich descriptions

### ISSUE THREAD

**Issue by figshot** [carekit-apple/CareKit#67]
First, noob alert. I only started programming after I discovered CareKit. Sorry if I'm missing something super obvious -- if there are, I would appreciate your kind explanations 👍

I have a few suggestions for the Care Card, if this is an appropriate place to discuss it.

1. Sub-labels / differentiation of occurrences. For example, if a pill is to be taken three times daily, there would be 3 occurrences under the said pill in the Care Card. However, the left, middle and the right circles are counted the same: if they were to be labeled morning, afternoon and evening, and the middle one is left unchecked (signifying the afternoon dose was skipped), this might potentially be an interesting piece of information to the physician.

2. Optional/flexible number of occurrences. For example, a post-surgery recovery protocol requires the patient to walk down the hall x number of times every day (say, at least three times). I guess this could be asked in the Symptom Tracker, but it's a to-do item for the patient and I believe it belongs in the Care Card.

3. Rich descriptions. I guess I wanted to put something like a ResearchKit Active Task in the description for, as an example, an exercise. At the very least I want to put some pictures or movie clips to demonstrate how one could perform the said exercise. To me the OCKSample program doesn't seem to suggest that I could do this, but it'd be pretty useful if I could.

That's it for now -- thanks for reading.

**Comment by YuanZhu-apple** [comment]
>Sub-labels / differentiation of occurrences. For example, if a pill is to be taken three times daily, there would be 3 occurrences under the said pill in the Care Card. However, the left, middle and the right circles are counted the same: if they were to be labeled morning, afternoon and evening, and the middle one is left unchecked (signifying the afternoon dose was skipped), this might potentially be an interesting piece of information to the physician.

1) Maybe create three activities with different titles (morning, afternoon, evening )
2) Or not splitting into three activities, just brings up a question sheet to let user to confirm which session is the user intention. 

>Optional/flexible number of occurrences. For example, a post-surgery recovery protocol requires the patient to walk down the hall x number of times every day (say, at least three times). I guess this could be asked in the Symptom Tracker, but it's a to-do item for the patient and I believe it belongs in the Care Card.

Do you think it could work to show three circles in Care Card and a total number reporting question in Symptom Tracker?

>Rich descriptions. I guess I wanted to put something like a ResearchKit Active Task in the description for, as an example, an exercise. At the very least I want to put some pictures or movie clips to demonstrate how one could perform the said exercise. To me the OCKSample program doesn't seem to suggest that I could do this, but it'd be pretty useful if I could.

Use [imageURL on OCKCarePlanActivity](http://carekit.org/docs/Classes/OCKCarePlanActivity.html#//api/name/imageURL)

**Comment by figshot** [comment]
Yuan, thanks for the reply! I really appreciate it. Wish I had the programming chops to actually contribute to the solution...

> 1) Maybe create three activities with different titles (morning, afternoon, evening )
2) Or not splitting into three activities, just brings up a question sheet to let user to confirm which session is the user intention.

I agree that I can accomplish the original intention with (1). I might be getting picky on this, but I feel it may not look as well polished as it can be. As for (2), is it something I can do? Under my current understanding, tweaking OCKCareCardViewController's UI can't be done without diving into CareKit's source itself.

> [About #2] Do you think it could work to show three circles in Care Card and a total number reporting question in Symptom Tracker?

Hopefully I illustrated that the difference between `OCKCarePlanActivityTypeIntervention` and a `OCKCarePlanActivityTypeAssessment` isn't always as clear-cut. From the user's standpoint, the user would be asked to take three walks, and then they would be asked again how many times they went walking, in two separate tabs none less. A hybrid activity type may be able to streamline this.

> imageURL on OCKCarePlanActivity

I've been trying to figure out how the heck I would get a URL out of an image asset in `Assets.xcassets`, but I'm a noob and I can't figure out how. Would you mind if I ask how?

**Comment by YuanZhu-apple** [comment]
> I agree that I can accomplish the original intention with (1). I might be getting picky on this, but I feel it may not look as well polished as it can be. As for (2), is it something I can do? Under my current understanding, tweaking OCKCareCardViewController's UI can't be done without diving into CareKit's source itself.

For 2) you can launch your own VC by implementing [careCardViewController:didSelectButtonWithInterventionEvent](http://carekit.org/docs/Protocols/OCKCareCardViewControllerDelegate.html#//api/name/careCardViewController:didSelectButtonWithInterventionEvent:)

>Hopefully I illustrated that the difference between OCKCarePlanActivityTypeIntervention and a OCKCarePlanActivityTypeAssessment isn't always as clear-cut. From the user's standpoint, the user would be asked to take three walks, and then they would be asked again how many times they went walking, in two separate tabs none less. A hybrid activity type may be able to streamline this.

Agree, we need to add an optional section in CareCard for any activity which recommended but not required. #22 

>I've been trying to figure out how the heck I would get a URL out of an image asset in Assets.xcassets, but I'm a noob and I can't figure out how. Would you mind if I ask how?

The image has to be in the App's sandbox. [CreatingaCopyFilesBuildPhase](https://developer.apple.com/library/mac/recipes/xcode_help-project_editor/Articles/CreatingaCopyFilesBuildPhase.html)

**Comment by figshot** [comment]
Thank you for the help Yuan!

**Comment by ninoguba** [comment]
@figshot watch the later part of the [Getting Started with CareKit](https://developer.apple.com/videos/play/wwdc2016/237/) session and it shows an example of an app that customizes the CareCard to show a UI with images and videos, coincidentally demonstrating how to perform an exercise.

**Comment by figshot** [comment]
@ninoguba Thank you very much for the link. It was really informative.

I understand that a delegate was used somehow to call on a ResearchKit-like interface for the exercise demonstration, so now I gotta figure it out...

**Comment by khunshan** [comment]
So we have to go and add images NOT in xcassets and set imageURL. Ouch!
