### ISSUE TITLE
Bar chart changes every time i close and reopen the application

### ISSUE THREAD

**Issue by chiar15** [carekit-apple/CareKit#682]
Hi, I'm trying to create an application that allows the user to do a ditigal two finger tapping test and then shows the results in a bar chart in terms of number of tappings per second, comparing the two hands. The main problem is that every time i close the app and reopen it the chart changes showing the wrong results. I think there is a problem in the way i retrieve the outcome of the task, but i'm not sure. Here some code to explain better:

I created the task:

`static func tappingCheck() -> ORKTask {
            
            let tappingTask = ORKOrderedTask.twoFingerTappingIntervalTask(
                withIdentifier: "tappingTask",
                intendedUseDescription: nil,
                duration: 10,
                handOptions: .both,
                options: []
            )
            
            return tappingTask
        }`

and then i created a method to extract the outcome in the same class:

`static func extractTappingOutcome(_ result: ORKTaskResult) -> [OCKOutcomeValue]? {
        
        guard let tappingResultRight = result.results?
            .compactMap({ $0 as? ORKStepResult })
            .compactMap({ $0.result(forIdentifier: "tapping.right") })
            .compactMap({ $0 })
            .compactMap({ $0 as? ORKTappingIntervalResult })
            .first else {

            assertionFailure("Failed to parse a tapping interval result")
                    return nil
        }
        

        guard let tappingResultLeft = result.results?
            .compactMap({ $0 as? ORKStepResult })
            .compactMap({ $0.result(forIdentifier: "tapping.left") })
            .compactMap({ $0 })
            .compactMap({ $0 as? ORKTappingIntervalResult })
            .first else {

            assertionFailure("Failed to parse a tapping interval result")
                    return nil
        }

        var countsRight = OCKOutcomeValue(tappingResultRight.samples!.count)
        var countsLeft = OCKOutcomeValue(tappingResultLeft.samples!.count)
        
        return [countsRight, countsLeft]
    }`

Now, this is how i create the bar chart:

`let intervalSeriesRight = OCKDataSeriesConfiguration(
              taskID: TaskIDs.tappingCheck,
              legendTitle: "Right Hand",
              gradientStartColor: #colorLiteral(red: 0.2910306752, green: 0.3830310106, blue: 0.6710438132, alpha: 1),
              gradientEndColor: #colorLiteral(red: 0.3036136925, green: 0.3746574819, blue: 0.6712816954, alpha: 1),
              markerSize: 10,
              eventAggregator: .custom({ dailyEvents -> Double in
                  
                  var values = dailyEvents.flatMap { $0.outcome?.values.map { $0.integerValue ?? 0 } ?? [] }
                  
                  let currentValue = Double(values.first ?? 0 )/10.0
                  
              })
          )

        let intervalSeriesLeft = OCKDataSeriesConfiguration(
              taskID: TaskIDs.tappingCheck,
              legendTitle: "Left Hand",
              gradientStartColor: .systemOrange,
              gradientEndColor: .systemOrange,
              markerSize: 10,
              eventAggregator: .custom({ dailyEvents -> Double in

                  var values = dailyEvents.flatMap { $0.outcome?.values.map { $0.integerValue ?? 0 } ?? [] }
                  let currentValue = Double(values.last ?? 0)/10.0
                  
                  return currentValue
              })
          )
        
        
    
        
        let barChart = OCKCartesianChartViewController(
            plotType: .bar,
            selectedDate: Date(),
            configurations: [intervalSeriesRight, intervalSeriesLeft],
            storeManager: storeManager
        )
        

        barChart.chartView.headerView.titleLabel.text = "Number Of Taps Between Per Second"
          appendViewController(barChart, animated: false)`

**Comment by InfuriatingYetti** [comment]
Hi @chiar15, I am still learning but wanted to try to help! :)

I am wondering, you said that "every time i close the app and reopen it the chart changes showing the wrong results"....prior to closing and reopening the app was the bar chart correct? Like do you mean if you go through the two finger tapping test and then to the bar chart, the bar chart shows the correct data and only after closing and reopening it is incorrect; or is it incorrect from the start??

Depending on your answer you could try adding a print() at various points of the process to see if the data collected and passed is accurate and what you're expecting in the first place...it would show you in the console. At the very least you could  verify that the data looks right to begin with, have you tried this yet?

**Comment by InfuriatingYetti** [comment]
That's wild! I don't know either, I thought that if you're using charts with ResearchKit data and CareKit (like insights with bar, line, scatter charts) that the data was updated in real-time. Which it sound like it is doing correctly at first until you close and reopen it...so like you said, how is it messing it up?! lol

I have seen other posts where others have mentioned their apps act up sometimes and cleaning the build folder under `Product` and/or delete the app from the simulator and re-building/re-running it, restarting Xcode and/or the Mac itself can sometimes fix glitchy things...have you tried any of these things?

**Comment by chiar15** [comment]
Yes, i've tried but there's clearly some problem in the code because i've written this code also on another mac and it doesn't work. I don't really know, i thought that maybe there is something i'm not doing right in the event aggregator or in the use of the store

**Comment by InfuriatingYetti** [comment]
I'm trying something, no promises, but does something like this help?    

    var countsRight = OCKOutcomeValue(Double(tappingResultRight.samples!.count)/tappingResultRight.stepViewDuration)
    var countsLeft = OCKOutcomeValue(Double(tappingResultLeft.samples!.count)/tappingResultLeft.stepViewDuration)

and for left and right change:

    eventAggregator: .last

**Comment by chiar15** [comment]
I tried, but it gives me the following errors:
Value of type 'ORKTappingIntervalResult' has no member 'stepViewDuration';
Type 'OCKEventAggregator' has no member 'last'.

**Comment by InfuriatingYetti** [comment]
Make sure to back it up first (remember, still learning) before changing it around too much (see below)! I'm tagging some of the awesome pros that helped me before too lol @Pariecemckinney-apple or @gavirawson-apple or others are you able to help?

I think it has something to do with either how the tapping data is being stored in OCK core data and persisted when the app is reopening, how the code is interpreting the order in which the taps are occurring (maybe storing or reading them out of order or perhaps only using some of the tapping data), or maybe it isn't correctly calculating the taps per minute...that's all I've got, I tried using a little AI help here too lol - thank you for letting me try to help you! Trying to give back for all the great help I have received :) 

Let us know if this happens to work!

    static func extractTappingOutcome(_ result: ORKTaskResult) -> [OCKOutcomeValue]? {
    
        guard let tappingResultRight = result.results?
            .compactMap({ $0 as? ORKStepResult })
            .compactMap({ $0.result(forIdentifier: "tapping.right") })
            .compactMap({ $0 })
            .compactMap({ $0 as? ORKTappingIntervalResult })
            .first else {
    
            assertionFailure("Failed to parse a tapping interval result")
                    return nil
        }
        
    
        guard let tappingResultLeft = result.results?
            .compactMap({ $0 as? ORKStepResult })
            .compactMap({ $0.result(forIdentifier: "tapping.left") })
            .compactMap({ $0 })
            .compactMap({ $0 as? ORKTappingIntervalResult })
            .first else {
    
            assertionFailure("Failed to parse a tapping interval result")
                    return nil
        }
    
        let countsRight = tappingResultRight.samples?.count ?? 0
        let countsLeft = tappingResultLeft.samples?.count ?? 0
        let duration = tappingResultRight.duration
    
        let tappingRateRight = Double(countsRight) / duration
        let tappingRateLeft = Double(countsLeft) / duration
    
        let outcomeRight = OCKOutcomeValue(tappingRateRight)
        let outcomeLeft = OCKOutcomeValue(tappingRateLeft)
    
        return [outcomeRight, outcomeLeft]
    }

Also:


    let intervalSeriesLeft = OCKDataSeriesConfiguration(
        taskID: TaskIDs.tappingCheck,
        legendTitle: "Left Hand",
        gradientStartColor: .systemOrange,
        gradientEndColor: .systemOrange,
        markerSize: 10,
        eventAggregator: .custom({ events -> Double in
            let values = events.compactMap { $0.outcome?.values.first?.integerValue }
            let lastValue = Double(values.last ?? 0) / 10.0
            return lastValue
        })
    )


With sorting the tapping events first:

    let intervalSeriesRight = OCKDataSeriesConfiguration(
        taskID: TaskIDs.tappingCheck,
        legendTitle: "Right Hand",
        gradientStartColor: #colorLiteral(red: 0.2910306752, green: 0.3830310106, blue: 0.6710438132, alpha: 1),
        gradientEndColor: #colorLiteral(red: 0.3036136925, green: 0.3746574819, blue: 0.6712816954, alpha: 1),
        markerSize: 10,
        eventAggregator: .custom({ dailyEvents -> Double in
            let sortedEvents = dailyEvents.sorted { $0.scheduleEvent.occurrenceDate > $1.scheduleEvent.occurrenceDate }
            let values = sortedEvents.flatMap { $0.outcome?.values.map { $0.integerValue ?? 0 } ?? [] }
            let currentValue = Double(values.first ?? 0 )/10.0
            return currentValue
        })
    )
    
    let intervalSeriesLeft = OCKDataSeriesConfiguration(
        taskID: TaskIDs.tappingCheck,
        legendTitle: "Left Hand",
        gradientStartColor: .systemOrange,
        gradientEndColor: .systemOrange,
        markerSize: 10,
        eventAggregator: .custom({ dailyEvents -> Double in
            let sortedEvents = dailyEvents.sorted { $0.scheduleEvent.occurrenceDate > $1.scheduleEvent.occurrenceDate }
            let values = sortedEvents.flatMap { $0.outcome?.values.map { $0.integerValue ?? 0 } ?? [] }
            let currentValue = Double(values.first ?? 0)/10.0
            return currentValue
        })
    )
    
    let barChart = OCKCartesianChartViewController(
        plotType: .bar,
        selectedDate: Date(),
        configurations: [intervalSeriesRight, intervalSeriesLeft],
        storeManager: storeManager
    )
    
    barChart.chartView.headerView.titleLabel.text = "Number Of Taps Between Per Second"
    appendViewController(barChart, animated: false)

**Comment by chiar15** [comment]
thank

**Comment by gavirawson-apple** [comment]
Hey folks, looks like there's been a lot of good discussion on the topic. Thanks for helping out here @InfuriatingYetti.

What was your solution @chiar15? Ideally the framework should maintain the sort order of the outcome values, but I'll have to check if that's guaranteed. Alternatively, you can use the `kind` or `units` property on the outcome value to tag each value with the orientation (left vs right sides). You can later read that tag to extract the desired outcome in the aggregator block.

**Comment by chiar15** [comment]
Hi, actually my solution included the kind property using the same identifiers of the steps for the outcomes too.
