### ISSUE TITLE
CareKitStore-CoreData-NSReadOnlyPersistentStoreOption-ErrorMessage

### ISSUE THREAD

**Issue by CaTimeX** [carekit-apple/CareKit#684]
I can still build and run my project, but I always get this error message:

_"Attempt to add read-only file at path file:///Users/.../SourcePackages/checkouts/CareKit/CareKitStore/CareKitStore/CoreData/Migrations/2_0To2_1/2.0_2.1_Mapping.xcmappingmodel/xcmapping.xml read/write. Adding it read-only instead. This will be a hard error in the future; you must specify the NSReadOnlyPersistentStoreOption.
Command MappingModelCompile emitted errors but did not return a nonzero exit code to indicate failure"_

Can anyone help me? I added CareKit via Package Dependencies with the branch 'main' and also updated to the latest Version (CareKit Version 2.1).

**Comment by gavirawson-apple** [comment]
See the current recommendation here: #665
