### ISSUE TITLE
Move codebase to Swift

### ISSUE THREAD

**Issue by hansemannn** [carekit-apple/CareKit#70]
Hey guys,

I would love to help migrating the codebase to Swift. Is there an interest in this? It would probably be done in a fork or - even better - in an own branch to ensure that master still can be synced. Thanks guys!

Hans

**Comment by GJNilsen** [comment]
This is an excellent idea!

I have been playing with the thought in my head for a while now, I need to add some fundamentally vital functions to CareKit, like optional assessments and optional activities, as well as dependency between activities and assessments, so if an optional activity is done, like taking some medication, an assessment pops up to check the pain scale for example. This is not possible to do at the moment, and if I would do this in the current cute, a lot of existing classes has to be altered, so it means a major rewrite of the existing code.

I hope someone at Apple could head the migration, and also put some (human) resources into it. And of course Im willing to contribute, so Im in!

**Comment by YuanZhu-apple** [comment]
@hansemannn and @GJNilsen 
The new branch `stable_xcode80_candidate` is available now, the plan is to make an release base on it after XCode8 GM.

**Comment by hansemannn** [comment]
Hey @YuanZhu-apple, thanks for your efforts!
