### ISSUE TITLE
Add all the supported language string files into OCKTest

### ISSUE THREAD

**Issue by YuanZhu-apple** [carekit-apple/CareKit#72]
To support test CareKit strings in OCKTest.

**Comment by umerkhan-apple** [comment]
Tracking this as a request to update the OCKTest.strings file for localized versions of the file.

This doesn't necessarily mean that the localization for all strings has to be provided, it just means that we need the localization files to exist for all supported languages.

**Comment by srinathtm-apple** [comment]
Closing out issues that are no longer relevant due to the CareKit 2.0 beta update.
