### ISSUE TITLE
Local Notification Reminder for Activity

### ISSUE THREAD

**Issue by bishalg** [carekit-apple/CareKit#74]
Hi @umerkhan-apple,

First of all thanks a lot for such a wonderful presentation on WWDC - Getting Started with CareKit  #[237](https://developer.apple.com/videos/play/wwdc2016/237/).
At the event you showed [_Pt Pal_ app](https://itunes.apple.com/us/app/pt-pal-pro/id900483661?mt=8) developed extending CareKit.

It would be wonderful if the _activity_ in _CarePlan Store_ itself had the such field for different time in a day, and not only option to give number of times a day.

![vlcsnap-2016-06-18-21h57m37s308](https://cloud.githubusercontent.com/assets/805689/16174598/79d03890-35e8-11e6-9092-256897e05b10.png)

Q1. Is there work going on _Care Kit_ to support such feature to allow exact time for event during a day ?  If not would you suggest to send pull request extending current framework to store time of the day.

Q2. If _Yes_ on Q1; is _Care Kit_ about to support Local notification support in future, for the use case like in _Pt Pal_ app ? Again would you sending pull request for this case adding helper for Local Notification for _activity_ ?

**Comment by ninoguba** [comment]
@bishalg here's the correct link to the [Pt Pal Pro](https://itunes.apple.com/us/app/pt-pal-pro-ii/id1117083368?mt=8) app that was shown at WWDC.

**Comment by YuanZhu-apple** [comment]
@bishalg 

>Q1. Is there work going on Care Kit to support such feature to allow exact time for event during a day ? If not would you suggest to send pull request extending current framework to store time of the day.

I have thought about `exact time event` before, but we need to figure what is that mean. Is that mean one event is only available within a certain amount time window? Out side that window, the event is either disabled or hidden?

But IMHO, it could be confusing for people to see a changing list through out the day.

>Q2. If Yes on Q1; is Care Kit about to support Local notification support in future, for the use case like in Pt Pal app ? Again would you sending pull request for this case adding helper for Local Notification for activity ?

Even with current CareKit, the CarePlanStore can save additional custom information in `userInfo`. 
And the app need to provide the message to user too.  Can you let me know how the CareKit can help in Local notification?

**Comment by umerkhan-apple** [comment]
@bishalg Thanks--I'm glad you enjoyed the presentation!

Q1.
I agree with @YuanZhu-apple that this would require a proper definition of an `exact time event` and that definition might lead to user confusion, if it is not globally defined.

If we can find a good solution, then it would be great to incorporate this.

Q2.
iOS currently provides an easy way to schedule local notifications. PatientPal used that framework to make their notifications work. You can use the Care Card delegate to show your own UI, like their app, to allow the user to set different times.

Let me know if you any further questions! :)

**Comment by JianWang2016** [comment]
Hi, 

I concur with @bishalg that your presentation at WWDC was excellent!  Thanks so much for sharing with community CareKit.  

I support to attach a time with the event in the activity schedule as petitioned in Q1.   For intervention in the care card, time is absolutely necessary.  If a scheduled event is not completed within a time window, it should be allowed to expire (optional of cause).  Say if someone misses 8am medication, after 2 hours (the window to complete the event), he can simply wait until next scheduled event.  The window of time can be adjusted according to the nature of the activity.  For assessment, a window of time in addition to a specific time is also much needed.

 Again, thanks for considering this proposal.  I hope the closed issue is still monitored.
