### ISSUE TITLE
[OCKCareCard] Add a delegate method to request custom behavior for certain cells

### ISSUE THREAD

**Issue by bonebox** [carekit-apple/CareKit#76]
Prior to `1.0.2` this class was public, which was useful when I wanted to present a custom view controller via the delegate methods only part of the time (based on some condition), and display the default detail view controller the rest of the time--I could still manually instantiate `OCKCareCardDetailViewController`.  Assuming this was intentionally made private, is there an alternative for manually accessing it?

**Comment by YuanZhu-apple** [comment]
@bonebox I assume that you are using CocoaPod, before 1.0.2 CocoaPod was not config correctly to expose only public headers. For now, you can use pod 1.0.1 instead.

I think the right approach is add another delegate method to request custom behavior for certain cells.

**Comment by bonebox** [comment]
Correct, I failed to mention this is through CocoaPods.  I like your idea of the additional delegate method.

**Comment by erik-apple** [comment]
Closing this out following the release of CareKit 2.0.

Developers now have much more freedom to respond to interaction with content, so this should no longer be a problem.
