### ISSUE TITLE
Request for Tutorial

### ISSUE THREAD

**Issue by JoeyTheKiD** [carekit-apple/CareKit#79]
Hope this finds all of you well! My team and I are complete amateurs to programming, app development, GitHub, you name it. But we are really excited about the prospects of CareKit. Despite our fumbling around on various walk-throughs and online resources, we have been unsuccessful in building an app leveraging CareKit's framework. In short: we don't know what we are doing and want to ask you for some guidance. 

We are wondering if anyone can point us to some helpful resources that we have so far been unable to find. Ideally, we are hoping to find someone interested in giving us a tutorial on CareKit and navigating Xcode generally. We would pay you for your time, and we don't expect this to be too time-intensive (just a few hours of your time). Would anyone be interested in scheduling a tutorial for $100/hour?  Feel free to e-mail me at joe.carruth.hill@gmail.com if you are interested.

We are at a point where we have hit a wall and need some tactical questions answered. Please let me know if there is a better forum for me to direct this request.  I apologize if this request is inappropriate for this venue.

Thanks in advance and have a great weekend!

-Joe

**Comment by figshot** [comment]
A likewise beginner here!

I found Paul Hudson's [Hacking With Swift](https://www.hackingwithswift.com) very useful on being familiarized with Xcode in general, in addition to Apple's own [Jump Right In](https://developer.apple.com/library/ios/referencelibrary/GettingStarted/DevelopiOSAppsSwift/index.html). As for CareKit, a WWDC'16 presentation [Getting Started with CareKit](https://developer.apple.com/videos/play/wwdc2016/237/) will give you a pretty good tutorial.

**Comment by jrames** [comment]
I wrote a 2 part tutorial currently up on raywenderlich.com: 

https://www.raywenderlich.com/136010/carekit-tutorial-for-ios-part-1
https://www.raywenderlich.com/136496/carekit-tutorial-for-ios-part-2

Hope that helps!

**Comment by akshay-yadav-apple** [comment]
@JoeyTheKiD 
Hey!
Were the above mentioned resources helpful? Do you still need help with this issue?
