### ISSUE TITLE
Storing Data To Remote Server

### ISSUE THREAD

**Issue by marcsnts** [carekit-apple/CareKit#81]
How would I go about storing the Care Store's data remotely?

**Comment by ninoguba** [comment]
Implement RESTful APIs that you can call in your app to send data to your backend.  If you're storing PHI information, just make sure you are HIPAA compliant.

**Comment by marcsnts** [comment]
Where can I find/what is the method called when the care circles (in care completion) are being filled?

**Comment by ninoguba** [comment]
This should help point you in the right direction:
http://carekit.org/docs/Protocols/OCKCareCardViewControllerDelegate.html
