### ISSUE TITLE
connectViewController document sharing

### ISSUE THREAD

**Issue by scdi** [carekit-apple/CareKit#82]
Does the document sharing work for the sample app? No document shows up sharing is attempted. The email and calling actions both work.

**Comment by tktsubota** [comment]
Yes it does. It should bring up an action sheet for sharing. Hit "Print" and the print preview will show the document.

**Comment by scdi** [comment]
Is there an intermediary step that I am missing.
I just downloaded the sample. I ran it. This is what I see (attached).
It seems that I would need print capabilities.






Jude Jonassaint, RN

**Comment by tktsubota** [comment]
Looks like you haven't attached anything :(

I just realized that I was actually running OCKTest, not OCKSample. Try running OCKTest, and even on the simulator the print option shows up.

**Comment by scdi** [comment]
Thanks. I will do that. Is there a way to make the sample work or to have a handle on the PDF doc without having to use print like it is done with the consent document in RK?

**Comment by tktsubota** [comment]
If you go into the source of OCKSample, go to RootViewController and scroll down to line 237. There, a sample document is generated and you can handle it differently. Look into OCKDocument to see what properties you can use to present it.

In a CareKit app that you make, you use the OCKConnectViewController delegate to handle when the user taps the send reports button.

**Comment by umerkhan-apple** [comment]
@scdi Is this okay to close?

**Comment by scdi** [comment]
Hi,
Has this been added to the master branch?

**Comment by umerkhan-apple** [comment]
@scdi When running the sample app, you should see a share sheet pop up if you tap the share cell in the connect detail view controller. 

Let me know if that doesn't work.

**Comment by scdi** [comment]
The share sheet pop up but the document produced will not show a graph.

**Comment by ninoguba** [comment]
Check #117 for a related issue with charts not showing on the PDF document.

**Comment by umerkhan-apple** [comment]
Thanks @ninoguba ! @scdi Let me know if that helps or the issue still remains for you?

**Comment by akshay-yadav-apple** [comment]
Hey @scdi, 
Was the above suggestion helpful to resolve this issue?

**Comment by scdi** [comment]
I am sorry but I could not get it to work.

On Fri, Dec 1, 2017 at 5:08 AM, akshay-yadav-apple <notifications@github.com

**Comment by srinathtm-apple** [comment]
Closing out this issue as this is no longer relevant due to the CareKit 2.0 beta release..
