### ISSUE TITLE
createPDFDataWithCompletion

### ISSUE THREAD

**Issue by HeatherP75** [carekit-apple/CareKit#83]
Receiving an EXC_BAD_ACCESS self.webview error in OCKHTMLPDFWriter.m when trying to create an OCKDocument from a OCKBarChart. The error occurs when I attempt to access the document data using 'document.createPDFDataWithCompletion' which was defined in Apple's Documentation.

**Comment by YuanZhu-apple** [comment]
@HeatherP75 Did you retain the ORKDocument object? For example, make it a instance var.

**Comment by HeatherP75** [comment]
func CreateDocument(chart: OCKBarChart) {
        let subheadElement = OCKDocumentElementSubtitle(subtitle: "Weekly Summary")
        let chartElement = OCKDocumentElementChart(chart: chart)
        let paragraphElement = OCKDocumentElementParagraph(content: "Some paragraph here")
        
        let document = OCKDocument(title: "Weekly Update", elements: [subheadElement, chartElement, paragraphElement])
        document.pageHeader = "Some header"
        
        document.createPDFDataWithCompletion { (PDFData, errorOrNil) in
            if let error = errorOrNil {
                // perform proper error checking here...
                fatalError(error.localizedDescription)
            }
            // Do something with the PDF data here...
        }

Yes this is my function where I create the document.

**Comment by YuanZhu-apple** [comment]
@HeatherP75 Make `document` a instance var to retain it.

**Comment by umerkhan-apple** [comment]
@HeatherP75 Are we okay to close this issue?
