### ISSUE TITLE
CareCard / SymptomTracker - Allow Customization

### ISSUE THREAD

**Issue by pedrohugorm** [carekit-apple/CareKit#87]
I  noticed that some CareCard and SymptomTracker classes are not open to customization.
For instance:

If one wants to change the TableHeader of the CareCard, currently that's not possible.
If one wants to draw different Table Cells for the CareCard, this is also not possible.
Some customizations like that are blocked by the way the classes are designed.
Is this an expected behavior? Or you guys are open to changes on that?

**Comment by ninoguba** [comment]
If you need that kind of customization then you can do so by directly changing the CareKit source code or extending the classes.

**Comment by pedrohugorm** [comment]
That works when using objective-c only.
For Swift, most of the classes in the project are private.

**Comment by umerkhan-apple** [comment]
https://github.com/carekit-apple/CareKit/pull/86
