### ISSUE TITLE
Documentation: dead link

### ISSUE THREAD

**Issue by buffstop** [carekit-apple/CareKit#91]
[Link](http://carekit.org/docs/docs/Overview/ConnectingWithCareTeamsAndEmergencyContacts) in [API docu](http://carekit.org/docs/docs/Overview/Overview.html) is dead.

**Comment by ninoguba** [comment]
Here's the correct one:

http://carekit.org/docs/docs/ConnectingWithCareTeamsAndPersonalContacts/ConnectingWithCareTeamsAndPersonalContacts.html

**Comment by umerkhan-apple** [comment]
@buffstop or @ninoguba Would either one of you be able to do a PR to fix this?

**Comment by tktsubota** [comment]
Should this be closed? Seems to be working on `master` branch.
