### ISSUE TITLE
Is it possible to have your own symptoms input?

### ISSUE THREAD

**Issue by sashalondon** [carekit-apple/CareKit#92]
I want to use the care kit system but within my own UI. Is there a way to save the symptom scores without the care kit UI? I want to keep the activity completion part of the System Tracker page.

**Comment by umerkhan-apple** [comment]
You can always create your own symptoms by adding Assessments into the CarePlanStore and using the delegate on the Symptom Tracker to present appropriate tasks.

If you would like to just use the header in the Symptom Tracker (the activity completion part), then you can create your own view controller and just use the header view provided in the source.

**Comment by sashalondon** [comment]
Thank you.
