### ISSUE TITLE
Optional Symptoms that do not contribute to the percent complete?

### ISSUE THREAD

**Issue by sashalondon** [carekit-apple/CareKit#93]
I need to implement a symptom tracker that has 4 required symptoms that must be tracked over a 7 days (that is straight forward). I also need to have another 20 symptoms that may occur and I dont want the user to have to fill these in. I think its easier that if the user doesn't select it then you assume that they haven't had that symptom. Instead of going through and having to interact with 20 symptoms that you dont have. 

The 4 important symptoms have to show as completed and the rest shouldn't interfere with the days completion percentage.

2) How is it possible to work with a list view or other selection processes when you present the view to input the level of your symptom that you can use in Research Kit? I cannot see how you can have say multiple choice questions? 
Sorry I am using swift and cant change the Obj C code to suite.

**Comment by umerkhan-apple** [comment]
If I understand your use-case properly, I think one approach could be to add a `+` barButtonItem to the navigation bar. And when the user taps that, provide them with a list of optional symptoms that they can also report. When they select a symptom they want to add, then add it to the Care Plan Store, and it will show up on their Symptom Tracker.

**Comment by sashalondon** [comment]
In my case the clinical test requires to have a list of possible symptoms (complications). If you have these then you would give a score multiple on how many you have had. How can this list of symptoms be presented as a list but completes as a single item on the completion percentage?

**Comment by umerkhan-apple** [comment]
@sashalondon I would recommend creating one survey using RK, for example "Complications". In that survey, you can ask the user to report all the different symptoms. 

If one or more of those symptoms are not relevant to the user, they can just choose to skip it.
This way, it will show up on the Symptom Tracker as one item (the survey), and inside that item, there are multiple symptom related questions, and the user can choose to answer some, none, or all.
