### ISSUE TITLE
OCKSample app giving compilation errors

### ISSUE THREAD

**Issue by chiragramani** [carekit-apple/CareKit#94]
I added the CareKit framework as per the instructions illustrated in the documentation during building OCKSample app.Xcode complains missing dependency target "Missing dependency target "ResearchKit (from ResearchKit.xcodeproj)".Any help is deeply appreciated.

**Comment by umerkhan-apple** [comment]
https://github.com/carekit-apple/CareKit#installation

If you follow the installation command provided in the readme, it will automatically retrieve any submodules necessary (such as ResearchKit).
