### ISSUE TITLE
Not Clear Activity Tasks

### ISSUE THREAD

**Issue by marcsnts** [carekit-apple/CareKit#95]
Is it possible for activity task answers, specifically ORKTextAnswerFormat to not clear when tapping to write again. I would like it to be read/write instead of just write.

**Comment by YuanZhu-apple** [comment]
@marcsnts Can you elaborate it a little more? Maybe a or flow or a screenshot is helpful.

**Comment by umerkhan-apple** [comment]
@marcsnts Is this still an issue? If so, could you please file it on ResearchKit's repo. Thanks!
