### ISSUE TITLE
How often will pull requests be merged?

### ISSUE THREAD

**Issue by tktsubota** [carekit-apple/CareKit#97]
This isn't stated in the [Contributing Guidelines](https://github.com/carekit-apple/CareKit/blob/master/CONTRIBUTING.md), so how long do we have to wait before our pull requests get merged?

The last change to `master` was over a month ago, and there are some pending localization fixes from April that haven't been merged.

Could any of you enlighten me on the process of what each of these pull requests go through to be eligible to merge, and how often this happens? I have lots of ideas for contribution, but my first one still hasn't been closed or merged.

Thanks.

**Comment by YuanZhu-apple** [comment]
@tktsubota  Pending localization fixes will be reviewed by our localization team during the convergence. I will look at your PR.
